// Generated by ea_template/deploy.ps1 immediately before compilation.
// UNSTAMPED is deliberately visible and is rejected by runtime identity validation.
#ifndef LAB_BUILD_RECEIPT
#define LAB_BUILD_RECEIPT "UNSTAMPED" // @CFG_METADATA
#endif
