//+------------------------------------------------------------------+
//| MacroGate_Core.mqh - (Boss)_MacroGate watchdog logic (ORDER-073   |
//| Phase-3). Reduces new-entry lot and/or blocks NEW orders on the   |
//| carry-leg magics while the MRIS macro regime is RISK_OFF/STRESS.  |
//| It NEVER closes a position (reduce-lot doctrine) - it only steers  |
//| the chassis' NEW-order path via two GlobalVariables per magic:     |
//|   MACROGATE_BLOCK_<magic>   = 1     (chassis vetoes new orders)     |
//|   MACROGATE_LOTMULT_<magic> = 0.5   (chassis shrinks new-order lot) |
//| The chassis bridge lives in ea_template\core\Execution.mqh; locked |
//| / non-chassis EAs simply ignore the GVs.                           |
//|                                                                    |
//| Regime source: a dated timeline CSV (yyyy.MM.dd HH:mm,STATE,RI),   |
//| written live by the daily chain (mris_run + exporter) and, for the |
//| strategy tester, pre-generated by mris_backtest_timeline.ps1. At   |
//| each tick the guard picks the most recent row <= server-now and    |
//| acts on its STATE.                                                  |
//|                                                                    |
//| Fail-safe (same doctrine as NewsGuard): regime file missing /      |
//| unparsable / file older than StaleMaxHours / newest usable row     |
//| older than RowStaleMaxHours -> guard INACTIVE: every GV we own is   |
//| CLEARED (never leave an EA throttled), one throttled Alert. The     |
//| guard NEVER acts on stale/absent data. No DLL, no WebRequest.       |
//+------------------------------------------------------------------+
#ifndef BOSS_MACROGATE_CORE_MQH
#define BOSS_MACROGATE_CORE_MQH

#define MG_MAX_MAGICS      32
#define MG_MAX_ROWS        8192
#define MG_BLOCK_PREFIX    "MACROGATE_BLOCK_"
#define MG_LOTMULT_PREFIX  "MACROGATE_LOTMULT_"
#define MG_ALERT_THROTTLE_SEC (4 * 3600)

// regime state enum (higher = more risk-on)
#define MG_ST_RISK_ON   1
#define MG_ST_NEUTRAL   0
#define MG_ST_RISK_OFF (-1)
#define MG_ST_STRESS   (-2)
#define MG_ST_UNKNOWN  (-99)

// ---- settings -------------------------------------------------------------
double mg_lotMult          = 0.5;    // new-order lot multiplier while gated (0<..<1)
bool   mg_blockNew         = true;   // also veto new orders while gated
bool   mg_triggerRiskOff   = true;   // gate on RISK_OFF too (false = STRESS only)
int    mg_offsetHours      = 0;      // server = CSV time + N hours (daily granularity: usually 0)
int    mg_staleMaxHours    = 48;     // regime FILE older than this -> fail-safe
int    mg_rowStaleMaxHours = 48;     // newest usable ROW older than this vs now -> fail-safe

// ---- guarded magics -------------------------------------------------------
long mg_magic[MG_MAX_MAGICS];
bool mg_gated[MG_MAX_MAGICS];        // currently applying the gate to this magic (for ENTER/EXIT logs)
int  mg_count = 0;

// ---- loaded regime timeline (server time, ascending) ----------------------
datetime mg_rowTime[MG_MAX_ROWS];
int      mg_rowState[MG_MAX_ROWS];
int      mg_rowCount = 0;

bool     mg_ok           = false;
double   mg_fileAgeHours = -1.0;
datetime mg_lastAlert    = 0;
int      mg_notificationAttempts = 0;
string   mg_fname        = "";      // remembered for per-pass freshness re-check
bool     mg_common       = true;

//+------------------------------------------------------------------+
void MG_AlertCritical(const string msg)
{
   Print("[MACROGATE] ALERT: ", msg);
   Alert(msg);
   ResetLastError();
   mg_notificationAttempts++;
   if(!SendNotification(msg))
      PrintFormat("[MACROGATE] remote notification unavailable (err %d); set MetaQuotes ID in Options>Notifications", GetLastError());
}

void MG_Setup(const double lotMult, const bool blockNew, const bool triggerRiskOff,
              const int offsetHours, const int staleMaxHours, const int rowStaleMaxHours)
{
   mg_lotMult          = lotMult;
   mg_blockNew         = blockNew;
   mg_triggerRiskOff   = triggerRiskOff;
   mg_offsetHours      = offsetHours;
   mg_staleMaxHours    = staleMaxHours;
   mg_rowStaleMaxHours = rowStaleMaxHours;
}

string MG_BlockGV(const long magic)   { return MG_BLOCK_PREFIX   + IntegerToString(magic); }
string MG_LotMultGV(const long magic) { return MG_LOTMULT_PREFIX + IntegerToString(magic); }

int MG_StateFromString(const string s0)
{
   string s = s0; StringTrimLeft(s); StringTrimRight(s); StringToUpper(s);
   if(s == "RISK_ON")  return MG_ST_RISK_ON;
   if(s == "NEUTRAL")  return MG_ST_NEUTRAL;
   if(s == "RISK_OFF") return MG_ST_RISK_OFF;
   if(s == "STRESS")   return MG_ST_STRESS;
   return MG_ST_UNKNOWN;
}

string MG_StateName(const int st)
{
   if(st == MG_ST_RISK_ON)  return "RISK_ON";
   if(st == MG_ST_NEUTRAL)  return "NEUTRAL";
   if(st == MG_ST_RISK_OFF) return "RISK_OFF";
   if(st == MG_ST_STRESS)   return "STRESS";
   return "UNKNOWN";
}

//+------------------------------------------------------------------+
//| Parse "990201,990203;990110" (comma or semicolon). Returns count.|
//+------------------------------------------------------------------+
int MG_ParseMagics(const string cfg)
{
   mg_count = 0;
   string norm = cfg;
   StringReplace(norm, ";", ",");
   string items[];
   int n = StringSplit(norm, ',', items);
   for(int i = 0; i < n; i++)
   {
      string it = items[i];
      StringTrimLeft(it); StringTrimRight(it);
      if(it == "") continue;
      long m = StringToInteger(it);
      if(m <= 0) { PrintFormat("[MACROGATE] bad magic token '%s' - SKIPPED", it); continue; }
      if(mg_count >= MG_MAX_MAGICS) { Print("[MACROGATE] too many magics - rest ignored"); break; }
      mg_magic[mg_count] = m;
      mg_gated[mg_count] = false;
      mg_count++;
      PrintFormat("[MACROGATE] guard carry magic=%I64d", m);
   }
   if(mg_count == 0) Print("[MACROGATE] no magics configured - nothing to gate");
   return mg_count;
}

int MG_SplitCsv(const string line, string &fields[])
{
   int cap = ArraySize(fields), n = 0; bool inQ = false; string cur = "";
   int len = StringLen(line);
   for(int i = 0; i < len; i++)
   {
      ushort ch = StringGetCharacter(line, i);
      if(ch == '"') { inQ = !inQ; continue; }
      if(ch == ',' && !inQ) { if(n < cap) fields[n] = cur; n++; cur = ""; continue; }
      cur += ShortToString(ch);
   }
   if(n < cap) fields[n] = cur;
   n++;
   return n;
}

bool MG_IsStaleAge(const double ageHours)
{
   return (mg_staleMaxHours > 0 && ageHours > (double)mg_staleMaxHours);
}

//+------------------------------------------------------------------+
//| Load + validate the regime timeline CSV. Columns:                |
//|   datetime,state,ri[,flags]   header skipped. Rows kept ascending.|
//| datetime parsed by StringToTime ("yyyy.MM.dd HH:mm"), shifted by  |
//| mg_offsetHours to server time. Sets mg_ok.                        |
//+------------------------------------------------------------------+
bool MG_LoadRegime(const string fname, const bool common)
{
   mg_rowCount = 0; mg_ok = false; mg_fileAgeHours = -1.0;
   mg_fname = fname; mg_common = common;   // remember for MG_Tick's per-pass freshness re-check
   int cflag = (common ? FILE_COMMON : 0);
   if(!FileIsExist(fname, cflag))
   {
      PrintFormat("[MACROGATE] regime file '%s' NOT FOUND (%s) - guard INACTIVE",
                  fname, (common ? "Common\\Files" : "MQL5\\Files"));
      return false;
   }
   long mod = FileGetInteger(fname, FILE_MODIFY_DATE, common);
   if(mod > 0) mg_fileAgeHours = (double)(TimeLocal() - (datetime)mod) / 3600.0;
   if(MG_IsStaleAge(mg_fileAgeHours))
   {
      PrintFormat("[MACROGATE] regime file '%s' STALE (%.1f h > %d h) - guard INACTIVE",
                  fname, mg_fileAgeHours, mg_staleMaxHours);
      return false;
   }
   int h = FileOpen(fname, FILE_READ | FILE_TXT | FILE_ANSI | cflag, 0, CP_UTF8);
   if(h == INVALID_HANDLE)
   {
      PrintFormat("[MACROGATE] regime file '%s' open failed (err %d) - guard INACTIVE", fname, GetLastError());
      return false;
   }
   int line = 0, skipped = 0;
   datetime prevT = 0; bool ascending = true;
   while(!FileIsEnding(h) && mg_rowCount < MG_MAX_ROWS)
   {
      string l = FileReadString(h); line++;
      if(line == 1) continue;               // header
      if(StringLen(l) < 8) continue;
      string f[6];
      if(MG_SplitCsv(l, f) < 2) { skipped++; continue; }
      string ts = f[0]; StringTrimLeft(ts); StringTrimRight(ts);
      // require a real "yyyy.MM.dd HH:mm" shape (a '.' inside the date part before the
      // space) so StringToTime cannot silently coerce a malformed token (Codex QA 2026-07-18)
      int sp = StringFind(ts, " ");
      if(sp < 0 || StringFind(StringSubstr(ts, 0, sp), ".") < 0) { skipped++; continue; }
      datetime t = StringToTime(ts);
      if(t <= 0) { skipped++; continue; }
      t += (datetime)(mg_offsetHours * 3600);
      int st = MG_StateFromString(f[1]);
      if(st == MG_ST_UNKNOWN) { skipped++; continue; }
      if(mg_rowCount > 0 && t < prevT) ascending = false;
      mg_rowTime[mg_rowCount]  = t;
      mg_rowState[mg_rowCount] = st;
      prevT = t;
      mg_rowCount++;
   }
   FileClose(h);
   if(mg_rowCount == 0)
   {
      PrintFormat("[MACROGATE] regime file '%s' parsed ZERO valid rows (%d skipped) - guard INACTIVE", fname, skipped);
      return false;
   }
   if(!ascending)
   {
      // MG_RowAsOf assumes ascending and breaks early; an unsorted file could skip a valid
      // as-of STRESS row and permit orders. Fail SAFE instead of trusting it (Codex QA 2026-07-18).
      Print("[MACROGATE] regime rows NOT strictly ascending - guard INACTIVE (fix the exporter/sort)");
      mg_rowCount = 0; mg_ok = false;
      return false;
   }
   mg_ok = true;
   PrintFormat("[MACROGATE] regime loaded: %d row(s), %d skipped, file age %.1f h, server = CSV %+d h",
               mg_rowCount, skipped, mg_fileAgeHours, mg_offsetHours);
   return true;
}

//+------------------------------------------------------------------+
//| Index of the most recent row with time <= nowServer, else -1.    |
//+------------------------------------------------------------------+
int MG_RowAsOf(const datetime nowServer)
{
   int idx = -1;
   for(int i = 0; i < mg_rowCount; i++)
   {
      if(mg_rowTime[i] <= nowServer) idx = i;
      else break;   // rows ascending
   }
   return idx;
}

bool MG_StateTriggers(const int st)
{
   if(st == MG_ST_STRESS) return true;
   if(st == MG_ST_RISK_OFF && mg_triggerRiskOff) return true;
   return false;
}

void MG_ClearMagic(const int i, const string why)
{
   string bgv = MG_BlockGV(mg_magic[i]);
   string lgv = MG_LotMultGV(mg_magic[i]);
   if(GlobalVariableCheck(bgv)) GlobalVariableDel(bgv);
   if(GlobalVariableCheck(lgv)) GlobalVariableDel(lgv);
   if(mg_gated[i]) PrintFormat("[MACROGATE] gate CLEARED magic=%I64d (%s)", mg_magic[i], why);
   mg_gated[i] = false;
}

void MG_ClearAll(const string why)
{
   for(int i = 0; i < mg_count; i++) MG_ClearMagic(i, why);
}

//+------------------------------------------------------------------+
//| Main watchdog pass. Call from OnTimer with the server clock.     |
//+------------------------------------------------------------------+
void MG_Tick(const datetime nowServer)
{
   // per-pass freshness re-check (LIVE only): a file that goes stale or is deleted BETWEEN
   // reloads must fail safe promptly, not wait for the next reload (Codex QA 2026-07-18).
   // Skipped in the tester, where the CSV is static/fresh and StaleMaxHours is set huge.
   if(mg_ok && !MQLInfoInteger(MQL_TESTER) && StringLen(mg_fname) > 0)
   {
      int cflag2 = (mg_common ? FILE_COMMON : 0);
      if(!FileIsExist(mg_fname, cflag2)) { mg_ok = false; }
      else
      {
         long mod = FileGetInteger(mg_fname, FILE_MODIFY_DATE, mg_common);
         if(mod > 0 && MG_IsStaleAge((double)(TimeLocal() - (datetime)mod) / 3600.0)) mg_ok = false;
      }
   }
   if(!mg_ok)
   {
      MG_ClearAll("fail-safe: regime data unavailable");
      if(TimeLocal() - mg_lastAlert >= MG_ALERT_THROTTLE_SEC)
      {
         mg_lastAlert = TimeLocal();
         MG_AlertCritical("MacroGate INACTIVE: regime file missing/stale - carry legs are UNGATED");
      }
      return;
   }
   int r = MG_RowAsOf(nowServer);
   if(r < 0)
   {
      // now is before the first regime row - nothing known yet, stay inert (no gate)
      MG_ClearAll("no regime row on-or-before now");
      return;
   }
   // newest usable row too old vs now -> treat as a data gap, fail-safe
   double rowAgeH = (double)(nowServer - mg_rowTime[r]) / 3600.0;
   if(mg_rowStaleMaxHours > 0 && rowAgeH > (double)mg_rowStaleMaxHours)
   {
      MG_ClearAll(StringFormat("regime row gap (%.1f h > %d h)", rowAgeH, mg_rowStaleMaxHours));
      if(TimeLocal() - mg_lastAlert >= MG_ALERT_THROTTLE_SEC)
      {
         mg_lastAlert = TimeLocal();
         MG_AlertCritical(StringFormat("MacroGate INACTIVE: regime row gap %.1f h - carry legs UNGATED", rowAgeH));
      }
      return;
   }

   int st = mg_rowState[r];
   bool trig = MG_StateTriggers(st);
   for(int i = 0; i < mg_count; i++)
   {
      if(trig)
      {
         if(mg_blockNew) GlobalVariableSet(MG_BlockGV(mg_magic[i]), 1.0);
         else { string bgv = MG_BlockGV(mg_magic[i]); if(GlobalVariableCheck(bgv)) GlobalVariableDel(bgv); }  // lot-only: never leave a stale block (Codex QA 2026-07-18)
         GlobalVariableSet(MG_LotMultGV(mg_magic[i]), mg_lotMult);
         if(!mg_gated[i])
            PrintFormat("[MACROGATE] gate ON magic=%I64d state=%s lotMult=%.2f block=%s @ %s",
                        mg_magic[i], MG_StateName(st), mg_lotMult, (mg_blockNew?"1":"0"),
                        TimeToString(nowServer, TIME_DATE|TIME_MINUTES));
         mg_gated[i] = true;
      }
      else
      {
         MG_ClearMagic(i, "regime not triggering (" + MG_StateName(st) + ")");
      }
   }
}

//+------------------------------------------------------------------+
void MG_Deinit()
{
   MG_ClearAll("deinit reconcile");
}

#endif // BOSS_MACROGATE_CORE_MQH
