//+------------------------------------------------------------------+
//| MacroGate_Core.mqh - (Boss)_MacroGate watchdog logic (ORDER-073   |
//| Phase-3). Reduces new-entry lot and/or blocks NEW orders on the   |
//| carry-leg magics while the MRIS macro regime is RISK_OFF/STRESS.  |
//| It NEVER closes a position (reduce-lot doctrine) - it only steers  |
//| the chassis' NEW-order path via two GlobalVariables per magic:     |
//|   MACROGATE_BLOCK_<magic>   = 1     (chassis vetoes new orders)     |
//|   MACROGATE_LOTMULT_<magic> = 0.5   (chassis shrinks new-order lot) |
//| The chassis bridge lives in ea_template\core\Execution.mqh; locked |
//| / non-chassis EAs simply ignore the GVs.                           |
//|                                                                    |
//| Regime source: a dated timeline CSV (yyyy.MM.dd HH:mm,STATE,RI),   |
//| written live by the daily chain (mris_run + exporter) and, for the |
//| strategy tester, pre-generated by mris_backtest_timeline.ps1. At   |
//| each tick the guard picks the most recent row <= server-now and    |
//| acts on its STATE.                                                  |
//|                                                                    |
//| Fail-safe (same doctrine as NewsGuard): regime file missing /      |
//| unparsable / file older than StaleMaxHours / newest usable row     |
//| older than RowStaleMaxHours -> guard INACTIVE: every GV we own is   |
//| CLEARED (never leave an EA throttled), one throttled Alert. The     |
//| guard NEVER acts on stale/absent data. No DLL, no WebRequest.       |
//+------------------------------------------------------------------+
#ifndef BOSS_MACROGATE_CORE_MQH
#define BOSS_MACROGATE_CORE_MQH

#define MG_MAX_MAGICS      32
#define MG_MAX_ROWS        8192
#define MG_BLOCK_PREFIX    "MACROGATE_BLOCK_"
#define MG_LOTMULT_PREFIX  "MACROGATE_LOTMULT_"
#define MG_ALERT_THROTTLE_SEC (4 * 3600)

// regime state enum (higher = more risk-on)
#define MG_ST_RISK_ON   1
#define MG_ST_NEUTRAL   0
#define MG_ST_RISK_OFF (-1)
#define MG_ST_STRESS   (-2)
#define MG_ST_UNKNOWN  (-99)
#define MG_ST_INVALID  (-100)

// ---- settings -------------------------------------------------------------
double mg_lotMult          = 0.5;    // new-order lot multiplier while gated (0<..<1)
bool   mg_blockNew         = true;   // also veto new orders while gated
bool   mg_triggerRiskOff   = true;   // gate on RISK_OFF too (false = STRESS only)
int    mg_offsetHours      = 0;      // server = CSV time + N hours (daily granularity: usually 0)
int    mg_staleMaxHours    = 48;     // regime FILE older than this -> fail-safe
int    mg_rowStaleMaxHours = 48;     // newest usable ROW older than this vs now -> fail-safe

// ---- guarded magics -------------------------------------------------------
long mg_magic[MG_MAX_MAGICS];
bool mg_gated[MG_MAX_MAGICS];        // currently applying the gate to this magic (for ENTER/EXIT logs)
int  mg_count = 0;

// ---- loaded regime timeline (server time, ascending) ----------------------
datetime mg_rowTime[MG_MAX_ROWS];
int      mg_rowState[MG_MAX_ROWS];
int      mg_rowCount = 0;

bool     mg_ok           = false;
double   mg_fileAgeHours = -1.0;
datetime mg_lastAlert    = 0;
int      mg_notificationAttempts = 0;
string   mg_fname        = "";      // remembered for per-pass freshness re-check
bool     mg_common       = true;

//+------------------------------------------------------------------+
void MG_AlertCritical(const string msg)
{
   Print("[MACROGATE] ALERT: ", msg);
   Alert(msg);
   ResetLastError();
   mg_notificationAttempts++;
   if(!SendNotification(msg))
      PrintFormat("[MACROGATE] remote notification unavailable (err %d); set MetaQuotes ID in Options>Notifications", GetLastError());
}

void MG_Setup(const double lotMult, const bool blockNew, const bool triggerRiskOff,
              const int offsetHours, const int staleMaxHours, const int rowStaleMaxHours)
{
   mg_lotMult          = lotMult;
   mg_blockNew         = blockNew;
   mg_triggerRiskOff   = triggerRiskOff;
   mg_offsetHours      = offsetHours;
   mg_staleMaxHours    = staleMaxHours;
   mg_rowStaleMaxHours = rowStaleMaxHours;
}

string MG_BlockGV(const long magic)   { return MG_BLOCK_PREFIX   + IntegerToString(magic); }
string MG_LotMultGV(const long magic) { return MG_LOTMULT_PREFIX + IntegerToString(magic); }

int MG_StateFromString(const string s0)
{
   string s = s0; StringTrimLeft(s); StringTrimRight(s); StringToUpper(s);
   if(s == "RISK_ON")  return MG_ST_RISK_ON;
   if(s == "NEUTRAL")  return MG_ST_NEUTRAL;
   if(s == "RISK_OFF") return MG_ST_RISK_OFF;
   if(s == "STRESS")   return MG_ST_STRESS;
   if(s == "UNKNOWN")  return MG_ST_UNKNOWN;
   return MG_ST_INVALID;
}

string MG_StateName(const int st)
{
   if(st == MG_ST_RISK_ON)  return "RISK_ON";
   if(st == MG_ST_NEUTRAL)  return "NEUTRAL";
   if(st == MG_ST_RISK_OFF) return "RISK_OFF";
   if(st == MG_ST_STRESS)   return "STRESS";
   if(st == MG_ST_UNKNOWN)  return "UNKNOWN";
   return "INVALID";
}

//+------------------------------------------------------------------+
//| Parse "990201,990203;990110" (comma or semicolon). Returns count.|
//+------------------------------------------------------------------+
int MG_ParseMagics(const string cfg)
{
   mg_count = 0;
   string norm = cfg;
   StringReplace(norm, ";", ",");
   string items[];
   int n = StringSplit(norm, ',', items);
   for(int i = 0; i < n; i++)
   {
      string it = items[i];
      StringTrimLeft(it); StringTrimRight(it);
      if(it == "") continue;
      long m = StringToInteger(it);
      if(m <= 0) { PrintFormat("[MACROGATE] bad magic token '%s' - SKIPPED", it); continue; }
      if(mg_count >= MG_MAX_MAGICS) { Print("[MACROGATE] too many magics - rest ignored"); break; }
      mg_magic[mg_count] = m;
      mg_gated[mg_count] = false;
      mg_count++;
      PrintFormat("[MACROGATE] guard carry magic=%I64d", m);
   }
   if(mg_count == 0) Print("[MACROGATE] no magics configured - nothing to gate");
   return mg_count;
}

int MG_SplitCsv(const string line, string &fields[])
{
   int cap = ArraySize(fields), n = 0; bool inQ = false; string cur = "";
   int len = StringLen(line);
   for(int i = 0; i < len; i++)
   {
      ushort ch = StringGetCharacter(line, i);
      if(ch == '"') { inQ = !inQ; continue; }
      if(ch == ',' && !inQ) { if(n < cap) fields[n] = cur; n++; cur = ""; continue; }
      cur += ShortToString(ch);
   }
   if(n < cap) fields[n] = cur;
   n++;
   return n;
}

bool MG_IsStaleAge(const double ageHours)
{
   return (mg_staleMaxHours > 0 && ageHours > (double)mg_staleMaxHours);
}

// One parser owns both the legacy text-file loader and the qualification
// same-buffer loader. This preserves the accepted timestamp/state/UNKNOWN and
// ascending-row semantics while allowing qualified tester bytes to be hashed
// and parsed without reopening a mutable path.
void MG_ParseRegimeDataLine(const string line, int &skipped,
                            datetime &prevT, bool &ascending)
{
   if(StringLen(line) < 8) return;
   string f[6];
   if(MG_SplitCsv(line, f) < 2) { skipped++; return; }
   string ts = f[0]; StringTrimLeft(ts); StringTrimRight(ts);
   // Require a real yyyy.MM.dd HH:mm shape so StringToTime cannot silently
   // coerce a malformed token.
   int sp = StringFind(ts, " ");
   if(sp < 0 || StringFind(StringSubstr(ts, 0, sp), ".") < 0)
   {
      skipped++;
      return;
   }
   datetime t = StringToTime(ts);
   if(t <= 0) { skipped++; return; }
   t += (datetime)(mg_offsetHours * 3600);
   int st = MG_StateFromString(f[1]);
   if(st == MG_ST_INVALID) { skipped++; return; }
   // Explicit UNKNOWN remains selectable only in the tester. Non-tester
   // loading retains the historical skip behavior.
   if(st == MG_ST_UNKNOWN && !MQLInfoInteger(MQL_TESTER))
   {
      skipped++;
      return;
   }
   // Deliberately preserve the accepted rule: equal timestamps are accepted;
   // only a backwards timestamp marks the file unsorted.
   if(mg_rowCount > 0 && t < prevT) ascending = false;
   mg_rowTime[mg_rowCount]  = t;
   mg_rowState[mg_rowCount] = st;
   prevT = t;
   mg_rowCount++;
}

#ifdef LAB_MG_TESTER_EVIDENCE_QUAL
// Source-compiled byte identities. No runtime sidecar may supply or replace an
// expected digest. Test-only probe overrides are compile-time literals and are
// never accepted by the production Boss15 map.
bool MGTT_ExpectedFeed(const string fname, string &sha256, long &bytes,
                       int &rows, string &first, string &last)
{
#ifdef MGTT_PROBE_EXPECTED_FILENAME
   if(fname == MGTT_PROBE_EXPECTED_FILENAME)
   {
      sha256 = MGTT_PROBE_EXPECTED_SHA256;
      bytes  = MGTT_PROBE_EXPECTED_BYTES;
      rows   = MGTT_PROBE_EXPECTED_ROWS;
      first  = MGTT_PROBE_EXPECTED_FIRST;
      last   = MGTT_PROBE_EXPECTED_LAST;
      return true;
   }
#endif
   if(fname == "REAL_FULL_2020_2025_macrogate_native.csv")
   { sha256="6aba7e1e7bd01e82469db580ae666c9903803c4fb8d206f4cc44f8aab8afbb2a"; bytes=73544; rows=2192; first="2020.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "MAIN_seed_2026092501_macrogate_native.csv")
   { sha256="dc5b31de1e0d5809c52c388302533b7228a52a389eb37873be50609ba6d30198"; bytes=36118; rows=1096; first="2023.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "BWD_seed_2026092501_macrogate_native.csv")
   { sha256="951bff972d0bcc9ef6edb556782cc4e11eafac3194ce0259ee87d6b5364d5320"; bytes=37446; rows=1096; first="2020.01.01 02:00"; last="2022.12.31 02:00"; return true; }
   if(fname == "MAIN_seed_2026092502_macrogate_native.csv")
   { sha256="f6ce2f5cf0be072e54641bad333871c70fd11ea7b8c4858dd7d600ea187e93a2"; bytes=36121; rows=1096; first="2023.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "BWD_seed_2026092502_macrogate_native.csv")
   { sha256="fa9efdd623dfd2d35cd2bfdda457e505de4cebc1ef990f13c9fb582b9cd248b5"; bytes=37446; rows=1096; first="2020.01.01 02:00"; last="2022.12.31 02:00"; return true; }
   if(fname == "MAIN_seed_2026092503_macrogate_native.csv")
   { sha256="e437e631cd5c158c1b34a3158753bbab767db6de8964457cebff73bc76504344"; bytes=36120; rows=1096; first="2023.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "BWD_seed_2026092503_macrogate_native.csv")
   { sha256="7f8f2aad388b9dca7d8e2c53808233987724569db014852bbd7c62c074d3fe98"; bytes=37449; rows=1096; first="2020.01.01 02:00"; last="2022.12.31 02:00"; return true; }
   if(fname == "MAIN_seed_2026092504_macrogate_native.csv")
   { sha256="1eacab594ebd5a73b1291965d78231611d58912b385910e82a3beae07132ddfd"; bytes=36120; rows=1096; first="2023.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "BWD_seed_2026092504_macrogate_native.csv")
   { sha256="8bbe8cf5632685c4b3e3c7a1fd659f35ea96d2297b1e74057609e8b435c5daa8"; bytes=37449; rows=1096; first="2020.01.01 02:00"; last="2022.12.31 02:00"; return true; }
   if(fname == "MAIN_seed_2026092505_macrogate_native.csv")
   { sha256="1ffcfa71ade5256671196fd7530ecacef60e1e227b7aa7d1e6566d5e35f06c5e"; bytes=36119; rows=1096; first="2023.01.01 02:00"; last="2025.12.31 02:00"; return true; }
   if(fname == "BWD_seed_2026092505_macrogate_native.csv")
   { sha256="ab2f6c7818c41ef3502a6a67c2bfa1ae0a707259ad72b6bfb9fd463b7787b3c5"; bytes=37445; rows=1096; first="2020.01.01 02:00"; last="2022.12.31 02:00"; return true; }
   return false;
}

bool MGTT_Sha256Hex(uchar &raw[], string &hex)
{
   uchar empty_key[];
   uchar digest[];
   ArrayResize(empty_key, 0);
   ArrayResize(digest, 0);
   int n = CryptEncode(CRYPT_HASH_SHA256, raw, empty_key, digest);
   if(n != 32 || ArraySize(digest) != 32)
   {
      hex = "";
      return false;
   }
   hex = "";
   for(int i=0; i<32; i++) hex += StringFormat("%02x", (int)digest[i]);
   return (StringLen(hex) == 64);
}

string g_mgtt_feed_session="UNBOUND";
string g_mgtt_feed_build="UNBOUND";
string g_mgtt_feed_config="UNBOUND";

void MGTT_FeedFailure(const string fname, const string reason,
                      const string expected_sha, const string observed_sha,
                      const long expected_bytes, const long observed_bytes,
                      const long bytes_read)
{
   PrintFormat("[MGTT_FEED] runtime_session=%s build_receipt=%s effective_config_fingerprint=%s requested_filename=%s source_class=TESTER_SANDBOX_NONCOMMON expected_sha256=%s observed_sha256=%s expected_size_bytes=%I64d file_size_bytes=%I64d bytes_read=%I64d load_status=FAIL failure=%s",
               g_mgtt_feed_session,g_mgtt_feed_build,g_mgtt_feed_config,fname, expected_sha, observed_sha, expected_bytes,
               observed_bytes, bytes_read, reason);
}

// Qualification-only loader: one binary open, one full read, hash and parse of
// the same immutable uchar buffer. It is called only under tester+self-gate and
// its false return is an OnInit INIT_FAILED decision owned by LabCore.
bool MGTT_LoadQualifiedRegime(const string fname, const bool common,
                               const string build_receipt,
                               const string config_fingerprint,
                               const string runtime_session="")
{
   g_mgtt_feed_session=(runtime_session!="" ? runtime_session : "UNBOUND");
   g_mgtt_feed_build=build_receipt;
   g_mgtt_feed_config=config_fingerprint;
   mg_rowCount=0; mg_ok=false; mg_fileAgeHours=-1.0;
   mg_fname=fname; mg_common=common;

   string expected_sha="", expected_first="", expected_last="";
   long expected_bytes=-1;
   int expected_rows=-1;
   if(!MGTT_ExpectedFeed(fname, expected_sha, expected_bytes,
                         expected_rows, expected_first, expected_last))
   {
      MGTT_FeedFailure(fname,"UNKNOWN_FILENAME","","",-1,-1,0);
      return false;
   }
   if(common)
   {
      MGTT_FeedFailure(fname,"COMMON_FORBIDDEN",expected_sha,"",
                       expected_bytes,-1,0);
      return false;
   }
   if(!FileIsExist(fname,0))
   {
      MGTT_FeedFailure(fname,"MISSING",expected_sha,"",
                       expected_bytes,-1,0);
      return false;
   }
   long mod=FileGetInteger(fname,FILE_MODIFY_DATE,false);
   if(mod > 0) mg_fileAgeHours=(double)(TimeLocal()-(datetime)mod)/3600.0;
   if(MG_IsStaleAge(mg_fileAgeHours))
   {
      MGTT_FeedFailure(fname,"STALE_REJECTED_BY_EXISTING_LOADER",
                       expected_sha,"",expected_bytes,-1,0);
      return false;
   }

   int h=FileOpen(fname,FILE_READ|FILE_BIN);
   if(h == INVALID_HANDLE)
   {
      MGTT_FeedFailure(fname,"OPEN_FAILED",expected_sha,"",
                       expected_bytes,-1,0);
      return false;
   }
   ulong observed_size=FileSize(h);
   long observed_bytes=-1;
   if(observed_size <= 2147483647)
      observed_bytes=(long)observed_size;
   if(expected_bytes < 0 || observed_size != (ulong)expected_bytes)
   {
      FileClose(h);
      MGTT_FeedFailure(fname,"SIZE_MISMATCH",expected_sha,"",
                       expected_bytes,observed_bytes,0);
      return false;
   }
   uchar raw[];
   if(ArrayResize(raw,(int)expected_bytes) != (int)expected_bytes)
   {
      FileClose(h);
      MGTT_FeedFailure(fname,"READ_INCOMPLETE",expected_sha,"",
                       expected_bytes,observed_bytes,0);
      return false;
   }
   uint read_count=FileReadArray(h,raw,0,(uint)expected_bytes);
   FileClose(h);
   if((long)read_count != expected_bytes)
   {
      MGTT_FeedFailure(fname,"READ_INCOMPLETE",expected_sha,"",
                       expected_bytes,observed_bytes,(long)read_count);
      return false;
   }

   string observed_sha="";
   if(!MGTT_Sha256Hex(raw,observed_sha))
   {
      MGTT_FeedFailure(fname,"HASH_ERROR",expected_sha,"",
                       expected_bytes,observed_bytes,(long)read_count);
      return false;
   }
   if(observed_sha != expected_sha)
   {
      MGTT_FeedFailure(fname,"HASH_MISMATCH",expected_sha,observed_sha,
                       expected_bytes,observed_bytes,(long)read_count);
      return false;
   }

   string text=CharArrayToString(raw,0,WHOLE_ARRAY,CP_UTF8);
   if(StringLen(text)>0 && StringGetCharacter(text,0)==0xFEFF)
      text=StringSubstr(text,1);
   string lines[];
   ushort newline=StringGetCharacter("\n",0);
   int line_count=StringSplit(text,newline,lines);
   int skipped=0;
   datetime prevT=0;
   bool ascending=true;
   for(int i=0; i<line_count && mg_rowCount<MG_MAX_ROWS; i++)
   {
      string line=lines[i];
      int len=StringLen(line);
      if(len>0 && StringGetCharacter(line,len-1)==13)
         line=StringSubstr(line,0,len-1);
      if(i==0) continue; // same unconditional header skip as the legacy loader
      MG_ParseRegimeDataLine(line,skipped,prevT,ascending);
   }
   if(mg_rowCount==0)
   {
      MGTT_FeedFailure(fname,"ZERO_VALID_ROWS",expected_sha,observed_sha,
                       expected_bytes,observed_bytes,(long)read_count);
      return false;
   }
   if(!ascending)
   {
      mg_rowCount=0;
      MGTT_FeedFailure(fname,"UNSORTED",expected_sha,observed_sha,
                       expected_bytes,observed_bytes,(long)read_count);
      return false;
   }

   datetime expected_first_time=StringToTime(expected_first)+(datetime)(mg_offsetHours*3600);
   datetime expected_last_time =StringToTime(expected_last) +(datetime)(mg_offsetHours*3600);
   if(mg_rowCount!=expected_rows || mg_rowTime[0]!=expected_first_time ||
      mg_rowTime[mg_rowCount-1]!=expected_last_time)
   {
      mg_rowCount=0;
      MGTT_FeedFailure(fname,"PARSE_OR_METADATA_MISMATCH",expected_sha,
                       observed_sha,expected_bytes,observed_bytes,
                       (long)read_count);
      return false;
   }

   mg_ok=true;
   PrintFormat("[MGTT_FEED] runtime_session=%s build_receipt=%s effective_config_fingerprint=%s requested_filename=%s source_class=TESTER_SANDBOX_NONCOMMON expected_sha256=%s observed_sha256=%s file_size_bytes=%I64d bytes_read=%I64d valid_row_count=%d skipped_row_count=%d first_accepted_timestamp=%s last_accepted_timestamp=%s load_status=PASS",
                g_mgtt_feed_session,build_receipt,config_fingerprint,fname,expected_sha,observed_sha,
               observed_bytes,(long)read_count,mg_rowCount,skipped,
               TimeToString(mg_rowTime[0],TIME_DATE|TIME_MINUTES),
               TimeToString(mg_rowTime[mg_rowCount-1],TIME_DATE|TIME_MINUTES));
   return true;
}
#endif // LAB_MG_TESTER_EVIDENCE_QUAL

//+------------------------------------------------------------------+
//| Load + validate the regime timeline CSV. Columns:                |
//|   datetime,state,ri[,flags]   header skipped. Rows kept ascending.|
//| datetime parsed by StringToTime ("yyyy.MM.dd HH:mm"), shifted by  |
//| mg_offsetHours to server time. Sets mg_ok.                        |
//+------------------------------------------------------------------+
bool MG_LoadRegime(const string fname, const bool common)
{
   mg_rowCount = 0; mg_ok = false; mg_fileAgeHours = -1.0;
   mg_fname = fname; mg_common = common;   // remember for MG_Tick's per-pass freshness re-check
   int cflag = (common ? FILE_COMMON : 0);
   if(!FileIsExist(fname, cflag))
   {
      PrintFormat("[MACROGATE] regime file '%s' NOT FOUND (%s) - guard INACTIVE",
                  fname, (common ? "Common\\Files" : "MQL5\\Files"));
      return false;
   }
   long mod = FileGetInteger(fname, FILE_MODIFY_DATE, common);
   if(mod > 0) mg_fileAgeHours = (double)(TimeLocal() - (datetime)mod) / 3600.0;
   if(MG_IsStaleAge(mg_fileAgeHours))
   {
      PrintFormat("[MACROGATE] regime file '%s' STALE (%.1f h > %d h) - guard INACTIVE",
                  fname, mg_fileAgeHours, mg_staleMaxHours);
      return false;
   }
   int h = FileOpen(fname, FILE_READ | FILE_TXT | FILE_ANSI | cflag, 0, CP_UTF8);
   if(h == INVALID_HANDLE)
   {
      PrintFormat("[MACROGATE] regime file '%s' open failed (err %d) - guard INACTIVE", fname, GetLastError());
      return false;
   }
   int line = 0, skipped = 0;
   datetime prevT = 0; bool ascending = true;
   while(!FileIsEnding(h) && mg_rowCount < MG_MAX_ROWS)
   {
      string l = FileReadString(h); line++;
      if(line == 1) continue;               // header
      MG_ParseRegimeDataLine(l,skipped,prevT,ascending);
   }
   FileClose(h);
   if(mg_rowCount == 0)
   {
      PrintFormat("[MACROGATE] regime file '%s' parsed ZERO valid rows (%d skipped) - guard INACTIVE", fname, skipped);
      return false;
   }
   if(!ascending)
   {
      // MG_RowAsOf assumes ascending and breaks early; an unsorted file could skip a valid
      // as-of STRESS row and permit orders. Fail SAFE instead of trusting it (Codex QA 2026-07-18).
      Print("[MACROGATE] regime rows NOT strictly ascending - guard INACTIVE (fix the exporter/sort)");
      mg_rowCount = 0; mg_ok = false;
      return false;
   }
   mg_ok = true;
   PrintFormat("[MACROGATE] regime loaded: %d row(s), %d skipped, file age %.1f h, server = CSV %+d h",
               mg_rowCount, skipped, mg_fileAgeHours, mg_offsetHours);
   return true;
}

//+------------------------------------------------------------------+
//| Index of the most recent row with time <= nowServer, else -1.    |
//+------------------------------------------------------------------+
int MG_RowAsOf(const datetime nowServer)
{
   int idx = -1;
   for(int i = 0; i < mg_rowCount; i++)
   {
      if(mg_rowTime[i] <= nowServer) idx = i;
      else break;   // rows ascending
   }
   return idx;
}

bool MG_StateTriggers(const int st)
{
   if(st == MG_ST_STRESS) return true;
   if(st == MG_ST_RISK_OFF && mg_triggerRiskOff) return true;
   return false;
}

void MG_ClearMagic(const int i, const string why)
{
   string bgv = MG_BlockGV(mg_magic[i]);
   string lgv = MG_LotMultGV(mg_magic[i]);
   if(GlobalVariableCheck(bgv)) GlobalVariableDel(bgv);
   if(GlobalVariableCheck(lgv)) GlobalVariableDel(lgv);
   if(mg_gated[i]) PrintFormat("[MACROGATE] gate CLEARED magic=%I64d (%s)", mg_magic[i], why);
   mg_gated[i] = false;
}

void MG_ClearAll(const string why)
{
   for(int i = 0; i < mg_count; i++) MG_ClearMagic(i, why);
}

//+------------------------------------------------------------------+
//| Main watchdog pass. Call from OnTimer with the server clock.     |
//+------------------------------------------------------------------+
void MG_Tick(const datetime nowServer)
{
   // per-pass freshness re-check (LIVE only): a file that goes stale or is deleted BETWEEN
   // reloads must fail safe promptly, not wait for the next reload (Codex QA 2026-07-18).
   // Skipped in the tester, where the CSV is static/fresh and StaleMaxHours is set huge.
   if(mg_ok && !MQLInfoInteger(MQL_TESTER) && StringLen(mg_fname) > 0)
   {
      int cflag2 = (mg_common ? FILE_COMMON : 0);
      if(!FileIsExist(mg_fname, cflag2)) { mg_ok = false; }
      else
      {
         long mod = FileGetInteger(mg_fname, FILE_MODIFY_DATE, mg_common);
         if(mod > 0 && MG_IsStaleAge((double)(TimeLocal() - (datetime)mod) / 3600.0)) mg_ok = false;
      }
   }
   if(!mg_ok)
   {
      MG_ClearAll("fail-safe: regime data unavailable");
      if(TimeLocal() - mg_lastAlert >= MG_ALERT_THROTTLE_SEC)
      {
         mg_lastAlert = TimeLocal();
         MG_AlertCritical("MacroGate INACTIVE: regime file missing/stale - carry legs are UNGATED");
      }
      return;
   }
   int r = MG_RowAsOf(nowServer);
   if(r < 0)
   {
      // now is before the first regime row - nothing known yet, stay inert (no gate)
      MG_ClearAll("no regime row on-or-before now");
      return;
   }
   // newest usable row too old vs now -> treat as a data gap, fail-safe
   double rowAgeH = (double)(nowServer - mg_rowTime[r]) / 3600.0;
   if(mg_rowStaleMaxHours > 0 && rowAgeH > (double)mg_rowStaleMaxHours)
   {
      MG_ClearAll(StringFormat("regime row gap (%.1f h > %d h)", rowAgeH, mg_rowStaleMaxHours));
      if(TimeLocal() - mg_lastAlert >= MG_ALERT_THROTTLE_SEC)
      {
         mg_lastAlert = TimeLocal();
         MG_AlertCritical(StringFormat("MacroGate INACTIVE: regime row gap %.1f h - carry legs UNGATED", rowAgeH));
      }
      return;
   }

   int st = mg_rowState[r];
   if(st == MG_ST_UNKNOWN)
   {
      // Tester-only explicit quarantine marker: clear only MacroGate-owned state.
      // This does not inspect, close, cancel, or modify any position or order.
      MG_ClearAll("explicit UNKNOWN quarantine marker");
      return;
   }
   bool trig = MG_StateTriggers(st);
   for(int i = 0; i < mg_count; i++)
   {
      if(trig)
      {
         if(mg_blockNew) GlobalVariableSet(MG_BlockGV(mg_magic[i]), 1.0);
         else { string bgv = MG_BlockGV(mg_magic[i]); if(GlobalVariableCheck(bgv)) GlobalVariableDel(bgv); }  // lot-only: never leave a stale block (Codex QA 2026-07-18)
         GlobalVariableSet(MG_LotMultGV(mg_magic[i]), mg_lotMult);
         if(!mg_gated[i])
            PrintFormat("[MACROGATE] gate ON magic=%I64d state=%s lotMult=%.2f block=%s @ %s",
                        mg_magic[i], MG_StateName(st), mg_lotMult, (mg_blockNew?"1":"0"),
                        TimeToString(nowServer, TIME_DATE|TIME_MINUTES));
         mg_gated[i] = true;
      }
      else
      {
         MG_ClearMagic(i, "regime not triggering (" + MG_StateName(st) + ")");
      }
   }
}

//+------------------------------------------------------------------+
void MG_Deinit()
{
   MG_ClearAll("deinit reconcile");
}

#endif // BOSS_MACROGATE_CORE_MQH
