"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),http=require("node:http"),path=require("node:path");
let puppeteer; try{puppeteer=require("puppeteer");}catch(error){throw new Error(`Playwright unavailable (MODULE_NOT_FOUND); Puppeteer fallback also unavailable: ${error.message}`);}
const qa=path.resolve(process.argv[2]||"build/sb_reader_qa"),preview=path.join(qa,"preview"),shots=path.join(qa,"screenshots");fs.mkdirSync(shots,{recursive:true});
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml"};
const server=http.createServer((req,res)=>{const u=new URL(req.url,"http://127.0.0.1");if(u.pathname.startsWith("/malformed/")&&u.pathname.endsWith("knowledge_index.json")){res.writeHead(200,{"Content-Type":"application/json"});return res.end("{}");}if(u.pathname.startsWith("/no-monitor/")&&u.pathname.endsWith("report_index.json")){res.writeHead(404);return res.end("missing monitor");}if(u.pathname.startsWith("/forged/")&&u.pathname.endsWith("knowledge_index.json")){const d=JSON.parse(fs.readFileSync(path.join(preview,"knowledge_index.json")));d.documents[0].body="RAW_PRIVATE_COMMENT";res.writeHead(200,{"Content-Type":"application/json"});return res.end(JSON.stringify(d));}const rel=decodeURIComponent(u.pathname.replace(/^\/(malformed|no-monitor|forged)\//,"/").replace(/^\//,""))||"index.html",file=path.resolve(preview,rel);if(!file.startsWith(path.resolve(preview)+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end("missing");}res.writeHead(200,{"Content-Type":mime[path.extname(file)]||"application/octet-stream","Cache-Control":"no-store"});fs.createReadStream(file).pipe(res);});
const edge=()=>[process.env.EDGE_PATH,"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe"].filter(Boolean).find(fs.existsSync);
const fill=async(page,selector,value)=>page.$eval(selector,(node,v)=>{node.value=v;node.dispatchEvent(new Event("input",{bubbles:true}));},value);
const count=async(page,selector)=>(await page.$$(selector)).length;
const content=async(page,selector)=>page.$eval(selector,node=>node.textContent);
async function open(browser,url,viewport,errors){const context=await browser.createBrowserContext();const page=await context.newPage();await page.setViewport(viewport);page._observedRequests=[];page.on("request",r=>page._observedRequests.push(r.url()));page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error"&&!/404|Failed to load resource/i.test(m.text()))errors.push(m.text());});await page.goto(url,{waitUntil:"domcontentloaded"});return{context,page};}
async function main(){await new Promise(r=>server.listen(0,"127.0.0.1",r));const port=server.address().port,browser=await puppeteer.launch({headless:true,executablePath:edge()}),errors=[];try{
  let {context,page}=await open(browser,`http://127.0.0.1:${port}/index.html#knowledge`,{width:390,height:844},errors);await page.waitForSelector(".kr-root",{timeout:5000}).catch(async error=>{throw new Error(`${error.message}; app=${await page.$eval("#app",n=>n.textContent)}; console=${errors.join(" | ")}`);});process.stdout.write("mobile mounted\n");assert.equal(await page.$eval(".kr-packet button",n=>n.disabled),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);assert.match(await content(page,".kr-notice"),/DRAFT_NOT_IMPORTED/);
  await fill(page,"#kr-query","Order Flow");await new Promise(r=>setTimeout(r,100));assert.ok(await count(page,".kr-result")>0);await page.click(".kr-result");assert.ok((await content(page,".kr-document-body")).length>80);
  await fill(page,"#kr-query","Demon Beam");await page.select("#kr-scope","DRAFT");assert.ok(await count(page,".kr-result")>0);await page.click(".kr-result");assert.match(await content(page,".kr-draft-warning"),/ไม่ใช่ canonical/);
  await page.click(".kr-packet summary");await fill(page,"#kr-intake-ea","EA-DEMO");await page.click(".kr-packet button");await new Promise(r=>setTimeout(r,100));assert.match(await content(page,".kr-packet-status"),/copied|downloaded/);
  assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.equal(await page.$$eval(".kr-document-body a,.kr-source",nodes=>nodes.every(n=>/^https?:/.test(n.href))),true);await page.screenshot({path:path.join(shots,"knowledge-mobile-390x844.png"),fullPage:true});await page.click('a[data-nav="home"]');await new Promise(r=>setTimeout(r,100));assert.equal(await page.evaluate(()=>location.hash),"#home");await context.close();
  ({context,page}=await open(browser,`http://127.0.0.1:${port}/index.html#knowledge`,{width:1280,height:900},errors));await page.waitForSelector(".kr-layout");process.stdout.write("desktop mounted\n");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);await page.screenshot({path:path.join(shots,"knowledge-desktop-1280x900.png"),fullPage:true});await context.close();
  ({context,page}=await open(browser,`http://127.0.0.1:${port}/malformed/index.html#knowledge`,{width:390,height:844},errors));await page.waitForSelector(".kr-failure");process.stdout.write("malformed visible\n");assert.match(await content(page,".kr-failure"),/Malformed|pinless/);await context.close();
  ({context,page}=await open(browser,new URL(`file:///${path.join(preview,"READ_SECOND_BRAIN.html").replace(/\\/g,"/")}`).href,{width:390,height:844},errors));const outgoing=[];page.on("request",r=>{if(!r.url().startsWith("file:"))outgoing.push(r.url());});await page.waitForSelector(".kr-root");process.stdout.write("offline mounted\n");await fill(page,"#kr-query","risk");assert.ok(await count(page,".kr-result")>0);assert.deepEqual(page._observedRequests.filter(u=>!u.startsWith("file:")),[]);assert.deepEqual(outgoing,[]);await page.screenshot({path:path.join(shots,"knowledge-offline-file.png"),fullPage:true});await context.close();
  for(const [route,expected] of [["no-monitor",/Monitor canonical pin unavailable/],["forged",/hash mismatch/]]) { ({context,page}=await open(browser,`http://127.0.0.1:${port}/${route}/index.html#knowledge`,{width:390,height:844},errors));await page.waitForSelector(".kr-failure");assert.match(await content(page,".kr-failure"),expected);await context.close();process.stdout.write(route+" refused\n"); }
  assert.deepEqual(errors,[]);const result={status:"PASS",browser_driver:"puppeteer fallback",playwright_reason:"MODULE_NOT_FOUND",served:true,offline_file:true,missing_monitor_pin_refused:true,forged_same_pin_content_refused:true,blank_packet_disabled:true,viewports:["390x844","1280x900"],console_errors:errors,search_open_packet:true,other_nav_hash:"#home",outgoing_offline_requests:[]};fs.writeFileSync(path.join(qa,"BROWSER_QA.json"),JSON.stringify(result,null,2)+"\n");process.stdout.write("BROWSER_QA PASS (Puppeteer fallback; Playwright MODULE_NOT_FOUND)\n");
}finally{await browser.close();server.close();}}
main().catch(e=>{server.close();console.error(e);process.exitCode=1;});
