"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const window={}; vm.runInNewContext(fs.readFileSync('mobile_report_hub/knowledge_reader.js','utf8'),{window,URL,console,navigator:{}},{filename:'knowledge_reader.js'});
const r=window.EALabKnowledgeReader;
const base={id:'RC-1',portable_id:'git::RC-1',title:'EA risk ความเสี่ยง',body:'Order Flow not Seafood',topics:['Risk'],source_ids:['SRC-ONE'],line_refs:[],authority_class:'REGISTERED_RESEARCH',document_type:'RESEARCH_CARD',sha256:'a'.repeat(64),path:'knowledge/card.md'};
assert.equal(r.matches(base,'EA','','ALL'),true);
assert.equal(r.matches({...base,title:'Seafood',body:'Seafood',topics:[],source_ids:[]},'EA','','ALL'),false);
assert.equal(r.matches(base,'ความเสี่ยง','','ALL'),true);
assert.equal(r.matches(base,'ไม่พบ','','ALL'),false);
for(const u of ['javascript:alert(1)','file:///secret','\\\\server\\share','data:text/html,secret'])assert.equal(r.safeHttp(u),null);
assert.match(r.safeHttp('https://example.com/a'),/^https:/);
assert.throws(()=>r.validate({}),/Malformed/);
const data={schema_version:'ea-lab-second-brain-reader/1',authority:'READ_ONLY',canonical:{sha:'b'.repeat(40),ref:'b'.repeat(40)},registry:[],health:{problems:[],canonical_documents:2,draft_documents:0,source_notes:0,research_cards:1,registry_records:0,missing_or_unsafe_link_count:0,registry_binding_problem_count:0},documents:[base,{...base,id:'NEG',portable_id:'git::NEG',title:'EA risk negative',body:'EA risk failed',document_type:'NEGATIVE_KNOWLEDGE',path:'knowledge/90_negative_knowledge/risk.md'}]};
r.validate(data);
assert.throws(()=>r.validate({...data,documents:[]}),/Malformed/);
assert.throws(()=>r.validate({...data,canonical:{...data.canonical,ref:'c'.repeat(40)}}),/Malformed/);
assert.throws(()=>r.validate({...data,health:{...data.health,draft_documents:4}}),/mismatch/);
assert.throws(()=>r.validate({...data,health:{...data.health,source_notes:-1}}),/count/);
assert.throws(()=>r.validate({...data,documents:[{...base,authority_class:'APPROVED_TO_TRADE'},data.documents[1]]}),/Malformed/);
assert.throws(()=>r.validate({...data,documents:[base,base]}),/Duplicate/);
const packet=r.packet(data,'EA risk',data.documents,{});
assert.equal(packet.negative_memory.status,'MATCH');assert.equal(packet.problem_intake.symbol,null);assert.equal(packet.test_verdict,null);
assert.ok(packet.matches.every(x=>Array.isArray(x.line_refs)));
assert.equal(r.packet(data,'Demon Beam',[],{}).negative_memory.status,'NO_MATCH');
assert.ok(r.packet(data,'Demon Beam',[],{}).unresolved_evidence_caveats.some(x=>x.includes('historical')));
process.stdout.write('# 25 focused knowledge-reader assertions passed\n');
