'use strict';
const assert=require('node:assert/strict');
const R=require('./request_contract.cjs');
const {createControl}=require('./control.cjs');
class Audit{constructor(){this.kind='DURABLE_AUDIT_STORE_V1';this.rows=Object.create(null);this.failFinalize=false;}withLock(fn){return fn();}get(k){const v=this.rows[k];return v?JSON.parse(JSON.stringify(v)):null;}prepare(k,h,p){if(this.rows[k])throw new Error('duplicate prepare');this.rows[k]={status:'PREPARED',request_sha256:h,payload:p};}finalize(k,h,r){if(this.failFinalize){this.failFinalize=false;throw new R.Refusal('INJECTED_LOST_ACK');}const x=this.rows[k];if(!x||x.request_sha256!==h)throw new Error('bad finalize');x.status='FINAL';x.receipt=JSON.parse(JSON.stringify(r));}}
function lane(id,state='WAITING',resource='MT5-lane1'){return {lane_id:id,state,head_sha:'a'.repeat(40),writer:true,runtime_lane:resource};}
function fixture(){const lanes=[lane('lane-a'),lane('lane-b','WAITING','MT5-lane2')],calls=[];const bridge={kind:'LANE_REGISTRY_BRIDGE_V1',getLane(id){const x=lanes.find(v=>v.lane_id===id);if(!x)throw new R.Refusal('LANE_MISSING');return JSON.parse(JSON.stringify(x));},listLanes(){return JSON.parse(JSON.stringify(lanes));},transition(x){calls.push({...x});const l=lanes.find(v=>v.lane_id===x.laneId);if(!l||l.state!==x.expectedState||l.head_sha!==x.expectedHead)throw new R.Refusal('REGISTRY_REFUSED');l.state=x.newState;return {result:'TRANSITIONED'};}};const audit=new Audit();let tick=0;const now=()=>`2026-10-06T10:00:${String(tick++).padStart(2,'0')}.000Z`;const api=createControl({bridge,audit,nowUtc:now});let seq=0;function req(operation,laneId='lane-a',resource='MT5-lane1',from='WAITING',to='RUNNING'){seq++;return {schema:'LNWJUD_RESOURCE_REGISTRY_REQUEST_V1',request_id:'req-'+seq,idempotency_key:'key-'+seq,actor:'ChatGPT-MainCT',contract_sha256:'b'.repeat(64),lane_id:laneId,expected_state:from,expected_head:'a'.repeat(40),created_utc:'2026-10-06T09:59:59.000Z',operation,resource_id:resource,target_state:to};}return {lanes,calls,bridge,audit,api,req};}
const cases=[];const add=(n,f)=>cases.push([n,f]);
add('reads exact lane without mutation',f=>{const x=f.api.get_lane_current({lane_id:'lane-a'});assert.equal(x.state,'WAITING');assert.equal(f.calls.length,0);});
add('free resource derived from active writer states only',f=>{assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).state,'FREE');});
add('request lease transitions exact lane to RUNNING and proves ownership',f=>{const r=f.req('request_resource_lease');const out=f.api.request_resource_lease(r);assert.equal(out.outcome,'APPLIED');assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).owner.lane_id,'lane-a');assert.equal(f.calls.length,1);});
add('exact replay returns same final receipt without second transition',f=>{const r=f.req('request_resource_lease');const a=f.api.request_resource_lease(r),n=f.calls.length,b=f.api.request_resource_lease(r);assert.deepEqual(b,a);assert.equal(f.calls.length,n);});
add('release lease transitions RUNNING to WAITING',f=>{f.lanes[0].state='RUNNING';const r=f.req('release_resource_lease','lane-a','MT5-lane1','RUNNING','WAITING');const out=f.api.release_resource_lease(r);assert.equal(out.to_state,'WAITING');assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).state,'FREE');});
add('narrow lane transition can resume resource-bound lane',f=>{const r=f.req('request_lane_transition','lane-a',null,'WAITING','RUNNING');const out=f.api.request_lane_transition(r);assert.equal(out.to_state,'RUNNING');assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).state,'OWNED');});
add('narrow lane transition can park RUNNING lane',f=>{f.lanes[0].state='RUNNING';const r=f.req('request_lane_transition','lane-a',null,'RUNNING','WAITING');f.api.request_lane_transition(r);assert.equal(f.lanes[0].state,'WAITING');});
add('lost final audit acknowledgement reconciles prepared request without second transition',f=>{const r=f.req('request_resource_lease');f.audit.failFinalize=true;assert.throws(()=>f.api.request_resource_lease(r),e=>e.code==='INJECTED_LOST_ACK');assert.equal(f.calls.length,1);const out=f.api.request_resource_lease(r);assert.equal(out.outcome,'RECONCILED_AFTER_LOST_ACK');assert.equal(f.calls.length,1);});
add('read remains available while another resource is owned',f=>{f.lanes[0].state='RUNNING';assert.equal(f.api.get_lane_current({lane_id:'lane-b'}).state,'WAITING');assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).state,'OWNED');});
function run(){let pass=0;const failures=[];for(const [name,test] of cases){const f=fixture();try{test(f);pass++;console.log('PASS '+name);}catch(e){failures.push(name);console.error('FAIL '+name+'\n'+e.stack);}}console.log(JSON.stringify({suite:'LNWJUD_RESOURCE_REGISTRY_V1_POSITIVE',total:cases.length,passed:pass,failed:failures.length,failures,registry_mutations:'FAKE_ONLY',runtime_activated:false}));if(failures.length)process.exitCode=1;}
if(require.main===module)run();module.exports={fixture,Audit};
