'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const R=require('./request_contract.cjs');
const {createLaneRegistryBridge,fileSha}=require('./lane_registry_bridge.cjs');
const {fixture}=require('./test_control.cjs');
function refused(fn,code){assert.throws(fn,e=>e instanceof R.Refusal&&e.code===code,'expected '+code);}
const cases=[];const add=(n,t)=>cases.push([n,t]);
add('unknown request field refuses before transition',f=>{const r=f.req('request_resource_lease');r.command='powershell';refused(()=>f.api.request_resource_lease(r),'MALFORMED_REQUEST');assert.equal(f.calls.length,0);});
add('prototype-bearing request refuses before transition',f=>{const r=f.req('request_resource_lease');Object.setPrototypeOf(r,{polluted:true});refused(()=>f.api.request_resource_lease(r),'MALFORMED_REQUEST');assert.equal(f.calls.length,0);});
add('future request time refuses',f=>{const r=f.req('request_resource_lease');r.created_utc='2027-01-01T00:00:00Z';refused(()=>f.api.request_resource_lease(r),'INVALID_OR_FUTURE_TIME');});
add('stale state refuses',f=>{const r=f.req('request_resource_lease');f.lanes[0].state='READY';refused(()=>f.api.request_resource_lease(r),'STALE_STATE');assert.equal(f.calls.length,0);});
add('stale head refuses',f=>{const r=f.req('request_resource_lease');f.lanes[0].head_sha='c'.repeat(40);refused(()=>f.api.request_resource_lease(r),'STALE_HEAD');assert.equal(f.calls.length,0);});
add('resource binding mismatch refuses',f=>{const r=f.req('request_resource_lease','lane-a','MT5-lane2');refused(()=>f.api.request_resource_lease(r),'RESOURCE_BINDING_MISMATCH');});
add('owned resource refuses competing acquisition',f=>{f.lanes.push({lane_id:'foreign',state:'RUNNING',head_sha:'d'.repeat(40),writer:true,runtime_lane:'MT5-lane1'});const r=f.req('request_resource_lease');refused(()=>f.api.request_resource_lease(r),'RESOURCE_NOT_FREE');});
add('ambiguous resource is reported explicitly',f=>{f.lanes[0].state='RUNNING';f.lanes.push({lane_id:'foreign',state:'REVIEW',head_sha:'d'.repeat(40),writer:true,runtime_lane:'MT5-lane1'});assert.equal(f.api.get_resource_lease({resource_id:'MT5-lane1'}).state,'AMBIGUOUS');});
add('release requires proven current owner',f=>{const r=f.req('release_resource_lease','lane-a','MT5-lane1','RUNNING','WAITING');refused(()=>f.api.release_resource_lease(r),'STALE_STATE');});
add('idempotency drift refuses after successful mutation',f=>{const r=f.req('request_resource_lease');f.api.request_resource_lease(r);const drift={...r,request_id:'different'};refused(()=>f.api.request_resource_lease(drift),'IDEMPOTENCY_DRIFT');assert.equal(f.calls.length,1);});
add('review state cannot be entered through generic transition',f=>{const r=f.req('request_lane_transition','lane-a',null,'WAITING','REVIEW');refused(()=>f.api.request_lane_transition(r),'TRANSITION_NOT_ALLOWED');});
add('integration state cannot be entered through generic transition',f=>{f.lanes[0].state='FROZEN';const r=f.req('request_lane_transition','lane-a',null,'FROZEN','INTEGRATING');refused(()=>f.api.request_lane_transition(r),'TRANSITION_NOT_ALLOWED');});
add('resource field forbidden on generic lane transition',f=>{const r=f.req('request_lane_transition','lane-a','MT5-lane1','WAITING','RUNNING');refused(()=>f.api.request_lane_transition(r),'RESOURCE_FIELD_NOT_ALLOWED');});
add('prepared request with unrelated later state refuses reconciliation',f=>{const r=f.req('request_resource_lease');f.audit.failFinalize=true;refused(()=>f.api.request_resource_lease(r),'INJECTED_LOST_ACK');f.lanes[0].state='BLOCKED';refused(()=>f.api.request_resource_lease(r),'PREPARED_REQUEST_AMBIGUOUS');assert.equal(f.calls.length,1);});
add('opaque idempotency key constructor is data, not prototype behavior',f=>{const r=f.req('request_resource_lease');r.idempotency_key='constructor';assert.equal(f.api.request_resource_lease(r).idempotency_key,'constructor');assert.equal(f.calls.length,1);});
add('bridge fixes PowerShell script and passes structured arguments only',_=>{const repo=path.resolve(__dirname,'..','..','..');const script=path.join(repo,'scripts','lane_registry.ps1');const calls=[];const actuator={kind:'FIXED_POWERSHELL_ACTUATOR_V1',invoke(call){calls.push(call);return {exitCode:0,stdout:JSON.stringify({lane_id:'lane-a',state:'WAITING',head_sha:'a'.repeat(40),writer:true,runtime_lane:'MT5-lane1'}),stderr:''};}};const b=createLaneRegistryBridge({powershellPath:'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',scriptPath:script,scriptSha256:fileSha(script),registryRoot:'D:\\EA_LAB_CONTROL\\lanes\\registry-v1',repoRoot:repo,actuator});const x=b.getLane('lane-a');assert.equal(x.lane_id,'lane-a');assert.equal(calls.length,1);assert.equal(calls[0].filePath,'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe');assert.ok(calls[0].args.includes(script));assert.ok(calls[0].args.includes('lane-a'));assert.equal(calls[0].args.some(v=>String(v).includes(';')),false);});
add('bridge refuses wrong pinned script hash before actuator use',_=>{const repo=path.resolve(__dirname,'..','..','..');const script=path.join(repo,'scripts','lane_registry.ps1');let calls=0;const actuator={kind:'FIXED_POWERSHELL_ACTUATOR_V1',invoke(){calls++;return {exitCode:0,stdout:'{}',stderr:''};}};refused(()=>createLaneRegistryBridge({powershellPath:'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',scriptPath:script,scriptSha256:'0'.repeat(64),registryRoot:'D:\\EA_LAB_CONTROL\\lanes\\registry-v1',repoRoot:repo,actuator}),'REGISTRY_SCRIPT_HASH_MISMATCH');assert.equal(calls,0);});
function run(){let pass=0;const failures=[];for(const [name,test] of cases){const f=fixture();try{test(f);pass++;console.log('PASS '+name);}catch(e){failures.push(name);console.error('FAIL '+name+'\n'+e.stack);}}console.log(JSON.stringify({suite:'LNWJUD_RESOURCE_REGISTRY_V1_NEGATIVE',total:cases.length,passed:pass,failed:failures.length,failures,real_registry_mutations:0,runtime_activated:false}));if(failures.length)process.exitCode=1;}
if(require.main===module)run();
