# -*- coding: utf-8 -*-
"""run_pilot_cells_tests.py -- the cage for gen_pilot_cells.py --check (ORDER-1272).

WHY. `ORDER-1250` registered the sixteen pilot cells and stated the guarantee in writing --
"generated by gen_pilot_cells.py (--check re-derives and diffs; the store is never hand-edited)".
`ORDER-1272` measured that the guarantee was enforced by nobody: one grep returned the generator
itself and no other caller. Putting `--check` on the commit path is only half the repair. The other
half is this file, because a checker whose usual answer is "it matches" is trivially green, and
`--check` PASSED at the moment the order was written -- so "it passes" is not evidence that it
would notice.

EVERY CASE RUNS AGAINST A COPY OF THE REAL STORES, not fixtures. The stores are copied into a temp
root and an `EvidenceSource` is pointed at it, so a mutation is applied to real committed content
and the repository is never touched. Fixtures of filler values cannot test resolution (memory
`fixture-of-filler-values-cannot-test-resolution`); a real row with one character changed can.

🔴 AND EVERY ANCHOR IS DERIVED FROM THE COPY AT RUN TIME, never written as a literal. The first
version pinned `'"dd_pct": 15.72'` and a cell id in source. THE LIVE CONTROL CAUGHT IT: a
one-character edit was made to the real `factory/coverage.jsonl` and a commit attempted, to prove
the hook blocks. The hook did block -- but because THIS SUITE THREW looking for a string the
mutated store no longer contained, not because the drift checker reported drift. A cage whose
fixture is a quotation of the live repository goes red on the very change it exists to describe,
and it reports it as a stack trace. The anchors below are read out of the copied rows.

THE CONTROL IS THE POINT. Case 1 asserts the untouched copy is GREEN, so every later red is
evidence about the mutation rather than about the copy, the temp root or the injected source.

USAGE  tools\\python312\\python.exe _triage/factory_os/run_pilot_cells_tests.py
"""

import io
import json
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)

import evidence                                                              # noqa: E402
import gen_pilot_cells as gen                                                # noqa: E402

PASSED, FAILED = [], []


def check(name, cond, detail=''):
    (PASSED if cond else FAILED).append(name)
    print('[%s] %s%s' % ('PASS' if cond else 'FAIL', name,
                         ('  -- ' + detail) if detail and not cond else ''))


def build_root(tmp):
    """Copy the three inputs --check reads into a temp root, then NORMALISE it. Returns the root.

    🔴 THE NORMALISE STEP IS THE SECOND THING THE LIVE CONTROL TAUGHT. Without it the baseline copy
    is a photograph of the working tree, so when the real store IS drifted -- which is the one
    moment this suite matters -- the CONTROL case ("an untouched copy re-derives") goes red and the
    tier reports the cage as broken instead of reporting the drift. Two different questions were
    riding on one artefact:

        does the CHECKER notice a change?      <- this suite, and it needs a self-consistent start
        is the LIVE store currently correct?   <- `gen_pilot_cells.py --check`, run right after
                                                  this suite by run_s13_tests.ps1

    Running `--apply` against the COPY makes the first question answerable no matter what the
    answer to the second is. It cannot touch the repository: `--apply` writes
    `source().root`, which here is the temp directory.
    """
    for rel in (gen.SOURCE, gen.COVERAGE):
        dst = os.path.join(tmp, rel.replace('/', os.sep))
        if not os.path.isdir(os.path.dirname(dst)):
            os.makedirs(os.path.dirname(dst))
        shutil.copyfile(os.path.join(ROOT, rel.replace('/', os.sep)), dst)
    src_dir = os.path.join(ROOT, gen.PROBE_DIR.replace('/', os.sep))
    dst_dir = os.path.join(tmp, gen.PROBE_DIR.replace('/', os.sep))
    os.makedirs(dst_dir)
    for name in os.listdir(src_dir):
        if name.endswith('.jsonl'):
            shutil.copyfile(os.path.join(src_dir, name), os.path.join(dst_dir, name))
    buf, real = io.StringIO(), sys.stdout
    sys.stdout = buf
    try:
        rc = gen.main(['gen_pilot_cells.py', '--apply'],
                      src=evidence.EvidenceSource('worktree', root=tmp))
    finally:
        sys.stdout = real
        gen._SRC = None
    if rc != 0:
        raise SystemExit('run_pilot_cells_tests: --apply on the copied root exited %s, so the '
                         'baseline these cases mutate is not self-consistent:\n%s' % (rc, buf.getvalue()))
    return tmp


def a_cell(root):
    """-> (cell_id, raw_line, parsed) for the FIRST CoverageCell row in the copied store.

    Derived, never quoted. Which cell it is does not matter to any case here -- what matters is
    that it is a row that actually exists in the snapshot under test, so the mutation lands.
    """
    p = os.path.join(root, gen.COVERAGE.replace('/', os.sep))
    for line in io.open(p, encoding='utf-8').read().splitlines():
        if not line.strip():
            continue
        obj = json.loads(line)
        if obj.get('entity') == 'CoverageCell' and obj.get('metrics'):
            return obj['cell_id'], line, obj
    raise SystemExit('run_pilot_cells_tests: the copied coverage store holds no CoverageCell row '
                     'carrying a metric, so there is nothing for these cases to mutate. That is a '
                     'refusal, not a skip -- silently passing here would report a cage that never '
                     'ran as a cage that found nothing.')


def bump_last_digit(text):
    """'15.72' -> '15.73'. One character, and the case name says one character."""
    return text[:-1] + str((int(text[-1]) + 1) % 10)


def run_check(root):
    """-> (exit_code, printed_text) for `--check` against `root`, in worktree mode."""
    buf, real = io.StringIO(), sys.stdout
    sys.stdout = buf
    try:
        rc = gen.main(['gen_pilot_cells.py', '--check'],
                      src=evidence.EvidenceSource('worktree', root=root))
    except SystemExit as e:
        rc = e.code if isinstance(e.code, int) else 1
    except evidence.ToolFailure as e:
        sys.stdout = real
        return 2, 'ToolFailure: %s' % e
    finally:
        sys.stdout = real
        gen._SRC = None
    return rc, buf.getvalue()


def edit(root, rel, old, new, count=1):
    p = os.path.join(root, rel.replace('/', os.sep))
    text = io.open(p, encoding='utf-8').read()
    if text.count(old) < count:
        raise SystemExit('run_pilot_cells_tests: %r does not appear in %s, so the mutation this '
                         'case depends on cannot be applied. The case would then pass by not '
                         'happening.' % (old, rel))
    io.open(p, 'w', encoding='utf-8', newline='\n').write(text.replace(old, new, count))


def edit_line(root, rel, must_contain, old, new):
    """Mutate `old`->`new` on the ONE line matching every token in `must_contain`.

    A bare string replace is not precise enough for the run store: `"trades":127` appears on two
    lines (two arms of the same cell) and only one of them is the arm the coverage store registers,
    so a first-occurrence replace could mutate a row the generator never reads -- a case that
    passes by not happening. Refusing unless exactly one line matches is what makes the mutation a
    statement about the row it names.
    """
    p = os.path.join(root, rel.replace('/', os.sep))
    lines = io.open(p, encoding='utf-8').read().splitlines()
    hits = [i for i, l in enumerate(lines) if all(t in l for t in must_contain) and old in l]
    if len(hits) != 1:
        raise SystemExit('run_pilot_cells_tests: %d line(s) in %s match %s and contain %r; exactly '
                         'one is required for this mutation to mean what the case says it means.'
                         % (len(hits), rel, must_contain, old))
    lines[hits[0]] = lines[hits[0]].replace(old, new, 1)
    io.open(p, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')


def probe_rec(**over):
    r = {'entity': 'PilotProbeRun', 'cell_id': 'B14-HTEST-r1/EURUSD/H1', 'arm': gen.PROBE_ARM,
         'lane': 'LANE', 'window': 'MAIN', 'from_date': '2023-01-01', 'to_date': '2025-12-31',
         'first_lot': 0.01, 'model': 1, 'xml': 'X.xml', 'launcher_exit_code': 0,
         '_source_file': 'fixture.jsonl'}
    r.update(over)
    return r


def af4_backfill_escape_cases():
    """A-F4 (M1-A, 2026-08-20) -- direct, PURE unit tests of `probed_cells`'s back-fill escape.

    Isolated from the DRIFT-detection machinery the rest of this file drives: no disk, no
    EvidenceSource, no --check. `probed_cells` is called directly with synthetic PilotProbeRun /
    baseline / back-fill inputs, because the defect and its repair live entirely inside that one
    `if` (gen_pilot_cells.py, `probed_cells`) and a synthetic case can put a record exactly on the
    boundary the real committed store cannot reach any more (its four `xml_present: false` records
    all also have `launcher_exit_code: 2`, so the OTHER gate masks the escape there -- see the
    A-F4 docstring on `probed_cells`). This suite drives `launcher_exit_code: 0` deliberately, which
    is the combination the old `is not True` reading would have let through.
    """
    baseline = {'B14-HTEST-r1/EURUSD/H1': {
        'lane': 'LANE', 'window': 'MAIN', 'from_date': '2023-01-01', 'to_date': '2025-12-31',
        'first_lot': 0.01, 'model': 1,
    }}
    cid = 'B14-HTEST-r1/EURUSD/H1'

    # HEALTHY CONTROL: the record PREDATES xml_present entirely (no key at all) and is back-filled
    # -- the one case `load_xml_backfill`'s docstring actually describes. Must still qualify.
    predates = probe_rec()
    predates.pop('xml_present', None)
    qualifying, excluded = gen.probed_cells([predates], baseline, {'X.xml': 5})
    check('A-F4 CONTROL: record PREDATES xml_present (field absent) + back-filled -> still qualifies',
          cid in qualifying, str(excluded))

    # 🔴 ATTACK: the record HAS the field and reports False -- a genuine negative from a launcher
    # capable of measuring it -- yet a back-fill row still names its XML, and launcher_exit_code=0
    # so the exit-code gate cannot mask the escape the way it does for the four historical records.
    # Before A-F4 this qualified; it must not any more.
    explicit_false = probe_rec(xml_present=False)
    qualifying2, excluded2 = gen.probed_cells([explicit_false], baseline, {'X.xml': 5})
    check('A-F4 ATTACK: explicit xml_present=False + exit_code=0 + back-filled XML -> excluded',
          cid not in qualifying2 and any('EXPLICIT negative' in e for e in excluded2),
          str(excluded2))

    # CONTROL: a genuine positive still qualifies (the fix must not touch the True path at all).
    genuine_true = probe_rec(xml_present=True)
    qualifying3, excluded3 = gen.probed_cells([genuine_true], baseline, {'X.xml': 5})
    check('A-F4 CONTROL: genuine xml_present=True + back-filled passes -> qualifies',
          cid in qualifying3, str(excluded3))

    # CONTROL: xml_present=False with NO back-fill row at all was already excluded before A-F4 and
    # must stay excluded -- this case is untouched by the fix, and proves that.
    false_no_backfill = probe_rec(xml_present=False)
    qualifying4, excluded4 = gen.probed_cells([false_no_backfill], baseline, {})
    check('A-F4 CONTROL: xml_present=False with no back-fill entry -> excluded (pre-existing behaviour)',
          cid not in qualifying4, str(excluded4))


def main():
    af4_backfill_escape_cases()
    tmp = tempfile.mkdtemp(prefix='pilotcells_')
    try:
      # 🔴 THE NET, and the live control is why it is here. Anything this suite raises becomes a
      # named FAIL with a roll-up line, never a bare traceback: the tier surfaces an uncaught
      # exception as `exit -1 SUITE THREW` with the cause truncated, which blocks the commit for a
      # reason nobody can read. Reported as a failure of THIS suite, which is what it is.
      try:
        # --- CONTROL: the unmutated copy is green -------------------------------------------
        root = build_root(tmp)
        n_cells = sum(1 for l in io.open(os.path.join(root, gen.COVERAGE.replace('/', os.sep)),
                                         encoding='utf-8').read().splitlines()
                      if l.strip() and json.loads(l).get('entity') == 'CoverageCell')
        rc, out = run_check(root)
        check('CONTROL: an untouched copy of the real stores is GREEN',
              rc == 0 and ('holds exactly the %d' % n_cells) in out,
              'exit=%s %s' % (rc, out[-200:]))
        check('CONTROL: the run prints its evidence-mode marker exactly once',
              out.count('##EVIDENCE-MODE## gen_pilot_cells ') == 1,
              str(out.count('##EVIDENCE-MODE## gen_pilot_cells ')))

        # --- ATTACK 1: one character of one committed cell ------------------------------------
        # This is the acceptance ORDER-1272 names by hand: "ships with a CONTROL proving it goes
        # red on a one-character edit to a committed cell".
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        cid, _line, obj = a_cell(root)
        was = repr(obj['metrics'][0]['dd_pct'])
        now = bump_last_digit(was)
        edit(root, gen.COVERAGE, '"dd_pct": %s' % was, '"dd_pct": %s' % now)
        rc, out = run_check(root)
        # The diff names the CONTAINING field, `metrics`, because dd_pct lives inside a MetricRef
        # list and the comparison is per top-level key. So the assertion is: the right cell is
        # named, and BOTH the committed and the generated value are printed -- which is what a
        # reader needs to see the one character. Drilling into nested keys would read better and
        # is a legibility change, not a detection one; recorded here rather than done in an order
        # about wiring.
        check('ATTACK: one character changed in a committed cell -> DRIFT, naming cell and values',
              rc == 1 and 'DRIFT' in out
              and ('%s.metrics committed=' % cid) in out
              and ("'dd_pct': %s" % now) in out and ("'dd_pct': %s" % was) in out,
              'exit=%s (%s -> %s) %s' % (rc, was, now, out[-300:]))

        # --- ATTACK 2: a whole cell row deleted from the store --------------------------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        cid, _line, _obj = a_cell(root)
        lines = io.open(os.path.join(root, gen.COVERAGE.replace('/', os.sep)),
                        encoding='utf-8').read().splitlines()
        kept = [l for l in lines if ('"cell_id": "%s"' % cid) not in l]
        check('ATTACK 2 precondition: exactly one line was removed',
              len(kept) == len(lines) - 1, '%d -> %d' % (len(lines), len(kept)))
        io.open(os.path.join(root, gen.COVERAGE.replace('/', os.sep)), 'w',
                encoding='utf-8', newline='\n').write('\n'.join(kept) + '\n')
        rc, out = run_check(root)
        check('ATTACK: a deleted cell row -> DRIFT, naming it MISSING',
              rc == 1 and ('MISSING %s' % cid) in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 3: a hand-written row the run evidence does not derive ---------------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        cid, rogue, _obj = a_cell(root)
        p = os.path.join(root, gen.COVERAGE.replace('/', os.sep))
        text = io.open(p, encoding='utf-8').read()
        fake = 'B14-H99-r1/HANDWRITTEN/H4'
        io.open(p, 'w', encoding='utf-8', newline='\n').write(
            text + rogue.replace(cid, fake) + '\n')
        rc, out = run_check(root)
        check('ATTACK: a hand-written cell -> DRIFT, naming it UNDERIVABLE',
              rc == 1 and ('UNDERIVABLE %s' % fake) in out,
              'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 4: the store is untouched and the SOURCE moved ----------------------------
        # The other direction, and it is the one a store-only guard misses: the coverage file is
        # exactly as committed, and the run record it is derived FROM changed underneath it.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        cid, _line, obj = a_cell(root)
        trades = obj['metrics'][0]['trades']
        edit_line(root, gen.SOURCE,
                  ('"cell_id":"%s"' % cid, '"arm":"%s"' % gen.REGISTERED_ARM),
                  '"trades":%d' % trades, '"trades":%d' % (trades + 1))
        rc, out = run_check(root)
        check('ATTACK: the store untouched and its pinned SOURCE moved -> DRIFT',
              rc == 1 and 'DRIFT' in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 5: a probe record removed -> the cell may not claim PROBE_RUN --------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        d = os.path.join(root, gen.PROBE_DIR.replace('/', os.sep))
        removed = [n for n in os.listdir(d) if n.startswith('xml_backfill_')]
        check('ATTACK 5 precondition: there is a back-fill file to remove', bool(removed))
        for n in removed:
            os.remove(os.path.join(d, n))
        rc, out = run_check(root)
        check('ATTACK: the evidence a probe produced anything removed -> DRIFT',
              rc == 1 and 'DRIFT' in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 6: "cannot answer" is exit 2, never exit 1 ---------------------------------
        # A reader that cannot see the store must not tell a committer their store is wrong.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        os.remove(os.path.join(root, gen.COVERAGE.replace('/', os.sep)))
        rc, out = run_check(root)
        check('a store that cannot be READ is exit 2 (cannot answer), not exit 1 (drift)',
              rc == 2, 'exit=%s %s' % (rc, out[-200:]))

        # --- ATTACK 7: --apply refuses to run against a non-worktree source --------------------
        # gen_pilot_cells.main pins --apply to worktree, so this assertion is unreachable from the
        # command line -- which is exactly why it is driven here. An unreachable check is not a
        # check (memory `falsifier-satisfied-by-unexercised-mechanism`), and the caller this
        # protects against is a future suite or hook that imports the module.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        gen.source(evidence.EvidenceSource('index', root=root))
        refused, msg = False, ''
        try:
            gen.write_store([], path=os.path.join(root, gen.COVERAGE.replace('/', os.sep)))
        except SystemExit as e:
            refused, msg = True, str(e)
        except Exception as e:  # noqa: BLE001 -- a crash is reported AS this case, not as a stack
            refused, msg = False, 'CRASHED: %s: %s' % (type(e).__name__, e)
        finally:
            gen._SRC = None
        check('--apply REFUSES to read a snapshot it is not about to overwrite',
              refused and 'builder' in msg, msg[:160])
      except BaseException as exc:  # noqa: BLE001 -- see THE NET above
        check('the cage ran to the end without throwing', False,
              '%s: %s' % (type(exc).__name__, exc))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print('')
    print('[pilot-cells-cage] %d case(s), %d failed' % (len(PASSED) + len(FAILED), len(FAILED)))
    return 1 if FAILED else 0


if __name__ == '__main__':
    sys.exit(main())
