# -*- coding: utf-8 -*-
"""ORDER-1100 (slice S10) -- the cage for Candidate identity, Deployment attestation and magic
reservation.

THE ACCEPTANCE THIS FILE OWNS (design section 10, S10 row, verbatim):
  1. `candidate_digest` is recomputed and compared on every read
  2. no non-OBSERVED attestation event without a human authorization ref
  3. `check_state.ps1` stays green   <- NOT here. It needs the real guard and the real repo, and
                                        it lives in scripts\\_test\\run_s10_tests.ps1, which drives
                                        `check_state.ps1` itself. Said out loud because a suite
                                        that quietly owned three of four criteria would read as
                                        owning all four.
  4. legacy magic exceptions preserved

WHY PARTS 1 AND 2 ARE ENUMERATED AND NOT SAMPLED
  The S9 lesson (`dda6783a` W9, then the 408-cell kill matrix): a check that samples two cases is
  a claim about the rest wearing a pass. So:
    * PART 1 mutates EVERY payload field, one at a time, and demands the digest move for each --
      then REFUSES to pass unless the mutation table covered the whole contract. A field the
      digest does not cover is exactly the hole "recomputed on read" is supposed to close, and
      only an enumeration can find the one that is missing.
    * PART 2 crosses EVERY event type with EVERY actor -- 18 cells, each with a hand-written
      expected verdict -- and refuses to pass unless all 18 were decided. The expectations are
      written from the RULE, not read back from the implementation; a table generated by the code
      under test agrees with it by construction and proves nothing.

WHAT THIS CAGE DOES NOT REACH, said before it is asked
  Everything below drives PURE python. The prompt's own lesson from four /scrutinize rounds over
  S9 is that all nine defects lived where a pure-module cage structurally cannot reach -- the
  PowerShell observation layer, the cage's own arithmetic, and the prose. So: PART 5 puts cheap
  mechanical checks on the halves this suite does not drive (the store on disk, the shape of the
  PowerShell guard, the absence of a renumber path), and the real `check_state.ps1` is driven by
  the wrapper, not by this file.

USAGE  tools\\python312\\python.exe _triage/factory_os/run_s10_tests.py
EXIT   0 = every criterion refused its attack and both enumerations are complete  -  1 = failure
"""

import copy
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import attestation as A                                                    # noqa: E402
import candidate as C                                                      # noqa: E402
import magic as M                                                          # noqa: E402
import scheduler as S                                                      # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
CHECK_STATE_REL = 'scripts/check_state.ps1'

FAILS = []
NAMED = set()


def check(label, ok, detail=''):
    if ok:
        sys.stdout.write('  [OK ] %s\n' % label)
    else:
        FAILS.append(label)
        sys.stdout.write('  [FAIL] %s\n' % label)
        if detail:
            sys.stdout.write('        -> %s\n' % detail)
    return ok


def refuses(label, problems, expect_id):
    """A refusal must be refused FOR THE STATED REASON. `problems` being non-empty is satisfied by
    the shape check on every one of these inputs, so matching on emptiness would let a case pass
    on an unrelated defect and then stop noticing the one it was written for."""
    NAMED.add(expect_id)
    hit = [p for p in problems if p.startswith(expect_id + ' ')]
    return check('%-3s %s' % (expect_id, label), bool(hit),
                 'expected a %s finding, got %s' % (expect_id, problems or 'nothing'))


def accepts(label, problems):
    """THE SPECIFICITY HALF. Every refusal below needs a control that must NOT fire, or the suite
    would pass just as well against a validator that refuses everything
    (memory `gate-specificity-not-just-sensitivity`)."""
    return check('CTL %s' % label, not problems, 'expected no finding, got %s' % problems)


H64 = 'a' * 64
H40 = 'b' * 40

# ------------------------------------------------------------------------------ ORDER-1263
# THESE PINS USED TO BE FILLER, AND THAT IS THE FINDING, NOT AN INCONVENIENCE.
# OWNER was `commit_oid='b'*40, blob_oid='c'*40, raw_sha256='d'*40` and every case in this
# suite passed, because `owner_ref_problems` validated the SHAPE of a pin and never resolved
# it. The S3 and S10 blind audits found that independently on the same day; S10 recorded it as
# unverified claim 2.1 -- "the positive fixture proves a regex exists and nothing else".
#
# So the fixtures now pin REAL objects, resolved from HEAD at import time. A test whose pins
# are fabricated cannot tell a working resolver from an absent one: it is green under both.
# Deriving them from git rather than pasting today's oids also means they do not need
# re-pinning every commit -- a hand-pasted oid here would be stale within the hour and the
# suite would start refusing its own controls.
def _pin(owner_type, path, anchor=None):
    """A REAL OwnerRef at HEAD, resolvable by candidate.owner_ref_resolution_problems.

    HEAD, not the index: under the pre-commit hook HEAD is the previous commit, which is
    exactly what a pin written by the commit being made would legitimately cite.
    """
    def git(*args):
        p = subprocess.run(['git', '-C', ROOT] + list(args), capture_output=True)
        if p.returncode != 0:
            raise RuntimeError('git %s failed: %s' % (' '.join(args), p.stderr.decode('utf-8',
                                                                                      'replace')))
        return p.stdout
    commit = git('rev-parse', 'HEAD').decode('ascii').strip()
    blob = git('rev-parse', 'HEAD:%s' % path).decode('ascii').strip()
    raw = git('cat-file', 'blob', blob)
    return {'entity': 'OwnerRef', 'owner_type': owner_type, 'path': path,
            'commit_oid': commit, 'blob_oid': blob,
            'raw_sha256': hashlib.sha256(raw).hexdigest(), 'anchor': anchor}


def _blob_text(blob_oid):
    p = subprocess.run(['git', '-C', ROOT, 'cat-file', 'blob', blob_oid], capture_output=True)
    return p.stdout.decode('utf-8', 'replace')


def _token_occurring(text, n):
    """A whitespace-free token whose SUBSTRING count in `text` is exactly n, or None.

    Substring count, not token count, because that is what the rule and the checker both mean:
    `ORDER-126` occurs inside `ORDER-1263`, and an anchor is looked for in the bytes, not in a
    tokenisation of them.
    """
    seen = set()
    for tok in text.split():
        if len(tok) < 8 or tok in seen:
            continue
        seen.add(tok)
        if text.count(tok) == n:
            return tok
    return None


OWNER = _pin('scorecard', 'EA_SCORECARD_AND_REGISTRY.md')
AUTH = _pin('taskboard_order', 'AGENT_TASKBOARD.md')
DEPLOY_REF = _pin('deployments_csv', 'portfolio/DEPLOYMENTS.csv')

PAYLOAD = {
    'hypothesis_revision': 'B14-H01-r1',
    'module_set': [{'token': 'LAB_CAP_STACK', 'module_version': '1', 'stability': 'CERTIFIABLE'}],
    'experimental': False,
    'logical_symbol': 'XAUUSD',
    'tf': 'H1',
    'parameters': {'_01_BreakoutBars': 40, '_02_SlAtrMult': 1.5, '_06_AllowLive': True},
    'profiles': {'instrument': '1' * 64, 'exit': '2' * 64, 'sizing': '3' * 64,
                 'safety': '4' * 64, 'execution': '5' * 64},
    'evidence': [{'window': 'MAIN', 'pf': 1.31, 'pf_state': 'DEFINED', 'trades': 84, 'dd_pct': 7.4,
                  'run_id': 'RUN-20260802-001', 'lane': 'lane1',
                  'data_fingerprint': 'df1', 'model': 1},
                 {'window': 'BWD', 'pf': 1.08, 'pf_state': 'DEFINED', 'trades': 52, 'dd_pct': 1.9,
                  'run_id': 'RUN-20260802-002', 'lane': 'lane1',
                  'data_fingerprint': 'df2', 'model': 1}],
    'ex5_sha256': '6' * 64,
    'source_sha256': '7' * 64,
    'allowlist_sha256': '8' * 64,
    'generator_version': 'gen_wrapper-1',
    'effective_config_hash': '9' * 64,
    'universe_version': 'U-1',
    'trial_count': 12,
}


def _journal(run_id, lane='lane1', fingerprint='df1', model=1, terminal='EVIDENCE_REGISTERED'):
    """A folded RunJournal of the shape `scheduler.fold` produces -- built through the real key
    field list so a fifteenth ExecutionKey field would break this fixture rather than be ignored."""
    key = dict((f, 'x') for f in S.EXECUTION_KEY_FIELDS)
    key.update({'lane': lane, 'data_fingerprint': fingerprint, 'model': model})
    return {'entity': 'RunJournal', 'run_id': run_id, 'cell_id': 'cell',
            'execution_key': key,
            'attempts': [{'attempt': 1, 'transition': 'COMPLETED', 'at': '2026-08-02T00:00:00Z'},
                         {'attempt': 1, 'transition': terminal, 'at': '2026-08-02T00:01:00Z'}]}


RUNS = {'RUN-20260802-001': _journal('RUN-20260802-001', fingerprint='df1'),
        'RUN-20260802-002': _journal('RUN-20260802-002', fingerprint='df2')}


def manifest():
    return C.build_manifest(copy.deepcopy(PAYLOAD), copy.deepcopy(OWNER))


# =============================================================================================
# PART 1 -- CANDIDATE IDENTITY. Criterion 1 of the S10 row.
# =============================================================================================
# ONE MUTATION PER PAYLOAD FIELD. The roll-up below refuses to pass unless this table covers the
# contract exactly, which is the only way to notice the field the digest forgot.
MUTATIONS = {
    'hypothesis_revision': 'B14-H01-r2',
    'module_set': [{'token': 'LAB_CAP_GRID', 'module_version': '1', 'stability': 'CERTIFIABLE'}],
    # `experimental` flips to True: a value change, not a type change, so the digest is the only
    # thing that can notice it.
    'experimental': True,
    'logical_symbol': 'EURUSD',
    'tf': 'H4',
    'parameters': {'_01_BreakoutBars': 55, '_02_SlAtrMult': 1.5, '_06_AllowLive': True},
    'profiles': {'instrument': '1' * 64, 'exit': '2' * 64, 'sizing': '3' * 64,
                 'safety': '4' * 64, 'execution': 'e' * 64},
    'evidence': [{'window': 'MAIN', 'pf': 1.32, 'pf_state': 'DEFINED', 'trades': 84, 'dd_pct': 7.4,
                  'run_id': 'RUN-20260802-001', 'lane': 'lane1',
                  'data_fingerprint': 'df1', 'model': 1}],
    'ex5_sha256': 'f' * 64,
    'source_sha256': 'f' * 64,
    'allowlist_sha256': 'f' * 64,
    'generator_version': 'gen_wrapper-2',
    'effective_config_hash': 'f' * 64,
    'universe_version': 'U-2',
    'trial_count': 13,
}


def part1_identity():
    sys.stdout.write('\nPART 1 -- candidate identity: the digest covers the payload, and the '
                     'reader recomputes it\n')
    base = C.candidate_digest(PAYLOAD)

    # -- the enumeration. EVERY field, one at a time.
    moved = 0
    for field in sorted(MUTATIONS):
        mutated = copy.deepcopy(PAYLOAD)
        mutated[field] = copy.deepcopy(MUTATIONS[field])
        if mutated[field] == PAYLOAD[field]:
            check('mutation for %s actually changes the value' % field, False,
                  'the table entry equals the base value, so this cell proved nothing')
            continue
        got = C.candidate_digest(mutated)
        if check('digest moves when %-21s changes' % field, got != base,
                 'the digest did not change, so this field is outside the identity'):
            moved += 1

    # -- ROLL-UP: the table IS the contract. A field added to CandidatePayload and not to this
    #    table would otherwise sail through with every cell above still green.
    check('ROLL-UP the mutation table covers exactly the %d payload fields'
          % len(C.PAYLOAD_FIELDS),
          tuple(sorted(MUTATIONS)) == tuple(sorted(C.PAYLOAD_FIELDS)),
          'table=%s contract=%s' % (sorted(MUTATIONS), sorted(C.PAYLOAD_FIELDS)))
    check('ROLL-UP every one of the %d fields moved the digest' % len(C.PAYLOAD_FIELDS),
          moved == len(C.PAYLOAD_FIELDS), '%d of %d moved' % (moved, len(C.PAYLOAD_FIELDS)))

    # -- C2: the payload may not contain the id. This is the construction rule, and design 4.5
    #    records that rev 1 shipping the impossible version is what led to the check being
    #    disabled.
    for f in C.ID_FIELDS:
        bad = copy.deepcopy(PAYLOAD)
        bad[f] = 'x'
        try:
            C.candidate_digest(bad)
            check('C2  a payload carrying %s is refused' % f, False,
                  'it was hashed anyway -- id = hash(object containing id) has no construction')
        except ValueError as exc:
            NAMED.add('C2')
            check('C2  a payload carrying %s is refused' % f, f in str(exc), str(exc))

    # -- C2 again, from the manifest side: the tamper the reader must catch.
    tampered = manifest()
    tampered['payload']['trial_count'] = 999
    refuses('a manifest whose payload was edited after the digest was taken',
            C.validate_manifest(tampered, run_lookup=RUNS), 'C2')

    # -- C8: the display id is derived. Edited alone, it must be caught by the digest it claims
    #    to be a prefix of.
    m = manifest()
    m['candidate_id'] = 'CAND-' + 'f' * 12
    refuses('a candidate_id that is not the prefix of its own digest',
            C.validate_manifest(m, run_lookup=RUNS), 'C8')

    # -- C4: the promotion-path rule, both halves.
    m = manifest()
    bad = copy.deepcopy(PAYLOAD)
    bad['experimental'] = True
    refuses('an experimental candidate', C.validate_payload(bad), 'C4')
    bad = copy.deepcopy(PAYLOAD)
    bad['module_set'] = [{'token': 'LAB_CAP_STACK', 'module_version': '1',
                          'stability': 'EXPERIMENTAL'}]
    refuses('experimental=false standing on an EXPERIMENTAL module',
            C.validate_payload(bad), 'C4')

    # -- C6: a metric with no lane. ORDER-371 is the whole reason.
    bad = copy.deepcopy(PAYLOAD)
    bad['evidence'][0]['lane'] = ''
    refuses('a metric that records no lane', C.validate_payload(bad), 'C6')

    # -- C1 / C3 / C5 / C7: the shape rules. Cheap, and attacked rather than assumed -- the
    #    roll-up in PART 5 demands that EVERY criterion id this module can emit was fired by
    #    something here, so a rule with no attack would show up there as a hole rather than as
    #    nothing at all.
    m = manifest()
    m['note'] = 'a field nobody declared'
    refuses('a manifest carrying an undeclared field', C.validate_manifest(m), 'C1')
    bad = copy.deepcopy(PAYLOAD)
    bad['module_set'] = [{'token': 'not_a_lab_cap', 'module_version': '1',
                          'stability': 'CERTIFIABLE'}]
    refuses('a module token that is not a LAB_CAP_ capability', C.validate_payload(bad), 'C3')
    bad = copy.deepcopy(PAYLOAD)
    del bad['profiles']['safety']
    refuses('a profiles object missing one of its five content hashes',
            C.validate_payload(bad), 'C5')
    bad = copy.deepcopy(PAYLOAD)
    bad['trial_count'] = -1
    refuses('a negative trial_count', C.validate_payload(bad), 'C7')
    bad = copy.deepcopy(PAYLOAD)
    bad['parameters'] = {}
    refuses('an empty parameter surface (ORDER-165: unlisted inputs come from the tester cache)',
            C.validate_payload(bad), 'C7')

    # -- C9: the pin is checked, not merely stored. Three ways to be wrong, one per fact.
    m = manifest()
    m['payload']['evidence'][0]['run_id'] = 'RUN-20260802-999'
    refuses('a metric citing a run that does not exist',
            C.validate_manifest(m, run_lookup=RUNS), 'C9')
    bad = copy.deepcopy(PAYLOAD)
    bad['evidence'][0]['lane'] = 'lane5c'
    m = C.build_manifest(bad, OWNER)
    refuses('a metric claiming a lane the run did not run on',
            C.validate_manifest(m, run_lookup=RUNS), 'C9')
    bad = copy.deepcopy(PAYLOAD)
    bad['evidence'][0]['model'] = 2
    m = C.build_manifest(bad, OWNER)
    refuses('a Model-2 number quoted as the model the run recorded',
            C.validate_manifest(m, run_lookup=RUNS), 'C9')
    unfinished = dict(RUNS, **{'RUN-20260802-001': _journal('RUN-20260802-001', terminal='FAILED')})
    refuses('a metric read off a run that never registered its evidence',
            C.validate_manifest(manifest(), run_lookup=unfinished), 'C9')
    # 🔴 /scrutinize round 3: the `if f in key` guard turned "I cannot check" into "checked, fine".
    #    Probed by blanking the key on the cited runs: ZERO problems, while the metric still
    #    claimed a lane, a fingerprint and a model that nothing compared.
    blind = copy.deepcopy(RUNS)
    for _rid in blind:
        blind[_rid]['execution_key'] = None
    refuses('a metric citing a run whose journal records NO ExecutionKey (nothing to compare)',
            C.validate_manifest(manifest(), run_lookup=blind), 'C9')
    partial = copy.deepcopy(RUNS)
    for _rid in partial:
        del partial[_rid]['execution_key']['lane']
    refuses('a metric citing a run whose ExecutionKey is silent about the lane',
            C.validate_manifest(manifest(), run_lookup=partial), 'C9')
    # ...and the SKIP is reported rather than passing silently.
    refuses('no run store supplied: the skip is a finding, not a silent pass',
            C.validate_manifest(manifest(), run_lookup=None), 'C9')

    # -- THE CONTROL. Every refusal above needs one, or a validator that refused everything would
    #    pass this entire part.
    accepts('the real manifest validates against the real run store',
            C.validate_manifest(manifest(), run_lookup=RUNS))


def part1b_serializer():
    sys.stdout.write('\nPART 1b -- ONE serializer, and the numeric normalization is carried\n')

    # 🔴 /scrutinize round 2 proved BY PROBE that `10000` and `10000.0` produced two ExecutionKey
    # digests for one deposit. design 4.5 names the identical failure for candidate_digest. The
    # payload nests, so the flat pass that fixed the key is not enough here -- and this is the
    # case that says so.
    a = copy.deepcopy(PAYLOAD)
    a['parameters'] = {'deposit': 10000, '_02_SlAtrMult': 1.5}
    b = copy.deepcopy(PAYLOAD)
    b['parameters'] = {'deposit': 10000.0, '_02_SlAtrMult': 1.5}
    check('the same deposit spelled two ways gives ONE digest, NESTED inside parameters',
          C.candidate_digest(a) == C.candidate_digest(b),
          '%s vs %s' % (C.candidate_digest(a)[:12], C.candidate_digest(b)[:12]))
    a = copy.deepcopy(PAYLOAD)
    a['evidence'][0]['pf'] = 2
    b = copy.deepcopy(PAYLOAD)
    b['evidence'][0]['pf'] = 2.0
    check('the same PF spelled two ways gives ONE digest, nested inside a LIST of objects',
          C.candidate_digest(a) == C.candidate_digest(b))

    # A bool is an int in Python. Normalizing it into one would make `True` and `1` the same
    # parameter, which is a different candidate on a broker where it is a mode switch.
    a = copy.deepcopy(PAYLOAD)
    a['parameters'] = {'AllowLive': True}
    b = copy.deepcopy(PAYLOAD)
    b['parameters'] = {'AllowLive': 1}
    check('True and 1 stay DIFFERENT (bool is a subclass of int, and collapsing them would '
          'silently merge two configurations)', C.candidate_digest(a) != C.candidate_digest(b))

    # THE DEPENDENCY IS MEASURED, not declared. If someone gave this module its own serializer,
    # replacing scheduler's would stop moving the candidate digest -- and that is what is checked.
    real = S.canonical
    try:
        S.canonical = lambda obj: json.dumps(obj, sort_keys=True, separators=(', ', ': '))
        with_swapped = C.candidate_digest(PAYLOAD)
    finally:
        S.canonical = real
    check('candidate_digest really goes THROUGH scheduler.canonical -- swap the serializer and '
          'the digest moves', with_swapped != C.candidate_digest(PAYLOAD),
          'the digest did not move, so this module is not using the shared serializer and the '
          '"one canonical form" claim is a comment')

    # ...and the same probe for the normalization, which is the half the round-2 defect lived in.
    int_pf = copy.deepcopy(PAYLOAD)
    int_pf['evidence'][0]['pf'] = 2
    float_pf = copy.deepcopy(PAYLOAD)
    float_pf['evidence'][0]['pf'] = 2.0
    real_norm = S.normalize_numbers
    try:
        S.normalize_numbers = lambda obj: obj
        split = C.candidate_digest(int_pf) != C.candidate_digest(float_pf)
    finally:
        S.normalize_numbers = real_norm
    check('...and really goes through normalize_numbers -- remove it and 2 vs 2.0 splits again '
          '(the /scrutinize round 2 defect, reproduced on demand)', split,
          'the pair stayed equal with the normalization removed, so this probe proves nothing '
          'about the normalization')

    # The flat form the key uses and the recursive form the payload uses must agree over the key,
    # measured on the real field list rather than argued for in a comment.
    key = dict((f, 'x') for f in S.EXECUTION_KEY_FIELDS)
    key.update({'deposit': 10000.0, 'model': 1, 'leverage': 100})
    flat = dict((f, int(v) if isinstance(v, float) and v.is_integer() else v)
                for f, v in key.items())
    check('the recursive normalization agrees with the flat one over a real ExecutionKey',
          S.canonical(S.normalize_numbers(key)) == S.canonical(flat))


def part1c_reader():
    sys.stdout.write('\nPART 1c -- THE ACCEPTANCE: recomputed and compared ON READ, from disk\n')
    tmp = tempfile.mkdtemp(prefix='s10cand_')
    try:
        m = manifest()
        path = C.write_manifest(m, root=tmp, run_lookup=RUNS)
        got = C.read_manifest(path, run_lookup=RUNS)
        check('a manifest written by build_manifest reads back',
              got['candidate_digest'] == m['candidate_digest'])

        # THE ATTACK. Edit the file the way a person edits a file, and read it again.
        raw = io.open(path, encoding='utf-8-sig').read()
        poisoned = raw.replace('"trial_count":12', '"trial_count":13')
        check('the poison actually changed the bytes', poisoned != raw)
        io.open(path, 'w', encoding='utf-8', newline='\n').write(poisoned)
        try:
            C.read_manifest(path, run_lookup=RUNS)
            check('reading a hand-edited manifest is REFUSED', False,
                  'it read cleanly -- the digest is decoration')
        except C.DigestMismatch as exc:
            check('reading a hand-edited manifest is REFUSED', 'C2' in str(exc), str(exc))

        # /scrutinize round 3: `run_lookup` is REQUIRED. The old default could never succeed, so
        # the signature advertised a normal way to read that always raised.
        import inspect
        sig = inspect.signature(C.read_manifest)
        check('read_manifest requires run_lookup -- no default that can never succeed',
              sig.parameters['run_lookup'].default is inspect.Parameter.empty, str(sig))

        # ...and the write-once rule, which is what stops the refusal above being fixed by
        # overwriting the file.
        io.open(path, 'w', encoding='utf-8', newline='\n').write(raw)
        try:
            C.write_manifest(manifest(), root=tmp, run_lookup=RUNS)
            check('a second write of the same candidate is REFUSED', False, 'it overwrote')
        except C.DigestMismatch as exc:
            check('a second write of the same candidate is REFUSED', 'ONCE' in str(exc), str(exc))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# =============================================================================================
# PART 2 -- ATTESTATION. Criterion 2 of the S10 row, enumerated over (event_type x actor).
# =============================================================================================
def _event(event_type, actor, **kw):
    ev = {'entity': 'DeploymentAttestationEvent', 'event_id': 'ATT-20260802-001',
          'account': '159503454', 'magic': 991001, 'event_type': event_type,
          'at': '2026-08-02T00:00:00Z', 'actor': actor,
          'deployment_ref': DEPLOY_REF}
    ev.update(kw)
    return ev


# HAND-WRITTEN FROM THE RULE, not generated from the code under test. Read design 10's S10 row and
# CONTRACTS.md's x-enforced-by together: "automation may append OBSERVED events only" and "no
# non-OBSERVED event without a human authorization ref".
#   value = the criterion id that must fire, or None when the event must be ACCEPTED
EXPECTED = {}
for _t in A.EVENT_TYPES:
    for _a in A.ACTORS:
        if _t == 'OBSERVED':
            EXPECTED[(_t, _a)] = None
        elif _a == 'automation':
            # BOTH rules bite here. A3 keys on the event type, A4 on the actor, and the cell only
            # proves one of them -- so the pair is asserted separately below.
            EXPECTED[(_t, _a)] = 'A4'
        else:
            EXPECTED[(_t, _a)] = None      # user/claude WITH a ref


def part2_attestation():
    sys.stdout.write('\nPART 2 -- attestation: %d (event_type x actor) cells, each decided\n'
                     % len(EXPECTED))
    decided = 0
    for (etype, actor) in sorted(EXPECTED):
        want = EXPECTED[(etype, actor)]
        kw = {} if etype == 'OBSERVED' else {'authorization_ref': copy.deepcopy(AUTH)}
        ev = _event(etype, actor, **kw)
        problems = A.validate_event(ev, [])
        if want is None:
            ok = accepts('%-20s by %-10s is allowed' % (etype, actor), problems)
        else:
            ok = refuses('%-20s by %-10s' % (etype, actor), problems, want)
        if ok:
            decided += 1
    check('ROLL-UP all %d (event_type x actor) cells were decided as declared' % len(EXPECTED),
          decided == len(EXPECTED), '%d of %d' % (decided, len(EXPECTED)))

    # -- A3 ON ITS OWN. Every non-OBSERVED type, by a HUMAN, with the ref removed. Without this,
    #    the table above proves only A4 (the actor rule) and the headline acceptance -- "no
    #    non-OBSERVED event without a human authorization ref" -- would be untested for the
    #    actors that matter.
    fired = 0
    for etype in A.EVENT_TYPES:
        if etype == 'OBSERVED':
            continue
        for actor in A.HUMAN_ACTORS:
            if refuses('%-20s by %-6s with NO authorization_ref' % (etype, actor),
                       A.validate_event(_event(etype, actor), []), 'A3'):
                fired += 1
    want = (len(A.EVENT_TYPES) - 1) * len(A.HUMAN_ACTORS)
    check('ROLL-UP A3 fired for all %d (non-OBSERVED type x human actor) pairs' % want,
          fired == want, '%d of %d' % (fired, want))

    # -- A3 also refuses a ref that is not a real OwnerRef. A citation that does not resolve is
    #    the same as no citation, and this repo has the receipt (`citation-guard-satisfied-by-a-
    #    universal-file`).
    refuses('an authorization_ref that is not a real OwnerRef',
            A.validate_event(_event('FROZEN', 'user', authorization_ref={'entity': 'OwnerRef'}), []),
            'A3')

    # -- ORDER-1263. The comment above ("a citation that does not resolve is the same as no
    #    citation") was ASPIRATIONAL until 2026-08-03: the case above it is a SHAPE violation,
    #    and a ref with three well-formed hex fields that identify three different documents
    #    walked straight through. Every case below returned [] before that commit -- measured
    #    against `git show HEAD:candidate.py`, not assumed.
    def refuses_pin(label, ref, rule):
        problems = A.validate_event(
            _event('CANDIDATE_ASSIGNED', 'user', candidate_id='CAND-' + '1' * 12,
                   authorization_ref=ref), [])
        hit = [p for p in problems if p.startswith('A3 ') and (' %s ' % rule) in p]
        return check('A3  %-58s [%s]' % (label, rule), bool(hit),
                     'expected an A3 finding naming %s, got %s' % (rule, problems or 'nothing'))

    def accepts_pin(label, ref):
        problems = A.validate_event(
            _event('CANDIDATE_ASSIGNED', 'user', candidate_id='CAND-' + '1' * 12,
                   authorization_ref=ref), [])
        return accepts(label, problems)

    refuses_pin('a well-formed pin at a commit this repo does not have',
                dict(AUTH, commit_oid='b' * 40), 'R1')
    # THE REPRODUCER FROM THE S2 AUDIT'S PART 5, and it is used here in preference to a
    # filler-oid one deliberately: filler invites "nobody would write that". These are real
    # oids of real files that have nothing to do with each other, on the one event type that
    # exists to require a human decision before a candidate reaches a live deployment.
    VISION = _pin('project_state', 'VISION.md')
    PSTATE = _pin('project_state', 'PROJECT_STATE.md')
    refuses_pin('path=VISION.md, blob_oid=PROJECT_STATE.md, sha256 unrelated',
                dict(VISION, blob_oid=PSTATE['blob_oid'], raw_sha256='c' * 64), 'R2')
    refuses_pin('the right blob, a raw_sha256 over something else',
                dict(AUTH, raw_sha256='d' * 64), 'R3')

    # -- R4, the anchor. The schema states the rule in prose ON THE FIELD -- "must occur EXACTLY
    #    once in the blob and contain no spaces" -- and nothing read it. The two anchors below
    #    are DERIVED from the pinned blob rather than hardcoded: a pasted token is stale the
    #    next time that file is edited, and a case whose fixture has rotted is green for the
    #    wrong reason. If the blob cannot supply one, that FAILS here rather than skipping.
    _auth_text = _blob_text(AUTH['blob_oid'])
    once = _token_occurring(_auth_text, 1)
    twice = _token_occurring(_auth_text, 2)
    check('fixture: the pinned blob supplies a once-only and a twice-over token',
          bool(once) and bool(twice),
          'once=%r twice=%r -- cannot construct the R4 cases from this blob' % (once, twice))
    if once and twice:
        refuses_pin('an anchor containing a space', dict(AUTH, anchor='not unique anchor'), 'R4')
        refuses_pin('an anchor that occurs nowhere in the blob',
                    dict(AUTH, anchor='ANCHOR-THAT-IS-NOT-THERE-1263'), 'R4')
        refuses_pin('an anchor that occurs twice -- ambiguous points at no one place',
                    dict(AUTH, anchor=twice), 'R4')
        accepts_pin('an anchor occurring EXACTLY once is accepted', dict(AUTH, anchor=once))
    # THE SPECIFICITY HALF for the whole of R1-R4: a real pin, resolved, must pass. Without it
    # this block reads identically against a resolver that refuses everything.
    accepts_pin('a REAL pin at HEAD resolves and is accepted', copy.deepcopy(AUTH))
    accepts_pin('a real pin with anchor=None is accepted', dict(AUTH, anchor=None))

    # -- A6 THE ONE WITH TEETH. Without it, A3 is an enum check and automation reassigns the
    #    deployment through the field the entity was rewritten to protect.
    prior = [_event('CANDIDATE_ASSIGNED', 'user', event_id='ATT-20260802-001',
                    candidate_id='CAND-' + '1' * 12, authorization_ref=copy.deepcopy(AUTH))]
    refuses('an automation OBSERVED event moving the deployment to another candidate',
            A.validate_event(_event('OBSERVED', 'automation', event_id='ATT-20260802-002',
                                    candidate_id='CAND-' + '2' * 12), prior), 'A6')
    refuses('a claude OBSERVED event doing the same thing (the rule is the EVENT, not the actor)',
            A.validate_event(_event('OBSERVED', 'claude', event_id='ATT-20260802-002',
                                    candidate_id='CAND-' + '2' * 12), prior), 'A6')
    # 🔴 /scrutinize round 2: THE FIRST ASSIGNMENT WAS THE HOLE, AND THE ASYMMETRY RAN THE WRONG
    #    WAY. This case used to exist for `automation` only, so `user` and `claude` could make the
    #    FIRST candidate assignment -- nothing to something -- through an OBSERVED event with NO
    #    authorization_ref, while the same two actors were refused for the strictly smaller act of
    #    moving an existing one. Probed both directions before the fix. Enumerated over every
    #    actor now, because "the rule is on the EVENT, not the actor" is only a claim until every
    #    actor has been asked.
    first_assign = 0
    for actor in A.ACTORS:
        if refuses('a %-10s OBSERVED event naming the FIRST candidate for a pair' % actor,
                   A.validate_event(_event('OBSERVED', actor, event_id='ATT-20260802-002',
                                           candidate_id='CAND-' + '2' * 12), []), 'A6'):
            first_assign += 1
    check('ROLL-UP no actor may first-assign a candidate through an OBSERVED event (%d of %d)'
          % (first_assign, len(A.ACTORS)), first_assign == len(A.ACTORS))
    # ...and the honest shape for the same observation is still accepted: report what was seen
    # WITHOUT deciding what the deployment is.
    accepts('an OBSERVED event that reports attest_state and names no candidate',
            A.validate_event(_event('OBSERVED', 'automation', event_id='ATT-20260802-002',
                                    attest_state='FILE_MISSING'), []))
    accepts('...but an OBSERVED event that REPEATS the current candidate is fine -- that is what '
            'an observation is',
            A.validate_event(_event('OBSERVED', 'automation', event_id='ATT-20260802-002',
                                    candidate_id='CAND-' + '1' * 12,
                                    attest_state='HASHED'), prior))
    accepts('...and an authorized REASSIGNMENT is exactly how the candidate is meant to move',
            A.validate_event(_event('CANDIDATE_REASSIGNED', 'user', event_id='ATT-20260802-002',
                                    candidate_id='CAND-' + '2' * 12,
                                    authorization_ref=copy.deepcopy(AUTH)), prior))

    # -- A1: the shape rule, attacked so the PART 5 roll-up has nothing to report as unfired.
    refuses('an event carrying an undeclared field',
            A.validate_event(_event('OBSERVED', 'automation', note='x'), []), 'A1')
    refuses('an event_id that is not an ATT- id',
            A.validate_event(_event('OBSERVED', 'automation', event_id='whatever'), []), 'A1')

    # -- A2 / A5 / A7: the append-only store's own rules.
    refuses('an event id already in the log',
            A.validate_event(_event('OBSERVED', 'automation'), prior), 'A2')
    refuses('an event timestamped before the line above it',
            A.validate_event(_event('OBSERVED', 'automation', event_id='ATT-20260802-002',
                                    at='2026-08-01T00:00:00Z'), prior), 'A5')
    retired = prior + [_event('RETIRED', 'user', event_id='ATT-20260802-002',
                              at='2026-08-02T01:00:00Z', authorization_ref=copy.deepcopy(AUTH))]
    refuses('any event after the pair was RETIRED',
            A.validate_event(_event('OBSERVED', 'automation', event_id='ATT-20260802-003',
                                    at='2026-08-02T02:00:00Z'), retired), 'A7')

    # -- the log-level replay, and the writer that refuses.
    check('verify_log re-drives a well-formed log clean', not A.verify_log(prior))
    forged = prior + [_event('FROZEN', 'automation', event_id='ATT-20260802-002',
                             at='2026-08-02T01:00:00Z')]
    check('verify_log catches an event that was written straight into the file',
          any('A4' in p or 'A3' in p for p in A.verify_log(forged)), A.verify_log(forged))

    tmp = tempfile.mkdtemp(prefix='s10att_')
    try:
        path = os.path.join(tmp, 'attestations.jsonl')
        A.append_event(path, prior[0])
        try:
            A.append_event(path, _event('FROZEN', 'automation', event_id='ATT-20260802-002',
                                        at='2026-08-02T01:00:00Z'))
            check('append_event REFUSES an unauthorized event on disk', False, 'it was written')
        except A.Refused as exc:
            check('append_event REFUSES an unauthorized event on disk', 'A4' in str(exc), str(exc))
        check('...and the refused event is not in the file',
              len(A.read_log(path)) == 1, A.read_log(path))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# =============================================================================================
# PART 3 -- MAGIC. Criterion 4 of the S10 row.
# =============================================================================================
INV = [{'account': '159503454', 'magic': 990103, 'status': 'REMOVED', 'judge_date': '2026-10-09'},
       {'account': '463666728', 'magic': 990103, 'status': 'ACTIVE', 'judge_date': '2026-10-24'},
       {'account': '159503454', 'magic': 991001, 'status': 'ACTIVE', 'judge_date': '2027-07-09'},
       {'account': '159475669', 'magic': 991001, 'status': 'ACTIVE', 'judge_date': ''},
       {'account': '159503454', 'magic': 992017, 'status': 'ACTIVE', 'judge_date': '2027-01-13'}]


def part3_magic():
    sys.stdout.write('\nPART 3 -- magic: the exception list, both directions, and no renumber\n')
    rows = M.cutover_import(INV, H40)
    accepts('the cutover import of a fixture inventory validates',
            M.store_problems(rows) + M.inventory_problems(INV, rows))
    legacy = sorted(r['magic'] for r in rows if r['scope'] == 'LEGACY_ACCOUNT_SCOPED')
    check('the import declares exactly the colliding magics as exceptions',
          legacy == [990103, 991001], legacy)
    check('...and the frozen accounts are the ones the inventory actually shows',
          [r for r in rows if r['magic'] == 991001][0]['legacy_accounts']
          == ['159475669', '159503454'])

    # -- M4 SENSITIVITY: a new collision that nobody declared.
    grown = INV + [{'account': '999999999', 'magic': 992017, 'status': 'ACTIVE', 'judge_date': ''}]
    refuses('a NEW collision that is not a declared exception',
            M.inventory_problems(grown, rows), 'M4')
    moved = [dict(r, legacy_accounts=['159475669', '111111111'])
             if r['magic'] == 991001 else r for r in rows]
    refuses('a frozen exception whose accounts moved',
            M.inventory_problems(INV, moved), 'M4')

    # -- M5 SPECIFICITY: the direction that stops the list becoming an off switch.
    over = rows + [{'entity': 'MagicAllocation', 'magic': 992017,
                    'scope': 'LEGACY_ACCOUNT_SCOPED', 'legacy_exception': True,
                    'legacy_accounts': ['159503454', '159475669'], 'imported_in_cutover': True,
                    'status': 'ASSIGNED', 'allocated_at_commit': H40}]
    refuses('a magic declared an exception that is not on two accounts',
            M.inventory_problems(INV, over), 'M5')

    # -- M6 the closed set. Two ways in, both refused.
    mint = {'entity': 'MagicAllocation', 'magic': 993000, 'scope': 'LEGACY_ACCOUNT_SCOPED',
            'legacy_exception': True, 'legacy_accounts': ['a', 'b'],
            'imported_in_cutover': False, 'status': 'RESERVED', 'allocated_at_commit': H40}
    refuses('a legacy row minted with imported_in_cutover=false',
            M.validate_allocation(mint), 'M6')
    late = dict(mint, imported_in_cutover=True, allocated_at_commit='c' * 40)
    refuses('a legacy row imported at a SECOND cutover commit',
            M.store_problems(rows + [late]), 'M6')

    # -- M3 / M2 shape rules.
    refuses('two allocations of one magic',
            M.store_problems(rows + [dict(rows[0])]), 'M3')
    refuses('a GLOBAL row flying the legacy flag',
            M.validate_allocation({'entity': 'MagicAllocation', 'magic': 1, 'scope': 'GLOBAL',
                                   'legacy_exception': True, 'status': 'RESERVED',
                                   'allocated_at_commit': H40}), 'M2')
    refuses('an allocation whose allocated_at_commit is not an oid',
            M.validate_allocation({'entity': 'MagicAllocation', 'magic': 1, 'scope': 'GLOBAL',
                                   'status': 'RESERVED', 'allocated_at_commit': 'HEAD'}), 'M1')

    # -- the allocator. RETIRED is the one that reads as free and is not.
    nxt = M.allocate(rows, INV, H40)
    check('the allocator picks a number above everything already spent',
          nxt['magic'] == max([r['magic'] for r in rows] + [r['magic'] for r in INV]) + 1,
          nxt)
    check('...and it is GLOBAL, never legacy', nxt['scope'] == 'GLOBAL')
    retired = rows + [{'entity': 'MagicAllocation', 'magic': 993001, 'scope': 'GLOBAL',
                       'legacy_exception': False, 'status': 'RETIRED',
                       'allocated_at_commit': H40}]
    for magic, why in ((993001, 'a RETIRED magic'), (991001, 'a magic already allocated'),
                       (992017, 'a magic already on an account in the inventory')):
        try:
            M.allocate(retired, INV, H40, magic=magic)
            check('the allocator refuses %s' % why, False, 'it handed out %d' % magic)
        except M.Refused as exc:
            check('the allocator refuses %s' % why, True)
            if magic == 993001:
                check('...and says WHY a retired one is not free', 'never re-issued' in str(exc),
                      str(exc))

    # -- the prohibition, enforced by the ABSENCE of code rather than by a rule people remember.
    src = io.open(os.path.join(HERE, 'magic.py'), encoding='utf-8').read()
    check('magic.py contains no renumber/rename path (design 10: no renumbering of a live magic)',
          not re.search(r'def\s+\w*(renumber|rename|reassign_magic)\w*', src))
    check('magic.py never opens the store for writing -- append only',
          not re.search(r"io\.open\([^)]*['\"]w['\"]", src),
          'a truncating open of an append-only store is a rewrite path')
    try:
        M.append_allocation(os.path.join(tempfile.gettempdir(), 'nope.jsonl'), mint, INV)
        check('append_allocation refuses a legacy row outright', False, 'it appended one')
    except M.Refused as exc:
        check('append_allocation refuses a legacy row outright', 'M6' in str(exc), str(exc))


# =============================================================================================
# PART 4 -- THE REAL STORE AND THE REAL INVENTORY. The fixtures above prove the rules; this
# proves they hold against the file the live-money guard will read.
# =============================================================================================
def part4_real():
    sys.stdout.write('\nPART 4 -- the real repo: the exception list against the real inventory\n')
    store = M.store_path(ROOT)
    if not os.path.exists(store):
        check('factory/magic_allocations.jsonl exists', False,
              'check_state.ps1 cannot flip to the global rule without it')
        return
    rows = M.read_store(store)
    inventory = M.read_inventory(M.inventory_path(ROOT))
    problems = M.store_problems(rows) + M.inventory_problems(inventory, rows)
    accepts('the committed store validates against the committed inventory', problems)
    legacy = sorted(S.normalize_numbers(r['magic']) for r in rows
                    if r['scope'] == 'LEGACY_ACCOUNT_SCOPED')
    # THE THREE, BY NAME. design 4.6 and PROJECT_STATE section 0.5 both enumerate them, and this
    # is the assertion that notices if a fourth quietly joins or one is dropped.
    check('the legacy exceptions are exactly the three the owner declared: 990103, 991001, 991002',
          legacy == [990103, 991001, 991002], legacy)
    live = [r for r in rows if S.normalize_numbers(r['magic']) == 991001][0]
    check('991001 -- the one on REAL money -- is frozen to both its accounts',
          sorted(live['legacy_accounts']) == ['159475669', '159503454'], live)
    sys.stdout.write('       (%d allocation(s), %d legacy, %d inventory row(s) carrying a magic)\n'
                     % (len(rows), len(legacy), len(inventory)))

    # 🔴 /scrutinize round 4: `gen_magic_allocations.py` WAS A DECLARED TRIGGER THAT NOTHING RAN.
    # It is listed in run_fast_cages.ps1's $SUITE_GUARDS for this suite, so editing it fires the
    # suite -- and the suite had no question to ask about it. Memory
    # `declared-as-trigger-but-never-read`, in the same slice that quotes the memory it came from.
    # The consequence is not cosmetic: `magic.py verify` checks COLLISIONS, and only `--check`
    # checks COMPLETENESS -- that every magic in the inventory has a row, and that no row was
    # hand-edited into something that still validates (a `status` flipped, an
    # `allocated_at_commit` retyped). That half had zero enforcement.
    gen = os.path.join(HERE, 'gen_magic_allocations.py')
    out = subprocess.run([sys.executable, gen, '--check', '--root=' + ROOT],
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    check('gen_magic_allocations.py --check regenerates the committed store byte-identically',
          out.returncode == 0, out.stdout.decode('utf-8', 'replace')[-300:])

    # ...and it must be able to FAIL, or the line above is a check that cannot fire. Drive it
    # against a copy of the store with one row removed: the inventory still has that magic, so the
    # regeneration no longer matches.
    tmp = tempfile.mkdtemp(prefix='s10gen_')
    try:
        kept = [r for r in rows if S.normalize_numbers(r['magic']) != 992017]
        check('the RED fixture actually removed a row', len(kept) == len(rows) - 1,
              '%d vs %d' % (len(kept), len(rows)))
        store = os.path.join(tmp, 'magic_allocations.jsonl')
        with io.open(store, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(''.join(S.canonical(r) + '\n' for r in kept))
        out = subprocess.run([sys.executable, gen, '--check', '--root=' + ROOT,
                              '--store=' + store],
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        text = out.stdout.decode('utf-8', 'replace')
        check('RED  --check REFUSES a store that has fallen behind the inventory',
              out.returncode == 1 and 'DRIFT' in text, text[-300:])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# =============================================================================================
# PART 5 -- THE HALF THIS CAGE DOES NOT DRIVE.
#
# The prompt's own lesson from four /scrutinize rounds over S9: every one of the nine defects
# lived where the pure-module matrix structurally cannot reach. So each acceptance gets a cheap
# mechanical check on the half the enumeration misses.
# =============================================================================================
def part5_the_other_half():
    sys.stdout.write('\nPART 5 -- the halves the enumeration cannot reach\n')
    path = os.path.join(ROOT, CHECK_STATE_REL.replace('/', os.sep))
    src = io.open(path, encoding='utf-8', errors='replace').read()

    lib = io.open(os.path.join(ROOT, 'scripts', 'lib', 'magic_guard.ps1'),
                  encoding='utf-8', errors='replace').read()

    # (a) ONE IMPLEMENTATION. The rule is ASKED of magic.py, never restated in PowerShell -- two
    #     implementations of one rule is two opinions, and the second one is always the one
    #     nobody drives.
    check('the PowerShell guard asks magic.py rather than reimplementing the rule',
          'magic.py' in lib, 'if it grew its own copy, this suite proves the wrong one')
    check('...and check_state.ps1 calls it through the shared library',
          'Test-MagicUniqueness' in src and 'magic_guard.ps1' in src)

    # (b) THE EVIDENCE DISCIPLINE (ORDER-674's A7). check_state reads judged bytes; a child
    #     process reading the WORKING TREE would reintroduce exactly the hole that order closed --
    #     a poisoned inventory staged behind a clean worktree copy, with the gate green. The
    #     library therefore takes TEXT and the caller does the reading.
    check('...and the exception list goes through the SAME judged reader as the inventory',
          re.search(r'ReadJudged\s+\$ALLOC', src) is not None)
    check('...and the library takes bytes and does NO repo reading of its own',
          '$AllocText' in lib and 'Read-Committed' not in lib and 'Get-Content' not in lib,
          'any read inside the library is a second vintage: the caller judged the bytes, and a '
          'guard that re-reads the disk is ORDER-674 A7 rebuilt one file along')

    # (c) A MISSING INPUT IS A FAILURE, NOT A PASS. memory `guard-disarmed-by-prose-reported-as-
    #     note`: "cannot read it" must never look like "there is nothing to enforce".
    check('...and a missing exception list is reported as a failure, not skipped',
          'cannot read the magic exception list' in lib)

    # (d) the wrapper that drives the REAL guard exists and is registered, because parts (a)-(c)
    #     are shape checks and shape checks do not fire guards.
    wrapper = os.path.join(ROOT, 'scripts', '_test', 'run_s10_tests.ps1')
    check('the wrapper that drives the real check_state.ps1 exists', os.path.exists(wrapper))
    tier = io.open(os.path.join(ROOT, 'scripts', '_test', 'run_fast_cages.ps1'),
                   encoding='utf-8', errors='replace').read()
    m = re.search(r'\$FAST_SUITES\s*=\s*@\((.*?)\n\)', tier, re.S)
    check('...and it is inside $FAST_SUITES, which is the array that actually runs',
          bool(m) and 'run_s10_tests.ps1' in m.group(1))

    # (d2) 🔴 /scrutinize round 2, generalised: NO DERIVED FLAG THE FOLD EXPOSES MAY GO UNREAD.
    #      `fold` carried a `frozen` flag that `validate_event` never mentioned, so a FROZEN event
    #      changed nothing -- a read-model describing enforcement nobody performs, which the next
    #      caller reads as a rule. The flag is gone; this check is what catches the next one,
    #      because the shape recurs and inspection does not scale.
    att_src = io.open(os.path.join(HERE, 'attestation.py'), encoding='utf-8').read()
    body = att_src.split('def validate_event')[1].split('\ndef ')[0]
    sample = A.fold([_event('RETIRED', 'user', authorization_ref=copy.deepcopy(AUTH))])
    flags = sorted(k for k, v in list(sample.values())[0].items() if isinstance(v, bool))
    check('every boolean the fold exposes is declared in DERIVED_FLAGS',
          flags == sorted(A.DERIVED_FLAGS), 'fold=%s declared=%s' % (flags, sorted(A.DERIVED_FLAGS)))
    unread = [f for f in A.DERIVED_FLAGS if ("'%s'" % f) not in body]
    check('...and every declared flag is actually READ by validate_event', not unread,
          '%s is computed and no rule consumes it -- a flag nobody reads reads as a rule' % unread)

    # (e) the vocabulary of all three modules is the schema's, re-read from the file.
    for name, mod in (('candidate', C), ('attestation', A), ('magic', M)):
        problems = mod.assert_vocabulary_matches_schema(ROOT)
        check('%s\'s vocabulary IS schemas.json\'s, re-read from the file' % name, not problems,
              problems)

    # (f) THE CAGE CAN FAIL. Every criterion id this suite names must correspond to a real
    #     refusal in the module -- and the roll-up below is what stops a criterion being deleted
    #     from a module and quietly disappearing from the report.
    expected = set()
    for mod, prefix, n in ((C, 'C', 9), (A, 'A', 7), (M, 'M', 6)):
        for i in range(1, n + 1):
            expected.add('%s%d' % (prefix, i))
    unnamed = sorted(expected - NAMED)
    invented = sorted(NAMED - expected)
    sys.stdout.write('       attacked: %s\n' % ' '.join(sorted(NAMED)))
    # 🔴 THE CLAIM AND ITS MEASUREMENT ARE THE SAME SENTENCE (the S9 round-1 lesson: the roll-up
    # recorded points REACHED and printed points KILLED). The line above is the set this line
    # compares; nothing is restated from memory.
    check('ROLL-UP every one of the %d criterion ids the three modules declare was ATTACKED by a '
          'case above' % len(expected), not unnamed,
          'never attacked: %s -- a criterion with no attack is a rule with a comment' % unnamed)
    check('ROLL-UP ...and this suite names no criterion the modules do not have', not invented,
          'named but not declared anywhere: %s' % invented)


def main():
    part1_identity()
    part1b_serializer()
    part1c_reader()
    part2_attestation()
    part3_magic()
    part4_real()
    part5_the_other_half()
    sys.stdout.write('\n')
    if FAILS:
        sys.stdout.write('=== %d FAILURE(S) ===\n' % len(FAILS))
        for f in FAILS:
            sys.stdout.write('  %s\n' % f)
        return 1
    sys.stdout.write('=== every criterion refused its attack: %d payload fields each moved the '
                     'digest, all %d (event_type x actor) cells decided, and the three legacy '
                     'magic exceptions are the owner\'s three ===\n'
                     % (len(C.PAYLOAD_FIELDS), len(EXPECTED)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
