# -*- coding: utf-8 -*-
"""run_pilot_cells_tests.py -- the cage for gen_pilot_cells.py --check (ORDER-1272).

WHY. `ORDER-1250` registered the sixteen pilot cells and stated the guarantee in writing --
"generated by gen_pilot_cells.py (--check re-derives and diffs; the store is never hand-edited)".
`ORDER-1272` measured that the guarantee was enforced by nobody: one grep returned the generator
itself and no other caller. Putting `--check` on the commit path is only half the repair. The other
half is this file, because a checker whose usual answer is "it matches" is trivially green, and
`--check` PASSED at the moment the order was written -- so "it passes" is not evidence that it
would notice.

EVERY CASE RUNS AGAINST A COPY OF THE REAL STORES, not fixtures. The stores are copied into a temp
root and an `EvidenceSource` is pointed at it, so a mutation is applied to real committed content
and the repository is never touched. Fixtures of filler values cannot test resolution (memory
`fixture-of-filler-values-cannot-test-resolution`); a real row with one character changed can.

THE CONTROL IS THE POINT. Case 1 asserts the untouched copy is GREEN, so every later red is
evidence about the mutation rather than about the copy, the temp root or the injected source.

USAGE  tools\\python312\\python.exe _triage/factory_os/run_pilot_cells_tests.py
"""

import io
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)

import evidence                                                              # noqa: E402
import gen_pilot_cells as gen                                                # noqa: E402

PASSED, FAILED = [], []


def check(name, cond, detail=''):
    (PASSED if cond else FAILED).append(name)
    print('[%s] %s%s' % ('PASS' if cond else 'FAIL', name,
                         ('  -- ' + detail) if detail and not cond else ''))


def build_root(tmp):
    """Copy the three inputs --check reads into a temp root. Returns the root."""
    for rel in (gen.SOURCE, gen.COVERAGE):
        dst = os.path.join(tmp, rel.replace('/', os.sep))
        if not os.path.isdir(os.path.dirname(dst)):
            os.makedirs(os.path.dirname(dst))
        shutil.copyfile(os.path.join(ROOT, rel.replace('/', os.sep)), dst)
    src_dir = os.path.join(ROOT, gen.PROBE_DIR.replace('/', os.sep))
    dst_dir = os.path.join(tmp, gen.PROBE_DIR.replace('/', os.sep))
    os.makedirs(dst_dir)
    for name in os.listdir(src_dir):
        if name.endswith('.jsonl'):
            shutil.copyfile(os.path.join(src_dir, name), os.path.join(dst_dir, name))
    return tmp


def run_check(root):
    """-> (exit_code, printed_text) for `--check` against `root`, in worktree mode."""
    buf, real = io.StringIO(), sys.stdout
    sys.stdout = buf
    try:
        rc = gen.main(['gen_pilot_cells.py', '--check'],
                      src=evidence.EvidenceSource('worktree', root=root))
    except SystemExit as e:
        rc = e.code if isinstance(e.code, int) else 1
    except evidence.ToolFailure as e:
        sys.stdout = real
        return 2, 'ToolFailure: %s' % e
    finally:
        sys.stdout = real
        gen._SRC = None
    return rc, buf.getvalue()


def edit(root, rel, old, new, count=1):
    p = os.path.join(root, rel.replace('/', os.sep))
    text = io.open(p, encoding='utf-8').read()
    if text.count(old) < count:
        raise SystemExit('run_pilot_cells_tests: %r does not appear in %s, so the mutation this '
                         'case depends on cannot be applied. The case would then pass by not '
                         'happening.' % (old, rel))
    io.open(p, 'w', encoding='utf-8', newline='\n').write(text.replace(old, new, count))


def edit_line(root, rel, must_contain, old, new):
    """Mutate `old`->`new` on the ONE line matching every token in `must_contain`.

    A bare string replace is not precise enough for the run store: `"trades":127` appears on two
    lines (two arms of the same cell) and only one of them is the arm the coverage store registers,
    so a first-occurrence replace could mutate a row the generator never reads -- a case that
    passes by not happening. Refusing unless exactly one line matches is what makes the mutation a
    statement about the row it names.
    """
    p = os.path.join(root, rel.replace('/', os.sep))
    lines = io.open(p, encoding='utf-8').read().splitlines()
    hits = [i for i, l in enumerate(lines) if all(t in l for t in must_contain) and old in l]
    if len(hits) != 1:
        raise SystemExit('run_pilot_cells_tests: %d line(s) in %s match %s and contain %r; exactly '
                         'one is required for this mutation to mean what the case says it means.'
                         % (len(hits), rel, must_contain, old))
    lines[hits[0]] = lines[hits[0]].replace(old, new, 1)
    io.open(p, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')


def main():
    tmp = tempfile.mkdtemp(prefix='pilotcells_')
    try:
        # --- CONTROL: the unmutated copy is green -------------------------------------------
        root = build_root(tmp)
        rc, out = run_check(root)
        check('CONTROL: an untouched copy of the real stores is GREEN',
              rc == 0 and 'holds exactly the 16' in out, 'exit=%s %s' % (rc, out[-200:]))
        check('CONTROL: the run prints its evidence-mode marker exactly once',
              out.count('##EVIDENCE-MODE## gen_pilot_cells ') == 1,
              str(out.count('##EVIDENCE-MODE## gen_pilot_cells ')))

        # --- ATTACK 1: one character of one committed cell ------------------------------------
        # This is the acceptance ORDER-1272 names by hand: "ships with a CONTROL proving it goes
        # red on a one-character edit to a committed cell".
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        edit(root, gen.COVERAGE, '"dd_pct": 15.72', '"dd_pct": 15.73')
        rc, out = run_check(root)
        # The diff names the CONTAINING field, `metrics`, because dd_pct lives inside a MetricRef
        # list and the comparison is per top-level key. So the assertion is: the right cell is
        # named, and BOTH the committed and the generated value are printed -- which is what a
        # reader needs to see the one character. Drilling into nested keys would read better and
        # is a legibility change, not a detection one; recorded here rather than done in an order
        # about wiring.
        check('ATTACK: one character changed in a committed cell -> DRIFT, naming cell and values',
              rc == 1 and 'DRIFT' in out
              and 'B14-H01-r1/BTCUSD/H1.metrics committed=' in out
              and "'dd_pct': 15.73" in out and "'dd_pct': 15.72" in out,
              'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 2: a whole cell row deleted from the store --------------------------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        lines = io.open(os.path.join(root, gen.COVERAGE.replace('/', os.sep)),
                        encoding='utf-8').read().splitlines()
        kept = [l for l in lines if 'B14-H01-r1/BTCUSD/H4' not in l]
        check('ATTACK 2 precondition: exactly one line was removed',
              len(kept) == len(lines) - 1, '%d -> %d' % (len(lines), len(kept)))
        io.open(os.path.join(root, gen.COVERAGE.replace('/', os.sep)), 'w',
                encoding='utf-8', newline='\n').write('\n'.join(kept) + '\n')
        rc, out = run_check(root)
        check('ATTACK: a deleted cell row -> DRIFT, naming it MISSING',
              rc == 1 and 'MISSING B14-H01-r1/BTCUSD/H4' in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 3: a hand-written row the run evidence does not derive ---------------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        p = os.path.join(root, gen.COVERAGE.replace('/', os.sep))
        text = io.open(p, encoding='utf-8').read()
        rogue = [l for l in text.splitlines() if 'B14-H01-r1/BTCUSD/H4' in l][0]
        io.open(p, 'w', encoding='utf-8', newline='\n').write(
            text + rogue.replace('B14-H01-r1/BTCUSD/H4', 'B14-H99-r1/HANDWRITTEN/H4') + '\n')
        rc, out = run_check(root)
        check('ATTACK: a hand-written cell -> DRIFT, naming it UNDERIVABLE',
              rc == 1 and 'UNDERIVABLE B14-H99-r1/HANDWRITTEN/H4' in out,
              'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 4: the store is untouched and the SOURCE moved ----------------------------
        # The other direction, and it is the one a store-only guard misses: the coverage file is
        # exactly as committed, and the run record it is derived FROM changed underneath it.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        edit_line(root, gen.SOURCE,
                  ('"cell_id":"B14-H01-r1/BTCUSD/H1"', '"arm":"baseline"'),
                  '"trades":127', '"trades":128')
        rc, out = run_check(root)
        check('ATTACK: the store untouched and its pinned SOURCE moved -> DRIFT',
              rc == 1 and 'DRIFT' in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 5: a probe record removed -> the cell may not claim PROBE_RUN --------------
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        d = os.path.join(root, gen.PROBE_DIR.replace('/', os.sep))
        removed = [n for n in os.listdir(d) if n.startswith('xml_backfill_')]
        check('ATTACK 5 precondition: there is a back-fill file to remove', bool(removed))
        for n in removed:
            os.remove(os.path.join(d, n))
        rc, out = run_check(root)
        check('ATTACK: the evidence a probe produced anything removed -> DRIFT',
              rc == 1 and 'DRIFT' in out, 'exit=%s %s' % (rc, out[-300:]))

        # --- ATTACK 6: "cannot answer" is exit 2, never exit 1 ---------------------------------
        # A reader that cannot see the store must not tell a committer their store is wrong.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        os.remove(os.path.join(root, gen.COVERAGE.replace('/', os.sep)))
        rc, out = run_check(root)
        check('a store that cannot be READ is exit 2 (cannot answer), not exit 1 (drift)',
              rc == 2, 'exit=%s %s' % (rc, out[-200:]))

        # --- ATTACK 7: --apply refuses to run against a non-worktree source --------------------
        # gen_pilot_cells.main pins --apply to worktree, so this assertion is unreachable from the
        # command line -- which is exactly why it is driven here. An unreachable check is not a
        # check (memory `falsifier-satisfied-by-unexercised-mechanism`), and the caller this
        # protects against is a future suite or hook that imports the module.
        shutil.rmtree(tmp); tmp = tempfile.mkdtemp(prefix='pilotcells_')
        root = build_root(tmp)
        gen.source(evidence.EvidenceSource('index', root=root))
        refused, msg = False, ''
        try:
            gen.write_store([], path=os.path.join(root, gen.COVERAGE.replace('/', os.sep)))
        except SystemExit as e:
            refused, msg = True, str(e)
        except Exception as e:  # noqa: BLE001 -- a crash is reported AS this case, not as a stack
            refused, msg = False, 'CRASHED: %s: %s' % (type(e).__name__, e)
        finally:
            gen._SRC = None
        check('--apply REFUSES to read a snapshot it is not about to overwrite',
              refused and 'builder' in msg, msg[:160])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print('')
    print('[pilot-cells-cage] %d case(s), %d failed' % (len(PASSED) + len(FAILED), len(FAILED)))
    return 1 if FAILED else 0


if __name__ == '__main__':
    sys.exit(main())
