'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {execFileSync}=require('node:child_process'),{chromium}=require('playwright-core');
const out=process.env.BUILDER_EVIDENCE_ROOT;if(!out)throw Error('Explicit fixture evidence root required');fs.mkdirSync(out,{recursive:true});
const py=process.env.EA_LAB_TEST_PYTHON;if(!py)throw Error('Explicit portable Python required');
const fixtures=JSON.parse(execFileSync(py,[path.join(__dirname,'test_owner_webapp.py'),'--browser-fixtures'],{encoding:'utf8',maxBuffer:16*1024*1024}));
const fixture=fixtures.catalog||fixtures.available,offline=path.join(out,'EA_BUILDER_M1_OFFLINE.html');
fs.writeFileSync(offline,(fixtures.catalog||fixtures.missing).html.replace('</head>','<meta name="ea-lab-mode" content="OFFLINE_SNAPSHOT"></head>').replace('<body>','<body><div class="notice">M1 DRAFT PREVIEW · Monitor fixture observations are synthetic and unavailable; no installed Monitor or accepted result binding.</div><script>if(!location.hash)location.hash="builder";</script>'));
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});let cases=0;
const matrix=[{width:360,height:800},{width:390,height:844},{width:844,height:390},{width:1280,height:900}];
const selected=process.env.BUILDER_VIEWPORT;
if(selected&&!matrix.some(v=>String(v.width)===selected))throw Error('Unknown viewport partition');
const viewports=selected?matrix.filter(v=>String(v.width)===selected):matrix;
try{for(const viewport of viewports)for(const mode of ['online_failure','offline']){
const context=await browser.newContext({viewport,acceptDownloads:true,serviceWorkers:'block'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));const writes=[];page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.method()+' '+r.url());});await page.clock.install({time:new Date('2026-09-24T00:01:00Z')});
await page.route('http://builder.fixture/**',r=>new URL(r.request().url()).pathname==='/api/snapshot'?r.fulfill({status:503,body:'unavailable'}):r.fulfill({contentType:'text/html',body:fixture.html}));
const url=mode==='offline'?pathToFileURL(offline).href:'http://builder.fixture/';if(mode==='offline')await context.setOffline(true);await page.goto(url+'#builder');

if(process.env.BUILDER_MT5_UX_ONLY==='1'){
 if(!fixture.snapshot.builder_profile_decisions)throw Error('MT5 UX requires profile fixture');
 await page.locator('#mt5UxRoot').waitFor();
 assert.equal(await page.locator('#builderForm').getAttribute('data-current-workspace'),'mt5-like');
 assert.equal(await page.locator('[data-mt5-tab]').count(),3);
 assert.equal(await page.locator('[data-mt5-mode="simple"]').evaluate(e=>e.classList.contains('active')),true);
 let visible=await page.locator('#mt5Rows .mt5-param-row').count();assert.ok(visible>=15&&visible<=25,'simple count '+visible);
 const fixed=page.locator('[data-mt5-row="_41_FixedLot"] [data-mt5-value="_41_FixedLot"]');assert.equal(await fixed.inputValue(),'0.01');
 const before=await page.evaluate(()=>{const raw=localStorage.getItem(window.EALabBuilder.PROFILE_KEY);if(!raw)return null;const p=JSON.parse(raw).working;return [...p.shared_values,...p.entry_values,...p.instance_values].find(x=>x.name==='_41_FixedLot');});
 if(before)assert.equal(before.value,null);
 await page.locator('[data-mt5-mode="all"]').click();assert.equal(await page.locator('#mt5Rows .mt5-param-row').count(),153);
 await page.locator('#mt5Search').fill('Risk');const filtered=await page.locator('#mt5Rows .mt5-param-row').count();assert.ok(filtered>0&&filtered<153,'filtered '+filtered);
 await page.locator('#mt5Search').fill('');await page.locator('[data-mt5-mode="simple"]').click();
 await page.locator('[data-mt5-row="_41_FixedLot"] [data-mt5-value="_41_FixedLot"]').fill('0.02');await page.keyboard.press('Tab');
 await page.waitForFunction(()=>{const raw=localStorage.getItem(window.EALabBuilder.PROFILE_KEY);if(!raw)return false;const p=JSON.parse(raw).working,s=[...p.shared_values,...p.entry_values,...p.instance_values].find(x=>x.name==='_41_FixedLot');return s&&s.value==='0.02'&&s.response==='VALUE_PROPOSED';});
 assert.equal(await page.locator('[data-mt5-row="_41_FixedLot"] [data-mt5-value="_41_FixedLot"]').inputValue(),'0.02');
 await page.locator('[data-mt5-tab="optimization"]').click();
 assert.deepEqual(await page.locator('.mt5-opt-table th').allTextContents(),['Optimize','Parameter','Value','Start','Step','Stop']);
 const optBox=page.locator('[data-mt5-opt="_41_FixedLot"][data-k="enabled"]');await optBox.check();
 const optRow=page.locator('tr').filter({has:optBox});await optRow.locator('[data-k="start"]').fill('0.01');await optRow.locator('[data-k="step"]').fill('0.01');await optRow.locator('[data-k="stop"]').fill('0.03');
 await page.locator('[data-mt5-tab="review"]').click();assert.match(await page.locator('#mt5TabReview').innerText(),/NOT_SUBMITTED/);assert.match(await page.locator('#mt5TabReview').innerText(),/Fixed Lot/);
 assert.equal(await page.locator('#mt5Download').isDisabled(),true);
 await page.locator('#mt5ReviewExact').click();await page.locator('#mt5Pending').check();await page.locator('#mt5Confirm').check();
 assert.equal(await page.locator('#mt5Download').isDisabled(),false);
 const dl=page.waitForEvent('download');await page.locator('#mt5Download').click();const dlf=path.join(out,`mt5-ux-request-${viewport.width}-${mode}.json`);await(await dl).saveAs(dlf);const req=JSON.parse(fs.readFileSync(dlf,'utf8'));
 assert.equal(req.status,'NOT_SUBMITTED');assert.equal(req.can_submit,false);assert.equal(req.can_execute,false);assert.equal(req.owner_attestation,false);
 const fixedReq=[...req.profile.shared_values,...req.profile.entry_values,...req.profile.instance_values].find(x=>x.name==='_41_FixedLot');assert.equal(fixedReq.value,'0.02');assert.equal(fixedReq.response,'VALUE_PROPOSED');
 assert.equal('symbol' in req,false);assert.equal('timeframe' in req,false);
 const geometry=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth,root:document.querySelector('#mt5UxRoot').getBoundingClientRect().toJSON()}));assert.ok(geometry.scrollWidth<=geometry.innerWidth+1,JSON.stringify(geometry));
 assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
 await page.screenshot({path:path.join(out,`mt5-ux-${viewport.width}-${mode}.png`),fullPage:true});
 fs.writeFileSync(path.join(out,`MT5_UX_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,simple_count:visible,all_inputs:153,search_count:filtered,source_reference_not_auto_approved:before===null||before.value===null,edited_existing_profile_slot:true,optimization_ui_local:true,request_status:req.status,can_submit:req.can_submit,can_execute:req.can_execute,horizontal_overflow:false,writes},null,2));
 cases++;await context.close();continue;
}

if(fixture.snapshot.builder_profile_decisions){
 assert.equal(await page.locator('[data-current-workspace="one-ea"]').count(),1);assert.equal(await page.locator('#builderForm').evaluate(e=>e.classList.contains('mobile-guided')),true);
 assert.equal(await page.locator('#mobileChrome h2').innerText(),'EA ที่กำลังตั้งค่า');assert.equal(await page.locator('.builder-grid>.panel:visible').count(),0);assert.equal(await page.locator('#mobileDetails').evaluate(e=>e.open),false);
 const beforeDetails=await page.evaluate(()=>({p:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),b:localStorage.getItem(window.EALabBuilder.KEY)}));
 await page.locator('#mobileDetails>summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#mobileDetails').evaluate(e=>e.open),true);await page.locator('#mobileDetails>summary').press('Space');assert.equal(await page.locator('#mobileDetails').evaluate(e=>e.open),false);
 assert.deepEqual(await page.evaluate(()=>({p:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),b:localStorage.getItem(window.EALabBuilder.KEY)})),beforeDetails);
}
const allFields=async()=>{const m=page.locator('#mobileMode');if(await m.count()&&await page.locator('#builderForm').evaluate(e=>e.classList.contains('mobile-guided'))){await page.locator('#mobileDetails').evaluate(e=>e.open=true);await m.click();}};await allFields();
const globalFocus=async()=>{await page.waitForFunction(()=>document.body.dataset.mobileReveal!=='pending');assert.equal(await page.locator('#mobileStatus').evaluate(e=>e===document.activeElement),true);const r=await page.locator('#mobileStatus').evaluate(e=>{const r=e.getBoundingClientRect(),h=document.querySelector('.topbar'),b=h.getBoundingClientRect();return {top:r.top,bottom:r.bottom,clearTop:getComputedStyle(h).position==='sticky'&&b.bottom>0?b.bottom:0,height:innerHeight};});assert.ok(r.top>=r.clearTop&&r.bottom<=r.height,JSON.stringify(r));};
await page.getByRole('heading',{name:'EA Builder',exact:true}).waitFor();assert.match(await page.title(),/EA_LAB/);assert.ok(page.url().endsWith('#builder'));
for(const name of ['Default Profiles','Design EA','Optimize Strategy','Requests & Results'])assert.equal(await page.getByRole('heading',{name,exact:true,includeHidden:true}).count(),1);if(fixture.snapshot.builder_profile_decisions){assert.equal(await page.locator('.builder-grid>.panel>.panel-head>h2:visible').count(),0);const headerControls=page.locator('.builder-grid>.panel>.panel-head').locator('button,input,select,textarea,a,[tabindex]');assert.deepEqual(await headerControls.evaluateAll(es=>es.map(e=>e.id)),['builderAdd']);for(const control of await headerControls.all()){assert.equal(await control.isVisible(),true);await control.focus();assert.equal(await control.evaluate(e=>e===document.activeElement),true);}}
if(fixtures.catalog){
 assert.match(await page.locator('#builderCatalog').innerText(),/AUDIT_METADATA_VERIFIED/);
 for(const [build,count]of [['B17',159],['B22',153]]){await page.locator('#builderWrapper').selectOption(build);assert.equal(await page.locator('.catalog-field').count(),count);assert.match(await page.locator('#builderPopulation').innerText(),new RegExp(build+': '+count+' physical inputs'));await page.locator('.catalog-field').first().click();assert.match(await page.locator('.catalog-field').first().innerText(),/SOURCE_REFERENCE_NOT_OWNER_APPROVED/);assert.match(await page.locator('.catalog-field').first().innerText(),/UNKNOWN_NO_EFFECTIVE_CONFIG/);}
}else assert.match(await page.locator('#main').innerText(),/Input population UNKNOWN/);
assert.equal(await page.getByRole('button',{name:'Submit disabled',exact:true}).isDisabled(),true);
assert.equal(await page.locator('fieldset input').isDisabled(),true);
await page.locator('[data-builder-field="title"]').fill('Owner draft <img onerror=alert(1)>');
await page.clock.fastForward(31000);assert.equal(await page.locator('[data-builder-field="title"]').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('[data-builder-field="title"]').inputValue(),'Owner draft <img onerror=alert(1)>');
await page.locator('[data-builder-field="bindings.entry_contract.id"]').fill('entry-unverified');
await page.getByRole('button',{name:'Add OFF draft',exact:true}).focus();assert.equal(await page.locator('#builderAdd').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('.builder-plan').count(),1);
await page.locator('[data-builder-field="plans.0.name"]').fill('Suggested incomplete plan');
await page.getByRole('button',{name:'DuplicateAsOFFDraft',exact:true}).click();
assert.equal(await page.locator('.builder-plan').count(),2);
fs.writeFileSync(path.join(out,`HEADER_ACTION_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,header_controls:['builderAdd'],visible_and_focusable:true,keyboard_add:true,duplicate_count:2,heading_titles_hidden:true},null,2));
if(process.env.BUILDER_HEADER_FOCUS_ONLY==='1'){assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);cases++;await context.close();continue;}
await page.getByRole('button',{name:'Validate draft',exact:true}).click();assert.match(await page.locator('#builderDiagnostic').innerText(),/"draft_valid":true/);assert.match(await page.locator('#builderDiagnostic').innerText(),/"can_execute":false/);
await page.locator('[data-builder-field="intent"]').selectOption('BUILD_AND_BASELINE');
if(mode==='online_failure'){await page.evaluate(()=>{location.hash='overview'});await page.getByRole('button',{name:/Refresh now/}).click();await page.evaluate(()=>{location.hash='builder'});await page.getByRole('heading',{name:'EA Builder',exact:true}).waitFor();}
assert.equal(await page.locator('[data-builder-field="title"]').inputValue(),'Owner draft <img onerror=alert(1)>');
if(fixtures.catalog){for(const reason of ['CATALOG_ENUM_UNKNOWN_SYMBOL','CATALOG_ENUM_TYPE_MISMATCH','CATALOG_ENUM_CODE_MISMATCH','CATALOG_ENUM_CATALOG_INCOMPLETE','CATALOG_ENUM_DUPLICATE_OR_ALIAS_CONFLICT']){await page.evaluate(reason=>window.EALabBuilder.mount(document.getElementById('main'),{schema:'EA_LAB_BUILDER_CATALOG_V1',status:'UNRESOLVED',profile_approval:'UNRESOLVED',compatibility:'UNKNOWN',can_submit:false,can_execute:false,population:null,wrappers:[],blockers:[reason]}),reason);assert.match(await page.locator('#builderCatalog').innerText(),/Input population UNKNOWN/);assert.ok((await page.locator('#builderCatalog').innerText()).includes(reason));assert.equal(await page.locator('.catalog-field').count(),0);assert.equal(await page.locator('button:has-text("Submit disabled")').isDisabled(),true);assert.equal(await page.locator('[data-builder-field="title"]').inputValue(),'Owner draft <img onerror=alert(1)>');}await page.evaluate(()=>window.EALabBuilder.mount(document.getElementById('main'),window.__EA_LAB_DATA__.builder_catalog,window.__EA_LAB_DATA__.builder_profile_decisions));}
await page.reload();await allFields();assert.equal(await page.locator('[data-builder-field="title"]').inputValue(),'Owner draft <img onerror=alert(1)>');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export draft JSON',exact:true}).click();const downloaded=await download;const file=path.join(out,`roundtrip-${viewport.width}-${mode}.json`);await downloaded.saveAs(file);const draft=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(draft.intent,'BUILD_AND_BASELINE');assert.ok(draft.plans.every(p=>p.enabled===false));assert.notEqual(draft.plans[0].id,draft.plans[1].id);
await page.locator('#builderImport').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schema":1,"schema":2}')});await page.waitForFunction(()=>document.querySelector('#builderDiagnostic').textContent.includes('Import refused'));assert.equal(await page.locator('.builder-plan').count(),2);
await page.locator('#builderImport').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#builderDiagnostic').textContent.includes('Imported UNVERIFIED'));assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('ea_lab.builder.m1.draft'))),draft);
const reviewDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export review proposal — NOT_SUBMITTED',exact:true}).click();const reviewFile=path.join(out,`review-${viewport.width}-${mode}.json`);await(await reviewDownload).saveAs(reviewFile);assert.equal(JSON.parse(fs.readFileSync(reviewFile,'utf8')).status,'NOT_SUBMITTED');
await page.locator('[data-results]').first().click();assert.match(await page.locator('.plan-diagnostic').first().innerText(),/UNAVAILABLE_NO_ACCEPTED_RUN/);
if(fixture.snapshot.builder_profile_decisions){
 await page.locator('#builderWrapper').selectOption('B22');assert.equal(await page.locator('[data-profile-group]').count(),10);assert.match(await page.locator('#profileWorkflow').innerText(),/28 core \/ 86 conditional \/ 31 deferred/);
 assert.equal(await page.locator('[data-profile-value="FirstLotMode"]').inputValue(),'');assert.equal(await page.locator('[data-profile-value="LotProg"]').inputValue(),'');
 await page.locator('#profileTitle').fill('แบบร่าง B22 <img onerror=alert(1)>');
 await page.locator('[data-profile-value="FirstLotMode"]').selectOption('FIRSTLOT_RISK');assert.equal(await page.locator('[data-profile-value="_42_RiskPct"]').count(),1);await page.locator('[data-profile-value="_42_RiskPct"]').fill('1');
 await page.locator('[data-profile-value="FirstLotMode"]').selectOption('FIRSTLOT_FIXED');assert.equal(await page.locator('[data-profile-value="_42_RiskPct"]').count(),0);await page.locator('[data-profile-value="_41_FixedLot"]').fill('0.01');
 await page.locator('[data-profile-value="LotProg"]').selectOption('PROG_PLUS');await page.locator('[data-profile-value="_53_PlusLot"]').fill('0.01');await page.locator('[data-profile-value="_9_MaxLevels"]').fill('20');
 await page.locator('[data-profile-value="DryRun"]').selectOption('false');await page.locator('[data-profile-value="_0_MaxSpread"]').fill('0');await page.locator('[data-profile-value="_0_Magic"]').fill('9007199254740993');
 assert.equal(await page.locator('#builderForm').evaluate(e=>e.classList.contains('mobile-guided')),false);assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');
 await page.locator('[data-profile-value="RC_MaxLevelsOverride"]').fill('1.5');await page.locator('#profileReview').click();assert.equal(await page.locator('#profileSend').isDisabled(),true);assert.match(await page.locator('#profileDiagnostics').innerText(),/exact integer literal/);assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');assert.equal(await page.locator('[data-profile-value="RC_MaxLevelsOverride"]').evaluate(e=>e===document.activeElement),true);await page.locator('[data-profile-value="RC_MaxLevelsOverride"]').fill('0');
 await page.locator('[data-profile-value="StackMode"]').selectOption('STACK_PYRAMID');assert.equal(await page.locator('[data-profile-value="_9_PendingMode"]').count(),1);await page.locator('[data-profile-value="StackMode"]').selectOption('STACK_SINGLE');
 await page.locator('[data-profile-value="SLMode"]').selectOption('SL_ATR');const recoveryAdaptive=fixture.snapshot.builder_profile_decisions.rows.find(r=>r.name==='RecoveryMode').constraints.enum_symbols.find(s=>s.endsWith('_ADAPTIVE'));await page.locator('[data-profile-value="RecoveryMode"]').selectOption(recoveryAdaptive);await page.locator('[data-profile-value="HedgeMode"]').selectOption('HEDGE_OFF');await page.locator('[data-profile-value="UseMiddlePathVeto"]').selectOption('true');
 const toggleSnapshot=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');
 const beforeAdvanced=await page.locator('[data-profile-row]').count();await page.locator('#profileView').click();assert.equal(await page.locator('[data-profile-row]').count(),153);assert.ok(beforeAdvanced<153);await page.locator('#profileView').click();
 assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');assert.equal(await page.locator('[data-profile-row]').count(),beforeAdvanced);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),toggleSnapshot);
 // A filtered risk proposal still requires Advanced expansion on error; no predicate is weakened.
 assert.equal(await page.locator('[data-profile-value="_42_RiskPct"]').count(),0);await page.locator('#profileView').click();await page.locator('[data-profile-value="_42_RiskPct"]').fill('1e-400');await page.locator('#profileView').click();assert.equal(await page.locator('[data-profile-value="_42_RiskPct"]').count(),0);
 const hiddenSnapshot=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));await page.locator('#profileReview').click();await page.waitForFunction(()=>document.body.dataset.mobileReveal!=='pending');
 assert.equal(await page.locator('#profileView').innerText(),'Normal view');assert.equal(await page.locator('[data-profile-row]').count(),153);assert.equal(await page.locator('[data-profile-value="_42_RiskPct"]').evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),hiddenSnapshot);
 const hiddenGeometry=await page.locator('[data-profile-value="_42_RiskPct"]').evaluate(el=>{const r=el.getBoundingClientRect(),h=document.querySelector('.topbar'),b=h.getBoundingClientRect(),top=getComputedStyle(h).position==='sticky'?Math.max(0,b.bottom):0;const hits=[[.05,.05],[.95,.05],[.5,.5],[.05,.95],[.95,.95]].map(([x,y])=>{const hit=document.elementFromPoint(r.left+r.width*x,r.top+r.height*y);return hit===el||el.contains(hit);});return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,clearTop:top,height:innerHeight,width:innerWidth,hits};});assert.ok(hiddenGeometry.top>=hiddenGeometry.clearTop&&hiddenGeometry.bottom<=hiddenGeometry.height&&hiddenGeometry.left>=0&&hiddenGeometry.right<=hiddenGeometry.width&&hiddenGeometry.hits.every(Boolean),JSON.stringify(hiddenGeometry));
 await page.locator('[data-profile-value="_42_RiskPct"]').fill('1');await page.locator('#profileView').click();assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');
 fs.writeFileSync(path.join(out,`ADVANCED_STATE_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,visible_error_preserves_normal:true,explicit_full_population:153,normal_count:beforeAdvanced,hidden_error_expands:true,hiddenGeometry,view_changes_preserve_cache:true},null,2));
 if(process.env.BUILDER_ADVANCED_FOCUS_ONLY==='1'){assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);cases++;await context.close();continue;}

 await page.locator('#profileSave').click();assert.equal(await page.locator('[data-profile-value="DryRun"]').isDisabled(),true);await page.locator('#profileFork').click();assert.equal(await page.locator('[data-profile-value="DryRun"]').isDisabled(),false);
 const pd=page.waitForEvent('download');await page.locator('#profileExport').click();const pf=path.join(out,`profile-${viewport.width}-${mode}.json`);await(await pd).saveAs(pf);const profile=JSON.parse(fs.readFileSync(pf,'utf8'));const value=n=>[...profile.shared_values,...profile.entry_values,...profile.instance_values].find(r=>r.name===n).value;assert.equal(value('DryRun'),'false');assert.equal(value('_0_MaxSpread'),'0');assert.equal(value('_0_Magic'),'9007199254740993');assert.equal(value('_42_RiskPct'),'1');assert.notEqual(profile.parent_revision,null);assert.equal(profile.authority,'LOCAL_DRAFT_UNVERIFIED');
 const liveTitle=await page.locator('#profileTitle').inputValue();for(const raw of [fs.readFileSync(pf,'utf8').replace('"title":','"title":"duplicate","title":'),JSON.stringify({...profile,shared_values:profile.shared_values.map((r,i)=>i? r:{...r,value:false,response:'VALUE_PROPOSED'})}),JSON.stringify({...profile,pins:{...profile.pins,decision_sha256:'0'.repeat(64)}})]){await page.locator('#profileImport').setInputFiles({name:'invalid-profile.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Import refused'));assert.equal(await page.locator('#profileTitle').inputValue(),liveTitle);}
 await page.locator('#profileImport').setInputFiles(pf);await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified'));assert.equal(await page.locator('#profileNotes').isDisabled(),true);const importedProfileCache=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.IMPORT_KEY)),fs.readFileSync(pf,'utf8'));await page.locator('#profileNotes').evaluate(e=>{e.value='attempted fresh profile parent change';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),importedProfileCache);await page.reload();await allFields();assert.equal(await page.locator('#profileTitle').inputValue(),profile.title);assert.equal(await page.locator('#profileNotes').isDisabled(),true);assert.equal(await page.locator('[data-profile-value="DryRun"]').inputValue(),'false');
 await page.locator('#profileReview').click();assert.equal(await page.locator('#profileSend').isDisabled(),true);await page.locator('#profileConfirm').check();await page.locator('#profileSend').click();assert.match(await page.locator('#profileDiagnostics').innerText(),/Required decisions remain/);
 await page.locator('#profilePending').check();const rd=page.waitForEvent('download');await page.locator('#profileSend').click();const rf=path.join(out,`profile-request-${viewport.width}-${mode}.json`);await(await rd).saveAs(rf);const request=JSON.parse(fs.readFileSync(rf,'utf8'));assert.equal(request.status,'NOT_SUBMITTED');assert.equal(request.intent,'PENDING_DECISIONS');assert.equal(request.can_submit,false);assert.equal(request.owner_attestation,false);assert.ok(request.unresolved_questions.length>0);assert.ok(request.builder_draft.plans.every(p=>p.enabled===false));assert.deepEqual(request.profile,profile);assert.match(await page.locator('#profileDiagnostics').innerText(),/No intake or activation/);
 await page.locator('#profileImport').setInputFiles(rf);await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified request'));assert.equal(await page.locator('#profileTitle').inputValue(),profile.title);assert.equal(await page.locator('[data-profile-value="_0_Magic"]').inputValue(),'9007199254740993');
 await page.locator('#builderWrapper').selectOption('B17');assert.match(await page.locator('#profileWorkflow').innerText(),/OUT_OF_SCOPE/);await page.locator('#builderWrapper').selectOption('B22');assert.equal(await page.locator('#profileTitle').inputValue(),profile.title);
 await page.locator('#profileFork').click(); await page.locator('#profileReview').click();await page.locator('#profileConfirm').check();await page.locator('#profileNotes').fill('Edited after review');assert.equal(await page.locator('#profileSend').isDisabled(),true);

 let boundaryDownloads=0;const observeDownload=()=>boundaryDownloads++;page.on('download',observeDownload);
 for(const [literal,reason]of [['1e-400','underflows'],['-1e-400','underflows'],['1e999','overflow'],['9007199254740993','loses precision'],['0.10000000000000001','loses precision']]){
  await page.locator('[data-profile-value="_41_FixedLot"]').fill(literal);await page.locator('#profileReview').click();assert.match(await page.locator('#profileDiagnostics').innerText(),new RegExp(reason));assert.equal(await page.locator('#profileConfirm').isDisabled(),true);assert.equal(await page.locator('#profileSend').isDisabled(),true);const count=boundaryDownloads;await page.locator('#profileExport').click();assert.equal(boundaryDownloads,count);
 }
 for(const [literal,representation]of [['0','0'],['-0','-0'],['1e-2','0.01']]){
  await page.locator('[data-profile-value="_41_FixedLot"]').fill(literal);await page.locator('#profileReview').click();await page.locator('#profilePending').check();await page.locator('#profileConfirm').check();const download=page.waitForEvent('download');await page.locator('#profileSend').click();const file=path.join(out,`numeric-${literal.replace('-','minus')}-${viewport.width}-${mode}.json`);await(await download).saveAs(file);const req=JSON.parse(fs.readFileSync(file,'utf8')),r=req.review_summary.values.find(r=>r.name==='_41_FixedLot');assert.equal(r.owner_proposed_value,literal);assert.equal(r.resolved_proposal.representation,representation);assert.equal(req.validation.type_valid,true);assert.equal(req.status,'NOT_SUBMITTED');assert.equal(req.can_execute,false);
 }
 await page.locator('#profileSave').click();const goodRaw=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),good=JSON.parse(goodRaw),saved=good.working;assert.deepEqual(good.history.find(r=>r.profile_id===saved.profile_id&&r.revision===saved.revision),saved);assert.equal(await page.locator('#profileNotes').isDisabled(),true);
 const conflict=structuredClone(saved);conflict.notes='Conflicting immutable content';
 const conflictingRequest=JSON.parse(fs.readFileSync(rf,'utf8'));conflictingRequest.profile=conflict;
 for(const doc of [conflict,conflictingRequest]){await page.locator('#profileImport').setInputFiles({name:'saved-collision.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Import refused'));assert.match(await page.locator('#profileDiagnostics').innerText(),/content conflict/);assert.equal(await page.locator('#profileNotes').inputValue(),saved.notes);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),goodRaw);}
 const savedDownload=page.waitForEvent('download');await page.locator('#profileExport').click();const savedFile=path.join(out,`immutable-${viewport.width}-${mode}.json`);await(await savedDownload).saveAs(savedFile);assert.deepEqual(JSON.parse(fs.readFileSync(savedFile,'utf8')),saved);
 await page.locator('#profileDuplicate').click();let dup=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)));assert.notEqual(dup.working.profile_id,saved.profile_id);assert.notEqual(dup.working.revision,saved.revision);assert.equal(dup.working.parent_revision,null);assert.ok(Object.values(dup.working.bindings).every(b=>b.id===''&&b.revision===''));assert.deepEqual(dup.history,good.history);
 await page.locator('#profileImport').setInputFiles(savedFile);await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified'));assert.equal(await page.locator('#profileNotes').isDisabled(),true);await page.locator('#profileFork').click();await page.locator('#profileNotes').fill('Explicit new revision content');const forked=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)));assert.equal(forked.working.parent_revision,saved.revision);assert.notEqual(forked.working.revision,saved.revision);assert.deepEqual(forked.history,good.history);
 // The original failure is refused atomically; stored bytes survive edits/save/export.
 const badRaw=JSON.stringify({working:conflict,history:good.history});await page.evaluate(raw=>localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw),badRaw);await page.reload();await allFields();assert.match(await page.locator('#profileDiagnostics').innerText(),/content conflict/);assert.notEqual(await page.locator('#profileId').inputValue(),saved.profile_id);await page.locator('#profileNotes').fill('Fresh unverified backup; refused cache retained');await page.locator('#profileSave').click();assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),badRaw);
 await page.locator('#profileImport').setInputFiles({name:'refused-cache-reimport.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(conflict))});await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Import refused'));assert.match(await page.locator('#profileDiagnostics').innerText(),/Stored revision cache refused/);await globalFocus();assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),badRaw);
 const freshDownload=page.waitForEvent('download');await page.locator('#profileExport').click();const freshFile=path.join(out,`cache-refusal-backup-${viewport.width}-${mode}.json`);await(await freshDownload).saveAs(freshFile);assert.notEqual(JSON.parse(fs.readFileSync(freshFile,'utf8')).profile_id,saved.profile_id);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),badRaw);
 const dupRaw=JSON.stringify({working:saved,history:[saved,saved]});await page.evaluate(raw=>localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw),dupRaw);await page.reload();await allFields();assert.match(await page.locator('#profileDiagnostics').innerText(),/Duplicate saved/);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),dupRaw);
 // Imported originals use strict preflight for both explicit child routes. A stale cache creates no child.
 const routeCases=[];
 for(const kind of ['profile','request'])for(const route of ['#mobileRevise','#profileFork']){
  await page.evaluate(raw=>{localStorage.removeItem('ea_lab.builder.m1.imported_original');localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw);},goodRaw);await page.reload();await allFields();
  const originalRaw=kind==='profile'?fs.readFileSync(savedFile,'utf8'):fs.readFileSync(rf,'utf8');
  await page.locator('#profileImport').setInputFiles({name:`route-${kind}.json`,mimeType:'application/json',buffer:Buffer.from(originalRaw)});
  await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified'));
  const originalDoc=JSON.parse(originalRaw),parent=kind==='profile'?originalDoc:originalDoc.profile;
  const before=await page.evaluate(()=>({cache:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),builder:localStorage.getItem(window.EALabBuilder.KEY),original:localStorage.getItem('ea_lab.builder.m1.imported_original')}));
  assert.equal(before.original,originalRaw);assert.equal(await page.locator('#profileNotes').isDisabled(),true);
  const valid=JSON.parse(before.cache);assert.deepEqual(valid.working,parent);assert.deepEqual(valid.history.find(x=>x.profile_id===parent.profile_id&&x.revision===parent.revision),parent);
  const external=structuredClone(parent);external.revision+=`-external-${kind}-${route.slice(1)}`;external.parent_revision=parent.revision;external.notes='Another tab saved a revision';
  const changed=JSON.stringify({working:parent,history:[...valid.history,external]});await page.evaluate(raw=>localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw),changed);
  const downloadsBefore=boundaryDownloads;await page.locator(route).click();await globalFocus();assert.match(await page.locator('#profileDiagnostics').innerText(),/Stale revision cache/);
  assert.equal(await page.locator('#profileNotes').isDisabled(),true);assert.equal(await page.locator('#profileId').inputValue(),parent.profile_id);assert.equal(await page.locator('#profileNotes').inputValue(),parent.notes);
  assert.deepEqual(await page.evaluate(()=>({cache:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),builder:localStorage.getItem(window.EALabBuilder.KEY),original:localStorage.getItem('ea_lab.builder.m1.imported_original')})),{cache:changed,builder:before.builder,original:before.original});
  await page.locator('#profileExport').click();assert.equal(boundaryDownloads,downloadsBefore);await globalFocus();
  // Reload observes the current valid cache; only then may the same explicit action create an editable child.
  await page.reload();await allFields();await page.locator(route).click();
  const child=await page.evaluate(()=>({cache:JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),builder:JSON.parse(localStorage.getItem(window.EALabBuilder.KEY)),original:localStorage.getItem('ea_lab.builder.m1.imported_original')}));
  assert.notEqual(child.cache.working.revision,parent.revision);assert.equal(child.cache.working.parent_revision,parent.revision);assert.equal(child.cache.working.profile_id,parent.profile_id);
  assert.deepEqual(child.cache.history,JSON.parse(changed).history);assert.equal(child.original,originalRaw);assert.equal(await page.locator('#profileNotes').isDisabled(),false);
  assert.equal(await page.locator('#profileSend').isDisabled(),true);assert.equal(await page.locator('#profileConfirm').isChecked(),false);
  const previousBuilder=JSON.parse(before.builder);assert.notEqual(child.builder.revision,previousBuilder.revision);assert.equal(child.builder.parent_revision,previousBuilder.revision);assert.deepEqual(child.builder.bindings.default_profile,{id:"",revision:""});
  await page.locator('#profileNotes').fill('Explicit healthy child after current-cache reload');await page.reload();await allFields();assert.equal(await page.locator('#profileNotes').isDisabled(),false);assert.equal(await page.locator('#profileNotes').inputValue(),'Explicit healthy child after current-cache reload');
  const after=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)));assert.deepEqual(after.history,JSON.parse(changed).history);assert.deepEqual(after.history.find(x=>x.profile_id===parent.profile_id&&x.revision===parent.revision),parent);assert.equal(await page.evaluate(()=>localStorage.getItem('ea_lab.builder.m1.imported_original')),originalRaw);
  routeCases.push({kind,route,stale_refused_before_child:true,exact_cache_builder_original_preserved:true,current_cache_reload_explicit_child:true,parent_immutable:true,child_reload_editable:true,approval_invalidated:true});
 }
 // Non-imported legacy local Fork remains editable, but stale writes/exports are refused.
 await page.evaluate(raw=>{localStorage.removeItem('ea_lab.builder.m1.imported_original');localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw);},goodRaw);assert.equal(await page.evaluate(()=>localStorage.getItem('ea_lab.builder.m1.imported_original')),null);await page.reload();await allFields();const extra=structuredClone(saved);extra.revision+='-external';extra.parent_revision=saved.revision;extra.notes='Saved by another tab';const staleRaw=JSON.stringify({working:saved,history:[...good.history,extra]});await page.evaluate(raw=>localStorage.setItem(window.EALabBuilder.PROFILE_KEY,raw),staleRaw);let count=boundaryDownloads;await page.locator('#profileExport').click();assert.match(await page.locator('#profileDiagnostics').innerText(),/Stale revision cache/);await globalFocus();assert.equal(boundaryDownloads,count);await page.locator('#profileFork').click();await page.locator('#profileNotes').fill('Stale tab edit');assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),staleRaw);count=boundaryDownloads;await page.locator('#profileExport').click();assert.equal(boundaryDownloads,count);await page.reload();await allFields();assert.equal(await page.locator('#profileNotes').inputValue(),saved.notes);assert.equal(await page.locator('#profileNotes').isDisabled(),true);
 // Storage quota failure preserves a known-valid live fork for JSON backup.
 await page.locator('#profileFork').click();await page.evaluate(()=>{window.profileOriginalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===window.EALabBuilder.PROFILE_KEY)throw Error('quota test');return window.profileOriginalSet.call(this,k,v);};});await page.locator('#profileNotes').fill('Quota preserved live fork');assert.equal(await page.locator('#profileNotes').evaluate(e=>e===document.activeElement),true);assert.match(await page.locator('#profileDiagnostics').innerText(),/quota test/);const quotaDownload=page.waitForEvent('download');await page.locator('#profileExport').click();const quotaFile=path.join(out,`quota-backup-${viewport.width}-${mode}.json`);await(await quotaDownload).saveAs(quotaFile);assert.equal(JSON.parse(fs.readFileSync(quotaFile,'utf8')).notes,'Quota preserved live fork');await page.evaluate(()=>{Storage.prototype.setItem=window.profileOriginalSet;delete window.profileOriginalSet;});
 fs.writeFileSync(path.join(out,`BOUNDARY_BROWSER_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,numeric_negatives:5,numeric_downloads:3,immutable_imports_refused:2,cache_conflict_refused:true,cache_bytes_preserved:true,duplicate_history_refused:true,stale_export_and_write_refused:true,duplicate_fork_valid:true,quota_backup_valid:true,NOT_SUBMITTED:true},null,2));page.off('download',observeDownload);
 fs.writeFileSync(path.join(out,`ROUTE_STATE_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,imported_cases:routeCases,nonimported_legacy_stale_fork_editable:true,legacy_stale_write_export_refused:true,quota_backup_preserved:true},null,2));
 if(process.env.BUILDER_ROUTE_FOCUS_ONLY==='1'){await context.close();continue;}

 const contrast=await page.locator('[data-profile-row="DryRun"]').evaluate(e=>{const c=getComputedStyle(e),lum=x=>{const a=x.match(/\d+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722;},a=lum(c.color),b=lum(c.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});assert.ok(contrast>=4.5);
 await page.locator('[data-profile-row="DryRun"]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`profile-values-${viewport.width}-${mode}.png`)});
 await page.locator('#profileTitle').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`profile-viewport-${viewport.width}-${mode}.png`)});await page.screenshot({path:path.join(out,`profile-${viewport.width}-${mode}.png`),fullPage:true});
}

// Guided one-EA flow uses the same accepted data and validators as all-fields.
if(fixture.snapshot.builder_profile_decisions){
 const geometry=async selector=>{
  await page.waitForFunction(()=>document.body.dataset.mobileReveal!=='pending');
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const result=await page.locator(selector).evaluate(el=>{const r=el.getBoundingClientRect(),h=document.querySelector('.topbar'),hr=h.getBoundingClientRect(),bar=document.querySelector('#mobileBar'),b=bar.getBoundingClientRect(),v=visualViewport,lo=v?.offsetTop||0,hi=lo+(v?.height||innerHeight),top=['sticky','fixed'].includes(getComputedStyle(h).position)&&hr.bottom>lo&&hr.top<hi?Math.max(lo,hr.bottom):lo,bottom=getComputedStyle(bar).position==='sticky'&&b.bottom>lo&&b.top<hi?Math.min(hi,b.top):hi;
   const hits=[[.05,.05],[.95,.05],[.5,.5],[.05,.95],[.95,.95]].map(([x,y])=>{const hit=document.elementFromPoint(r.left+r.width*x,r.top+r.height*y);return el===hit||el.contains(hit);});
   return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height,clearTop:top,clearBottom:bottom,viewportWidth:innerWidth,unobscured:hits.every(Boolean),hits,flow:document.body.classList.contains('mobile-chrome-flow')};});
  assert.ok(result.top>=result.clearTop&&result.bottom<=result.clearBottom&&result.left>=0&&result.right<=result.viewportWidth&&result.unobscured,JSON.stringify({selector,...result}));return result;
 };
 const go=async step=>{await page.locator('#mobileIndex').evaluate(e=>e.open=true);await page.locator('[data-mobile-go='+step+']').click();};
 const primaryOne=async()=>{assert.equal(await page.locator('[data-current-workspace="one-ea"]').count(),1);assert.ok(await page.locator('.builder-grid>.panel:visible').count()<=1);};
 await page.evaluate(()=>{localStorage.clear();});await page.reload();
 if((await page.locator('#mobileMode').innerText()).includes('เปิดขั้นตอน'))await page.locator('#mobileMode').click();
 await go('start');
 assert.equal(await page.locator('#mobileNew').isVisible(),true);const headerGeometry=await geometry('#mobileChrome h2');
 await page.screenshot({path:path.join(out,`mobile-start-${viewport.width}-${mode}.png`)});
 await page.locator('#mobileNew').click();await page.locator('#mobileConfirmNew').click();
 await page.locator('[data-builder-field="title"]').fill('EA ภาษาไทย '+ 'ทดสอบคำอธิบายยาว '.repeat(12));
 const before=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));
 for(const g of fixture.snapshot.builder_profile_decisions.groups){await go(g.id);assert.equal(await page.locator(`[data-profile-group="${g.id}"]`).isVisible(),true);}
 assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),before);
 await go('SIZING');await page.locator('[data-profile-value="FirstLotMode"]').selectOption('FIRSTLOT_FIXED');await page.locator('[data-profile-value="_41_FixedLot"]').fill('1e-400');await page.locator('#mobileNext').click();
 assert.equal(await page.locator('[data-profile-value="_41_FixedLot"]').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('[data-profile-value="_41_FixedLot"]').getAttribute('aria-invalid'),'true');
 assert.equal(await page.locator('#builderForm').evaluate(e=>e.classList.contains('mobile-guided')),true);assert.equal(await page.locator('#profileView').innerText(),'Advanced full surface');
 const errorGeometry=await geometry('[data-profile-value="_41_FixedLot"]');await page.screenshot({path:path.join(out,`mobile-error-${viewport.width}-${mode}.png`)});await page.locator('[data-profile-value="_41_FixedLot"]').fill('0.01');
 await page.locator('#mobileSave').click();await go(fixture.snapshot.builder_profile_decisions.groups[0].id);
 await primaryOne();assert.equal(await page.locator('#mobileIdentityDetails').evaluate(e=>e.open),false);await page.locator('#mobileIdentityDetails>summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#profileHistory').isVisible(),true);await page.locator('#mobileIdentityDetails>summary').press('Space');assert.equal(await page.locator('#mobileIdentityDetails').evaluate(e=>e.open),false);
 const original=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)));
 await page.locator('#mobileRevise').click();const revised=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)));assert.deepEqual(revised.history,original.history);assert.equal(revised.working.parent_revision,original.working.revision);assert.notEqual(revised.working.revision,original.working.revision);
 await go('review');await primaryOne();await page.locator('#profileReview').click();
 const human=page.locator('#mobileHumanReview');assert.ok((await human.innerText()).includes(revised.working.revision));assert.ok((await human.innerText()).includes('B22'));
 assert.equal(await page.locator('[data-review-value="_41_FixedLot"] strong').innerText(),'0.01');assert.ok(await page.locator('[data-review-reference="builder.entry_contract"]').isVisible());
 assert.ok(await page.locator('[data-review-group="SIZING"]').isVisible());assert.ok(await page.locator('#mobileHumanReview li').count()>0);
 const beforeJump=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));
 await page.getByRole('button',{name:'แก้ไข _41_FixedLot',exact:true}).click();
 assert.equal(await page.locator('[data-profile-value="_41_FixedLot"]').evaluate(e=>e===document.activeElement),true);await geometry('[data-profile-value="_41_FixedLot"]');assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),beforeJump);
 await go('review');await page.locator('#profileReview').click();await go('request');assert.equal(await page.getByRole('button',{name:'ส่งจริง — ยังไม่พร้อม',exact:true}).isDisabled(),true);await page.locator('#profilePending').check();await page.locator('#profileConfirm').check();
 // MOBILE-TR-001: qualified view-only navigation must preserve derived readiness and exact data.
 const confirmedBytes=await page.evaluate(()=>({profile:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),builder:localStorage.getItem(window.EALabBuilder.KEY)}));
 const ready=async()=>{assert.equal(await page.locator('#profileConfirm').isChecked(),true);assert.equal(await page.locator('#profilePending').isChecked(),true);assert.equal(await page.locator('#profileSend').isDisabled(),false);assert.deepEqual(await page.evaluate(()=>({profile:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),builder:localStorage.getItem(window.EALabBuilder.KEY)})),confirmedBytes);};
 await ready();
 for(let i=0;i<3;i++){await page.locator('[data-review-step="review"]').click();await page.locator('#mobileNext').click();await ready();await page.locator('#mobileBack').click();await page.locator('#mobileNext').click();await ready();await go('review');await go('request');await ready();}
 await page.locator('[data-review-step="review"]').click();
 const valueJump=page.locator('[data-review-step]').filter({hasText:'_41_FixedLot'}).first();await valueJump.click();await go('request');await ready();
 const event=page.waitForEvent('download');await page.locator('#profileSend').click();const requestFile=path.join(out,`mobile-request-${viewport.width}-${mode}.json`);await(await event).saveAs(requestFile);const req=JSON.parse(fs.readFileSync(requestFile,'utf8'));assert.equal(req.status,'NOT_SUBMITTED');assert.equal(req.can_submit,false);assert.deepEqual(req.profile,JSON.parse(confirmedBytes.profile).working);assert.deepEqual(req.builder_draft,JSON.parse(confirmedBytes.builder));
 await go(fixture.snapshot.builder_profile_decisions.groups[0].id);await page.locator('#profileNotes').fill('แก้ไขหลังตรวจทาน');assert.equal(await page.locator('#profileSend').isDisabled(),true);assert.equal(await page.locator('#profileConfirm').isChecked(),false);assert.equal(await page.locator('#profileConfirm').isDisabled(),true);
 const rawBefore=await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY));await page.locator('#profileImport').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schema":1,"schema":2}')});await page.waitForFunction(()=>document.querySelector('#mobileStatus').textContent.includes('Import refused'));assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),rawBefore);
 assert.equal(await page.locator('#mobileStatus').evaluate(e=>e===document.activeElement),true);await geometry('#mobileStatus');
 const badPin=structuredClone(req);badPin.pins.decision_sha256='0'.repeat(64);
 for(const raw of ['{',JSON.stringify(badPin)]){await page.locator('#mobileStatus').evaluate(e=>e.textContent='');await page.locator('#profileImport').setInputFiles({name:'bad-global.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForFunction(()=>document.querySelector('#mobileStatus').textContent.includes('Import refused'));assert.equal(await page.locator('#mobileStatus').evaluate(e=>e===document.activeElement),true);await geometry('#mobileStatus');assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),rawBefore);}
 await page.locator('#profileNotes').fill('typing retains focus');assert.equal(await page.locator('#profileNotes').evaluate(e=>e===document.activeElement),true);

 await go('review');await page.locator('#profileReview').click();await go('request');await page.locator('#profilePending').check();await page.locator('#profileConfirm').check();assert.equal(await page.locator('#profileSend').isDisabled(),false);
 await page.locator('#profileImport').setInputFiles(requestFile);await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified request'));assert.equal(await page.locator('#profileConfirm').isChecked(),false);assert.equal(await page.locator('#profileSend').isDisabled(),true);
 const importedRaw=fs.readFileSync(requestFile,'utf8');
 assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.IMPORT_KEY)),importedRaw);
 const lockedBefore=await page.evaluate(()=>({p:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),b:localStorage.getItem(window.EALabBuilder.KEY)}));
 assert.equal(await page.locator('#profileNotes').isDisabled(),true);
 await page.locator('#profileNotes').evaluate(e=>{e.value='attempted parent mutation';e.dispatchEvent(new Event('input',{bubbles:true}));});
 assert.deepEqual(await page.evaluate(()=>({p:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),b:localStorage.getItem(window.EALabBuilder.KEY)})),lockedBefore);
 await page.reload();await allFields();assert.equal(await page.locator('#profileNotes').isDisabled(),true);assert.equal(await page.locator('[data-builder-field="title"]').isDisabled(),true);
 await page.locator('[data-builder-field="title"]').evaluate(e=>{e.value='attempted Builder parent mutation';e.dispatchEvent(new Event('input',{bubbles:true}));});
 assert.deepEqual(await page.evaluate(()=>({p:localStorage.getItem(window.EALabBuilder.PROFILE_KEY),b:localStorage.getItem(window.EALabBuilder.KEY)})),lockedBefore);
 await page.locator('#profileReview').click();await page.locator('#profilePending').check();await page.locator('#profileConfirm').check();assert.equal(await page.locator('#profileSend').isDisabled(),false);
 await page.locator('#mobileRevise').click();const copy=await page.evaluate(()=>({p:JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)),b:JSON.parse(localStorage.getItem(window.EALabBuilder.KEY))}));assert.equal(copy.p.working.parent_revision,req.profile.revision);assert.equal(copy.b.parent_revision,req.builder_draft.revision);assert.deepEqual(copy.p.history.find(p=>p.revision===req.profile.revision),req.profile);
 assert.equal(await page.locator('#profileConfirm').isChecked(),false);assert.equal(await page.locator('#profileSend').isDisabled(),true);
 fs.writeFileSync(path.join(out,`TR001_READINESS_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,repeated_summary_next_back_index:3,value_jump_preserves_confirmation:true,exact_snapshot_download:true,edit_invalidates:true,import_invalidates:true,child_revision_invalidates:true,real_submit_disabled:true,NOT_SUBMITTED:true},null,2));
 await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)).working),copy.p.working);assert.equal(await page.evaluate(()=>localStorage.getItem(window.EALabBuilder.IMPORT_KEY)),importedRaw);
 await allFields();await page.locator('#profileImport').setInputFiles(requestFile);await page.waitForFunction(()=>document.querySelector('#profileDiagnostics').textContent.includes('Imported unverified request'));assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem(window.EALabBuilder.PROFILE_KEY)).history.find(p=>p.revision===JSON.parse(localStorage.getItem(window.EALabBuilder.IMPORT_KEY)).profile.revision)),req.profile);await page.locator('#mobileRevise').click();
 if((await page.locator('#mobileMode').innerText()).includes('เปิดขั้นตอน'))await page.locator('#mobileMode').click();
 await go('idea');await page.locator('[data-builder-field="notes"]').fill('ทดสอบภาษาไทย '.repeat(80));await page.locator('#mobileBack').click();await page.locator('#mobileResume').click();assert.ok((await page.locator('[data-builder-field="notes"]').inputValue()).startsWith('ทดสอบภาษาไทย'));
 for(const selector of ['#mobileNext','#mobileBack','#mobileSave']){const rect=await page.locator(selector).boundingBox();assert.ok(rect.height>=44&&rect.width>=44);}
 await page.locator('#mobileIndex').evaluate(e=>e.open=true);await page.screenshot({path:path.join(out,`mobile-guided-${viewport.width}-${mode}.png`)});
 await page.setViewportSize({width:viewport.width,height:320});await page.locator('[data-builder-field="notes"]').focus();await page.locator('[data-builder-field="notes"]').scrollIntoViewIfNeeded();assert.equal(await page.locator('#mobileBar').evaluate(e=>getComputedStyle(e).position),'static');await page.setViewportSize(viewport);
 await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>document.documentElement.style.fontSize='');

 // Real CSS zoom affects px-sized controls as well as rem text; retain the earlier text-only test.
 await go('SIZING');await page.locator('[data-profile-value="_41_FixedLot"]').fill('1e-400');
 await page.evaluate(()=>document.documentElement.style.zoom='2');await page.locator('#mobileNext').click();
 const zoomGeometry=await geometry('[data-profile-value="_41_FixedLot"]');
 const zoomDirections=[];
 for(const edge of ['top','bottom']){await page.evaluate(edge=>scrollTo({top:edge==='top'?0:document.documentElement.scrollHeight,behavior:'instant'}),edge);await page.locator('#mobileNext').click();zoomDirections.push(await geometry('[data-profile-value="_41_FixedLot"]'));}
 for(const selector of ['#mobileNext','#mobileBack','#mobileSave']){const r=await page.locator(selector).boundingBox();assert.ok(r.width>=44&&r.height>=44);}

 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const headerOverflow=await page.locator('.topbar').evaluate(el=>[...el.children].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<0||r.right>innerWidth+1);}).map(e=>e.id||e.className));assert.deepEqual(headerOverflow,[]);
 await page.screenshot({path:path.join(out,`mobile-zoom200-${viewport.width}-${mode}.png`)});
 await page.evaluate(()=>document.documentElement.style.zoom='');await page.locator('[data-profile-value="_41_FixedLot"]').fill('0.01');
 fs.writeFileSync(path.join(out,`SINGLE_WORKSPACE_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,default_guided_every_width:true,one_current_workspace:true,one_primary_panel:true,secondary_keyboard_toggle:true,history_reachable:true,old_data_semantics_retained:true},null,2));
 fs.writeFileSync(path.join(out,`MOBILE_RECEIPT-${viewport.width}-${mode}.json`),JSON.stringify({result:'PASS',viewport,mode,groups:10,focus:true,headerGeometry,errorGeometry,zoomGeometry,zoomDirections,headerOverflow,immutable_parent:true,download_reimport:true,reload:true,invalidation:true,malformed_preserved:true,native_phone:'NOT_QUALIFIED'},null,2));
}

assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);await page.screenshot({path:path.join(out,`builder-${viewport.width}-${mode}.png`),fullPage:true});cases++;await context.close();
}console.log(JSON.stringify({result:'PASS',cases,offline_artifact:offline}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
