(()=>{'use strict';
let DATA=window.__EA_LAB_DATA__||{};
let selectedAccount=null,range='1M',workFilter='ALL',newsTab='EVENTS',knowledgeKind='ALL';
const main=document.getElementById('main'),drawerRoot=document.getElementById('drawerRoot'),toast=document.getElementById('toast');
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c==='\"'?'&quot;':'&#39;')}
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const fmt=(v,d=2)=>n(v)==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const short=v=>v?String(v).slice(0,8):'UNKNOWN';
const showDate=v=>{if(!v)return 'UNKNOWN';const x=new Date(v);return Number.isNaN(x.valueOf())?String(v):x.toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'})};
const status=v=>'<span class=\"status '+esc(v||'UNKNOWN')+'\">'+esc(v||'UNKNOWN')+'</span>';
const paths={
home:'M3 11 L12 4 L21 11 M5 10 L5 20 L10 20 L10 14 L14 14 L14 20 L19 20 L19 10',
work:'M4 7h16v12H4z M8 7V4h8v3',time:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 5v5l3 2',
chart:'M4 19V9m6 10V5m6 14v-7m4 7H2',news:'M5 5h14v14H5z M8 9h8M8 13h8M8 17h5',
brain:'M8 5 L6 8 L7 11 L5 14 L8 18 L12 20 M16 5 L18 8 L17 11 L19 14 L16 18 L12 20 M12 4 L12 20',
db:'M4 6c0-2 16-2 16 0s-16 2-16 0m0 0v6c0 2 16 2 16 0V6m-16 6v6c0 2 16 2 16 0v-6',
alert:'M12 4l8 15H4z M12 9v4m0 3v.1',sync:'M20 7v5h-5M4 17v-5h5 M18 10a7 7 0 0 0-12-3M6 14a7 7 0 0 0 12 3'};
const icon=name=>'<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"'+(paths[name]||paths.db)+'\"/></svg>';
const activeStates=new Set(['RUNNING','REVIEW','FROZEN','INTEGRATING']);
function route(){const r=(location.hash.slice(1).split('?')[0]||'overview');return ['overview','work','runtime','performance','news','knowledge','templates'].includes(r)?r:'overview'}
function setActiveNav(r){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r))}
function shellHead(title,subtitle,ico='home',back=false){
 const mon=DATA.monitoring||{},stamp=mon.generated_at_utc||DATA.observed_at;
 const badge=DATA.global_state||'UNKNOWN';
 return '<section class=\"shell-head\"><div><div class=\"breadcrumbs\"><a href=\"#overview\">Home</a> / '+esc(title)+'</div><div class=\"title-row\"><span class=\"title-icon\">'+icon(ico)+'</span><div><h1>'+esc(title)+'</h1><p class=\"subtitle\">'+esc(subtitle)+'</p></div></div></div><div class=\"head-actions\"><div class=\"timestamp\">Last data '+esc(showDate(stamp))+'<div class=\"health-line\"><span class=\"pulse\"></span> <span class=\"'+(badge==='DEGRADED_MONITORING'?'bad':'')+'\">'+esc(badge)+'</span></div></div>'+(back?'<a class=\"btn ghost\" href=\"#overview\">← Back to overview</a>':'')+'<button class=\"btn primary\" data-refresh>'+icon('sync')+' Refresh now</button></div></section>'}
function panel(title,body,action=''){return '<section class=\"panel\"><header class=\"panel-head\"><h2>'+esc(title)+'</h2>'+action+'</header><div class=\"panel-body\">'+body+'</div></section>'}
function kpi(label,value,sub,ico='db',kind=''){return '<article class=\"kpi '+kind+'\"><span class=\"kpi-icon\">'+icon(ico)+'</span><div><label>'+esc(label)+'</label><strong>'+esc(value)+'</strong><small>'+esc(sub)+'</small></div></article>'}
function freshWork(){return (DATA.work?.rows||[]).filter(r=>r.freshness==='CURRENT')}
function dataAge(){const t=new Date(DATA.monitoring?.generated_at_utc||DATA.observed_at||0);if(Number.isNaN(t.valueOf()))return 'UNKNOWN';const h=(Date.now()-t.valueOf())/36e5;if(h<0)return 'FUTURE';if(h<1)return Math.max(0,Math.round(h*60))+' min';return h.toFixed(1)+' h'}
function account(){const rows=DATA.accounts?.rows||[];if(!selectedAccount||!rows.some(a=>a.id===selectedAccount))selectedAccount=rows[0]?.id||null;return rows.find(a=>a.id===selectedAccount)||null}
function rangePoints(a){if(!a)return[];const pts=a.points||[];if(range==='ALL'||pts.length<2)return pts;const last=new Date(pts.at(-1).time).valueOf(),days={ '1D':1,'1W':7,'1M':31}[range]||31;return pts.filter(p=>last-new Date(p.time).valueOf()<=days*864e5)}
function chart(a,mini=false){const pts=rangePoints(a);if(!a||!pts.length)return '<div class=\"empty\">Balance / Equity history unavailable</div>';
 const W=mini?520:900,H=mini?220:300,pad={l:58,r:18,t:16,b:34},vals=pts.flatMap(p=>[n(p.balance),n(p.equity)]).filter(v=>v!=null),lo=Math.min(...vals),hi=Math.max(...vals),span=Math.max(1,hi-lo);
 const x=i=>pad.l+(W-pad.l-pad.r)*(pts.length===1?.5:i/(pts.length-1)),y=v=>pad.t+(H-pad.t-pad.b)*(1-(v-lo)/span),line=key=>pts.map((p,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(p[key]).toFixed(1)).join(' ');
 const grids=[0,.25,.5,.75,1].map(q=>{const yy=pad.t+(H-pad.t-pad.b)*q,v=hi-span*q;return '<line class=\"chart-grid\" x1=\"'+pad.l+'\" y1=\"'+yy+'\" x2=\"'+(W-pad.r)+'\" y2=\"'+yy+'\"/><text class=\"chart-axis\" x=\"4\" y=\"'+(yy+4)+'\">'+esc(fmt(v,0))+'</text>'}).join('');
 const first=pts[0],last=pts.at(-1);return '<div class=\"legend\"><span><i class=\"dot\"></i>Balance</span><span><i class=\"dot equity\"></i>Equity</span><span class=\"muted\">'+esc(a.currency)+' · '+pts.length+' observed samples</span></div><div class=\"chart-shell\"><svg class=\"chart-svg\" viewBox=\"0 0 '+W+' '+H+'\" preserveAspectRatio=\"none\" role=\"img\" aria-label=\"Observed balance and equity\"><defs><linearGradient id=\"areaFill\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"0\" stop-color=\"#16dac9\"/><stop offset=\"1\" stop-color=\"#16dac9\" stop-opacity=\"0\"/></linearGradient></defs>'+grids+'<path class=\"chart-line-balance\" d=\"'+line('balance')+'\"/><path class=\"chart-line-equity\" d=\"'+line('equity')+'\"/><text class=\"chart-axis\" x=\"'+pad.l+'\" y=\"'+(H-8)+'\">'+esc(first.time.slice(0,10))+'</text><text text-anchor=\"end\" class=\"chart-axis\" x=\"'+(W-pad.r)+'\" y=\"'+(H-8)+'\">'+esc(last.time.slice(0,10))+'</text></svg></div>'}
function metricStrip(a){if(!a)return'';const p=a.latest||{},float=n(p.equity)!=null&&n(p.balance)!=null?n(p.equity)-n(p.balance):null;return '<div class=\"metric-strip\">'+[['Balance',fmt(p.balance)+' '+a.currency],['Equity',fmt(p.equity)+' '+a.currency],['Floating',fmt(float)+' '+a.currency],['Samples',String(a.sample_count)]].map(x=>'<div class=\"metric\"><label>'+x[0]+'</label><strong>'+esc(x[1])+'</strong></div>').join('')+'</div>'}
function chartControls(){const accts=DATA.accounts?.rows||[];return '<div class=\"filters\"><div class=\"seg\">'+['1D','1W','1M','ALL'].map(x=>'<button data-range=\"'+x+'\" class=\"'+(x===range?'active':'')+'\">'+x+'</button>').join('')+'</div><select class=\"select\" data-account>'+accts.map(a=>'<option value=\"'+esc(a.id)+'\" '+(a.id===selectedAccount?'selected':'')+'>'+esc(a.label+' · '+a.currency)+'</option>').join('')+'</select></div>'}
function workTable(rows,limit=8){const view=rows.slice(0,limit);if(!view.length)return '<div class=\"empty\">No qualified unfinished lane observations</div>';return '<div class=\"table-wrap compact\"><table><thead><tr><th>Updated</th><th>Work / lane</th><th>Status</th></tr></thead><tbody>'+view.map(r=>'<tr data-work=\"'+esc(r.id)+'\"><td class=\"nowrap\">'+esc(r.updated_at?showDate(r.updated_at):'UNKNOWN')+'</td><td><button class=\"linkbtn row-title\" data-open-work=\"'+esc(r.id)+'\">'+esc(r.title)+'</button><span class=\"row-sub\">'+esc(r.worker||r.owner||'UNKNOWN')+'</span></td><td>'+status(r.display_state||r.state)+'</td></tr>').join('')+'</tbody></table></div>'}
function compactGraph(){const rows=freshWork().filter(r=>activeStates.has(r.state)||r.state==='WAITING'||r.state==='BLOCKED').slice(0,4);if(!rows.length)return '<div class=\"empty\">No current graph nodes. Registry history is not shown as live agents.</div>';return '<div class=\"graph\"><div class=\"graph-level\"><span class=\"graph-node\">Owner / CT</span></div><div class=\"graph-arrows\">↓</div><div class=\"graph-level\">'+rows.map(r=>'<button class=\"graph-node '+(r.state==='BLOCKED'?'warn':'')+'\" data-open-work=\"'+esc(r.id)+'\">'+esc(r.id.replace(/^ct-/,'').slice(0,26))+'<br>'+esc(r.state)+'</button>').join('')+'</div><div class=\"graph-arrows\">↓</div><div class=\"graph-level\"><span class=\"graph-node\">Existing evidence / jobs</span></div><p class=\"graph-caption\">Observation map only. A Registry lane is not process-health proof.</p></div>'}
function templateMini(){const rows=DATA.templates||[];if(!rows.length)return '<div class=\"empty\">Template source inventory unavailable</div>';return '<div class=\"mini-list\">'+rows.slice(0,6).map(t=>'<div class=\"mini-row\"><button class=\"linkbtn\" data-open-template=\"'+esc(t.id)+'\"><b>'+esc(t.id)+' '+esc(t.name)+'</b><small>'+esc(t.concept)+'</small></button>'+status(t.state)+'</div>').join('')+'</div><p><a class=\"linkbtn\" href=\"#templates\">View all '+rows.length+' source wrappers →</a></p>'}
function macroMini(){const m=DATA.macro||{};const bars=m.barometers||[];return '<div class=\"mini-list\"><div class=\"mini-row\"><div><b>MRIS observed regime</b><small>'+esc(m.time||'UNKNOWN')+' · '+esc(m.freshness||'UNKNOWN')+'</small></div>'+status(m.state||'UNKNOWN')+'</div>'+bars.slice(0,5).map(b=>'<div class=\"mini-row\"><div><b>'+esc(b.symbol)+'</b><small>'+esc(b.reason||'')+'</small></div><span>'+esc(fmt(b.chg5d_pct,2))+'%</span></div>').join('')+'</div><div class=\"notice\">EA effective MacroGate state: '+esc(m.effective||'UNKNOWN')+'. Historical macro observation is not a live trading-policy claim.</div>'}
function knowledgeMini(){const k=DATA.knowledge||{},h=k.health||{};return '<div class=\"tag-row\"><span class=\"tag\">Canonical docs '+esc(h.canonical_documents??'—')+'</span><span class=\"tag\">Research cards '+esc(h.research_cards??'—')+'</span><span class=\"tag\">Drafts '+esc(h.draft_documents??'—')+'</span></div><div class=\"mini-list\"><div class=\"mini-row\"><div><b>1 · Search</b><small>EA, mechanism, source or problem</small></div></div><div class=\"mini-row\"><div><b>2 · Check authority</b><small>Source claim / inference / draft remain separate</small></div></div><div class=\"mini-row\"><div><b>3 · Use evidence</b><small>Open the exact card/source before proposing a test</small></div></div></div>'}
function overview(){const fw=freshWork(),active=fw.filter(r=>activeStates.has(r.state)),review=fw.filter(r=>r.state==='REVIEW'||r.state==='FROZEN'),a=account(),alerts=(DATA.alerts||[]).filter(x=>x.state==='OPEN');
 const kpis='<div class=\"grid kpis\">'+kpi('Active lanes',String(active.length),'qualified Registry observations','work')+kpi('Review waiting',String(review.length),'REVIEW / FROZEN','time','warn')+kpi('Observed accounts',String((DATA.accounts?.rows||[]).length),'account snapshots; not Live-EA count','db')+kpi('Open monitor findings',String(alerts.length),'SafeProjection findings','alert','danger')+kpi('Data observation age',dataAge(),DATA.monitoring?.status||'UNKNOWN','db')+'</div>';
 const work=panel('Work in chats now',workTable(fw.filter(r=>r.state!=='DONE'),6),'<a href=\"#work\">View all →</a>');
 const graph=panel('Agent Graph / system flow',compactGraph(),'<a href=\"#work\">View detail →</a>');
 const perfBody=chartControls()+chart(a,true)+metricStrip(a);const perf=panel('EA Account Performance',perfBody,'<a href=\"#performance\">Open details →</a>');
 const templates=panel('EA Template Inventory',templateMini(),'<a href=\"#templates\">Open →</a>');
 const guards=panel('NewsGuard & MacroGate',macroMini(),'<a href=\"#news\">Open →</a>');
 const knowledge=panel('Second Brain / Knowledge Base',knowledgeMini(),'<a href=\"#knowledge\">Open →</a>');
 const accord='<div class=\"accordions\"><details><summary>Read me — ภาพรวมและขอบเขต</summary><div class=\"details-body\">Read-only owner view. Missing evidence stays UNKNOWN. Dashboard presentation does not grant runtime, trading, risk/default or promotion authority.</div></details><details><summary>Method / Notes</summary><div class=\"details-body\">Git owns canonical project state; Registry owns lane declarations; durable job/result bytes own execution lifecycle; accepted evidence owns acceptance. These layers are not collapsed into one green status.</div></details><details><summary>Data source details</summary><div class=\"details-body\">Canonical '+esc(short(DATA.canonical_sha))+' · published binding '+esc(DATA.published_binding||'UNKNOWN')+' · snapshot files '+esc(DATA.accounts?.files_read??0)+' · Knowledge '+esc(DATA.knowledge?.binding||'UNKNOWN')+'.</div></details></div>';
 main.innerHTML=shellHead('EA_LAB Monitor','Live view of research, execution and system health — read only','home')+kpis+'<div class=\"grid overview-main\">'+work+graph+perf+'</div><div class=\"grid overview-second\">'+templates+guards+knowledge+'</div>'+accord;bindCommon()}
function drawer(title,body){drawerRoot.innerHTML='<div class=\"drawer-backdrop\" data-close-drawer><aside class=\"drawer\" role=\"dialog\" aria-modal=\"true\" aria-label=\"'+esc(title)+'\"><div class=\"drawer-head\"><h2>'+esc(title)+'</h2><button class=\"close\" data-close-drawer aria-label=\"Close\">×</button></div>'+body+'</aside></div>';drawerRoot.querySelector('.drawer').addEventListener('click',e=>e.stopPropagation());drawerRoot.querySelectorAll('[data-close-drawer]').forEach(x=>x.addEventListener('click',()=>drawerRoot.innerHTML=''))}
function openWork(id){const r=(DATA.work?.rows||[]).find(x=>x.id===id);if(!r)return;const pairs=[['Registry state',r.state],['Display state',r.display_state],['Freshness',r.freshness],['Updated',r.updated_at],['Worker',r.worker],['Owner chat',r.owner],['Durable job',r.job_id||'NOT OBSERVED'],['Job state',r.job_state],['Process state',r.process_state],['Progress',r.progress],['Blocker',r.blocker||'—'],['Head',r.head||'UNKNOWN'],['Reviewed head',r.reviewed_head||'UNKNOWN'],['Reviewer',r.reviewer||'UNKNOWN'],['Dependencies',(r.dependencies||[]).join(', ')||'None declared']];drawer(r.title,'<dl class=\"kv\">'+pairs.map(([k,v])=>'<dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><div class=\"notice\">This is an observation of existing lane/job evidence. It has no retry, kill, launch or push action.</div>')}
function workPage(){const rows=(DATA.work?.rows||[]),states=['ALL','RUNNING','REVIEW','BLOCKED','WAITING','PAUSED','FROZEN','INTEGRATING','TERMINAL_RECONCILE'];const filtered=rows.filter(r=>workFilter==='ALL'||r.state===workFilter||r.display_state===workFilter);const current=rows.filter(r=>r.freshness==='CURRENT'&&r.state!=='DONE');
 const controls='<div class=\"search-row\"><div class=\"tag-row\">'+states.map(s=>'<button class=\"tag '+(workFilter===s?'active':'')+'\" data-work-filter=\"'+s+'\">'+s+'</button>').join('')+'</div></div>';
 const body=controls+'<div class=\"notice\">Mapped work only: chats without a durable lane/job identity are not observable here. Current unfinished qualified observations: '+current.length+'. Registry history is not counted as concurrent agents.</div>'+workTable(filtered,100);
 const side=panel('How to read status','<div class=\"mini-list\"><div class=\"mini-row\"><div><b>Registry</b><small>Who owns a lane / declared stage</small></div></div><div class=\"mini-row\"><div><b>Durable job</b><small>Runner result, not deliverable acceptance</small></div></div><div class=\"mini-row\"><div><b>Review</b><small>Exact reviewed head required where applicable</small></div></div><div class=\"mini-row\"><div><b>Canonical</b><small>Origin/master remains source of truth</small></div></div></div>');
 main.innerHTML=shellHead('Work','Current lanes, durable jobs and review state — without guessing chat UI liveness','work',true)+'<div class=\"page-grid\"><div class=\"section-stack\">'+panel('Mapped work',body)+panel('Agent Graph',compactGraph())+'</div><aside class=\"sidebar\">'+side+'</aside></div>';bindCommon()}
function observedDD(a){const pts=a?.points||[];let peak=null,worst=null;for(const p of pts){const e=n(p.equity);if(e==null)continue;peak=peak==null?e:Math.max(peak,e);const dd=peak?100*(e-peak)/peak:null;if(dd!=null&&(worst==null||dd<worst))worst=dd}return worst}
function latestEA(a){return Array.isArray(a?.latest?.eas)?a.latest.eas:[]}
function eaLiveTable(a){const rows=latestEA(a);if(!rows.length)return '<div class=\"empty\">No per-magic rows in latest account snapshot</div>';return '<div class=\"table-wrap\"><table><thead><tr><th>EA / deployment mapping</th><th>Symbol</th><th>Inventory</th><th>Floating</th><th>Open lots</th><th>Positions</th><th>Identity</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><b>'+esc(r.name)+'</b></td><td>'+esc(r.symbol||'—')+'</td><td>'+status(r.inventory_state)+'</td><td>'+esc(fmt(r.floating))+'</td><td>'+esc(fmt(r.lots))+'</td><td>'+esc(fmt(r.positions,0))+'</td><td>'+status(r.identity)+'</td></tr>').join('')+'</tbody></table></div>'}
function lotsBySymbol(a){const map={};for(const r of latestEA(a)){if(!r.symbol||n(r.lots)==null)continue;map[r.symbol]=(map[r.symbol]||0)+n(r.lots)}const rows=Object.entries(map).sort((x,y)=>y[1]-x[1]),max=Math.max(1,...rows.map(x=>x[1]));if(!rows.length)return '<div class=\"empty\">No current lot observations</div>';return '<div class=\"exposure-list\">'+rows.map(x=>'<div class=\"bar-row\"><b>'+esc(x[0])+'</b><div class=\"bar-track\"><div class=\"bar-fill\" data-width=\"'+esc((100*x[1]/max).toFixed(1))+'\"></div></div><span>'+esc(fmt(x[1]))+'</span></div>').join('')+'</div><div class=\"notice\">Raw open lots by symbol are observational only; they are not normalized economic exposure.</div>'}
function performancePage(){const a=account(),p=a?.latest||{},eas=latestEA(a);let floating=null;if(eas.length&&eas.every(x=>n(x.floating)!=null))floating=eas.reduce((s,x)=>s+n(x.floating),0);const dd=observedDD(a);
 const values=[['Balance',fmt(p.balance)+' '+(a?.currency||'')],['Equity',fmt(p.equity)+' '+(a?.currency||'')],['MAGIC float sum',fmt(floating)+' '+(a?.currency||'')],['Observed sample DD',dd==null?'UNAVAILABLE':fmt(dd,2)+'%'],['Samples',String(a?.sample_count??0)],['Clock',a?.clock||'UNKNOWN']];
 const summary='<div class=\"summary-grid\">'+values.map(x=>'<div class=\"summary-box\"><label>'+esc(x[0])+'</label><strong>'+esc(x[1])+'</strong></div>').join('')+'</div><div class=\"notice\">No deposit/withdrawal adjustment and no per-EA realized attribution is claimed. Lines connect observed account snapshots only.</div>';
 const top='<div class=\"grid performance-top\">'+panel('Balance vs Equity',chartControls()+chart(a)+metricStrip(a))+panel('Performance Summary',summary)+'</div>';
 const lower='<div class=\"grid performance-lower\">'+panel('Observed EA / deployment rows',eaLiveTable(a),'<span class=\"source-pill\">latest account snapshot</span>')+panel('Open lots by symbol',lotsBySymbol(a))+'</div>';
 main.innerHTML=shellHead('EA Performance / Live Tracking','Observed account balance, equity and current deployment rows — no invented profitability','chart',true)+top+lower;bindCommon()}
function runtimePage(){const m=DATA.monitoring||{},sources=m.sources||[],accounts=DATA.accounts?.rows||[];
 const sourceRows=sources.length?'<div class="mini-list">'+sources.map(s=>'<div class="mini-row"><div><b>'+esc(s.name)+'</b><small>'+esc(s.timestamp_basis||'')+' · '+esc(s.observed_at_utc||'UNKNOWN')+'</small></div>'+status(s.state||'UNKNOWN')+'</div>').join('')+'</div>':'<div class="empty">No monitoring-source detail supplied</div>';
 const accountRows=accounts.length?'<div class="mini-list">'+accounts.map(a=>'<div class="mini-row"><div><b>'+esc(a.label+' · '+a.currency)+'</b><small>'+esc(a.environment)+' · '+a.sample_count+' samples · clock '+esc(a.clock)+'</small></div>'+status(a.freshness)+'</div>').join('')+'</div>':'<div class="empty">No account snapshots</div>';
 const disks=(DATA.disks||[]).map(x=>'<div class="summary-box"><label>'+esc(x.drive)+' free</label><strong>'+esc(fmt(x.free_gb,1))+' GB</strong><small>'+esc(fmt(x.total_gb,1))+' GB total</small></div>').join('');
 const identity='<dl class="kv"><dt>Canonical</dt><dd>'+esc(DATA.canonical_sha)+'</dd><dt>Published pin</dt><dd>'+esc(DATA.published?.canonical_sha||'UNKNOWN')+'</dd><dt>Binding</dt><dd>'+status(DATA.published_binding)+'</dd><dt>Runtime repo head</dt><dd>'+esc(m.repo_head||'UNKNOWN')+'</dd><dt>Monitor status</dt><dd>'+status(m.status||m.reported_status||'UNKNOWN')+'</dd></dl>';
 const errors=(DATA.errors||[]).map(e=>'<div class="source-error">'+esc(e.source)+' — '+esc(e.reason)+'</div>').join('')||'<div class="good">No reader errors in this view refresh.</div>';
 main.innerHTML=shellHead('Runtime','Monitor source binding, account observations and local system health','time',true)+'<div class="page-grid"><div class="section-stack">'+panel('Monitoring provenance',identity)+panel('Control Room provenance',controlRoomProvenance())+panel('Source freshness',sourceRows)+panel('Observed account snapshot streams',accountRows)+'</div><aside class="sidebar">'+panel('Disk observation','<div class="summary-grid">'+disks+'</div>')+panel('Reader errors',errors)+panel('Limits','<p class="muted">'+esc((DATA.limits||[]).join(' · '))+'</p>')+'</aside></div>';bindCommon()}
function templatesPage(){const rows=DATA.templates||[];
 const table=rows.length?'<div class="table-wrap"><table><thead><tr><th>ID</th><th>Template source</th><th>Concept from source</th><th>Source state</th><th>Runtime</th></tr></thead><tbody>'+rows.map(t=>'<tr><td><b>'+esc(t.id)+'</b></td><td><button class="linkbtn row-title" data-open-template="'+esc(t.id)+'">'+esc(t.name)+'</button><span class="row-sub">'+esc(t.path)+'</span></td><td>'+esc(t.concept)+'</td><td>'+status(t.state)+'</td><td>'+status(t.runtime)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No canonical template wrappers found</div>';
 main.innerHTML=shellHead('EA Template Inventory','What exists in the canonical EA Template source — separate from research, deployment and profitability','db',true)+panel('Canonical source wrappers',table)+'<div class="accordions"><details><summary>What SOURCE_PRESENT means</summary><div class="details-body">A wrapper exists in canonical source and is bound to its Git hash. It does not mean backtest passed, runtime is attached, or the EA is profitable.</div></details><details><summary>Research is separate</summary><div class="details-body">Open EA Performance / reports for source-bound research evidence. No global grade is invented from source presence.</div></details><details><summary>Future additions</summary><div class="details-body">New canonical wrappers automatically appear after the local Monitor reads a newer origin/master. No second catalog is created here.</div></details></div>';bindCommon()}
function openTemplate(id){const t=(DATA.templates||[]).find(x=>x.id===id);if(!t)return;drawer(t.id+' · '+t.name,'<p>'+esc(t.concept)+'</p><dl class="kv"><dt>Source</dt><dd>'+esc(t.path)+'</dd><dt>SHA256</dt><dd>'+esc(t.sha256)+'</dd><dt>Canonical</dt><dd>'+esc(t.canonical_sha)+'</dd><dt>Runtime</dt><dd>'+esc(t.runtime)+'</dd><dt>Research</dt><dd>'+esc(t.research)+'</dd></dl>')}
let knowledgeQuery='';
function newsPage(){const events=DATA.news?.events||[],m=DATA.macro||{},now=Date.now();
 const next=events.find(e=>new Date(e.time).valueOf()>=now);
 const eventRows=events.length?'<div class="table-wrap"><table><thead><tr><th>Bangkok time</th><th>Currency</th><th>Event</th><th>Forecast</th><th>Previous</th><th>NewsGuard window</th></tr></thead><tbody>'+events.map(e=>'<tr><td>'+esc(showDate(e.time))+'</td><td><b>'+esc(e.currency)+'</b></td><td>'+esc(e.title)+'</td><td>'+esc(e.forecast||'—')+'</td><td>'+esc(e.previous||'—')+'</td><td>'+status(e.guard_window)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No current calendar rows in the existing DailyMonitor source</div>';
 const bars=m.barometers||[];
 const macroRows=bars.length?'<div class="cards">'+bars.map(b=>'<article class="card"><span class="source-pill">MRIS observation</span><h3>'+esc(b.symbol)+'</h3><p>Spot '+esc(fmt(b.spot))+' · 5d '+esc(fmt(b.chg5d_pct,2))+'% · signal '+esc(fmt(b.signal,1))+'</p><p>'+esc(b.reason||'')+'</p></article>').join('')+'</div>':'<div class="empty">No MRIS barometer observations</div>';
 const tabs='<div class="tag-row"><button class="tag '+(newsTab==='EVENTS'?'active':'')+'" data-news-tab="EVENTS">Economic calendar</button><button class="tag '+(newsTab==='MACRO'?'active':'')+'" data-news-tab="MACRO">Macro regime</button></div>';
 const np=DATA.news_policy||{},ref=(np.pre_news_min!=null&&np.post_news_min!=null)?('Reference window −'+fmt(np.pre_news_min,0)+' / +'+fmt(np.post_news_min,0)+' min'):'Reference window unavailable';
 const eventPanel=tabs+'<div class="summary-grid"><div class="summary-box"><label>Canonical NewsGuard runbook</label><strong>'+esc(ref)+'</strong><small>'+esc(np.reference_date||'UNKNOWN')+' · '+esc(np.coverage_state||'UNKNOWN')+'</small></div><div class="summary-box"><label>Effective live guard state</label><strong>'+esc(np.effective_runtime||DATA.news?.guard_effective||'UNKNOWN')+'</strong><small>Attach/log evidence required</small></div></div><div class="notice">Calendar rows do not carry an authoritative impact grade. The −pre/+post values are a dated canonical runbook reference only; this UI does not claim the live terminal is currently applying them.</div>'+(next?'<p><b>Next observed calendar row:</b> '+esc(showDate(next.time))+' · '+esc(next.currency)+' · '+esc(next.title)+'</p>':'')+eventRows;
 const macroPanel=tabs+'<div class="summary-grid"><div class="summary-box"><label>MRIS state</label><strong>'+esc(m.state||'UNKNOWN')+'</strong><small>'+esc(m.time||'UNKNOWN')+'</small></div><div class="summary-box"><label>Freshness</label><strong>'+esc(m.freshness||'UNKNOWN')+'</strong><small>EA-effective MacroGate: '+esc(m.effective||'UNKNOWN')+'</small></div></div><div class="notice">'+esc(m.source||'Historical MRIS observation')+'. The Monitor does not infer country/pair regimes beyond qualified producer output.</div>'+macroRows;
 main.innerHTML=shellHead('News & Macro','Economic calendar and existing MRIS/MacroGate observations — source age and applicability stay visible','news',true)+panel(newsTab==='EVENTS'?'NewsGuard schedule / economic calendar':'MacroGate / MRIS overview',newsTab==='EVENTS'?eventPanel:macroPanel);
 bindCommon();
}
function knowledgeMatches(){const docs=DATA.knowledge?.documents||[],q=knowledgeQuery.trim().toLowerCase();return docs.filter(d=>(knowledgeKind==='ALL'||d.kind===knowledgeKind)&&(!q||[d.title,d.body,(d.topics||[]).join(' '),(d.sources||[]).join(' ')].join(' ').toLowerCase().includes(q)))}
function knowledgePage(){const docs=DATA.knowledge?.documents||[],kinds=['ALL',...new Set(docs.map(d=>d.kind).filter(Boolean))].slice(0,10),rows=knowledgeMatches();
 const controls='<div class="search-row"><input class="input" data-knowledge-search placeholder="Search knowledge, EA, mechanism, risk..." value="'+esc(knowledgeQuery)+'"><div class="tag-row">'+kinds.map(k=>'<button class="tag '+(knowledgeKind===k?'active':'')+'" data-knowledge-kind="'+esc(k)+'">'+esc(k)+'</button>').join('')+'</div></div>';
 const cards=rows.slice(0,24).map(d=>'<article class="card"><span class="source-pill '+(d.authority==='DRAFT_NOT_IMPORTED'?'bad':'')+'">'+esc(d.authority)+'</span><h3>'+esc(d.title)+'</h3><p>'+esc((d.body||'').replace(/\s+/g,' ').slice(0,260))+'</p><footer>'+esc(d.kind)+' · '+esc(short(d.sha256))+'</footer><button class="btn small" data-open-knowledge="'+esc(d.id)+'">Read summary / source</button></article>').join('');
 const h=DATA.knowledge?.health||{};
 const health='<div class="summary-grid"><div class="summary-box"><label>Canonical docs</label><strong>'+esc(h.canonical_documents??'—')+'</strong></div><div class="summary-box"><label>Research cards</label><strong>'+esc(h.research_cards??'—')+'</strong></div><div class="summary-box"><label>Draft docs</label><strong>'+esc(h.draft_documents??'—')+'</strong></div><div class="summary-box"><label>Binding</label><strong style="font-size:13px">'+esc(DATA.knowledge?.binding||'UNKNOWN')+'</strong></div></div>';
 const guide='<div class="mini-list"><div class="mini-row"><div><b>1 Search</b><small>Problem, EA, mechanism, source ID</small></div></div><div class="mini-row"><div><b>2 Check authority</b><small>Canonical vs draft vs inference</small></div></div><div class="mini-row"><div><b>3 Check negative knowledge</b><small>Avoid repeating closed/falsified paths</small></div></div><div class="mini-row"><div><b>4 Build a bounded question</b><small>Knowledge alone grants no experiment authority</small></div></div></div>';
 main.innerHTML=shellHead('Second Brain','Search the accepted reader while keeping source claims, inference and drafts separate','brain',true)+'<div class="page-grid"><div class="section-stack">'+panel('Knowledge search',controls+'<p class="muted">'+rows.length+' matching document(s)</p><div class="cards">'+cards+'</div>')+'</div><aside class="sidebar">'+panel('Library health',health)+panel('How to use',guide)+'</aside></div>';
 bindCommon();
}
function openKnowledge(id){const d=(DATA.knowledge?.documents||[]).find(x=>x.id===id);if(!d)return;drawer(d.title,'<p><span class="source-pill '+(d.authority==='DRAFT_NOT_IMPORTED'?'bad':'')+'">'+esc(d.authority)+'</span> '+esc(d.kind)+'</p><div class="prose">'+esc((d.body||'').slice(0,12000))+'</div><hr><dl class="kv"><dt>Document ID</dt><dd>'+esc(d.id)+'</dd><dt>SHA256</dt><dd>'+esc(d.sha256)+'</dd><dt>Sources</dt><dd>'+esc((d.sources||[]).join(', ')||'None listed')+'</dd></dl>')}
function livePerfFlag(row){
 const m={'st-red':'DD BREACH','st-yellow':'DD WARN','st-green':'BELOW WARN','st-white':'NO CLOSED DATA','st-grey':'UNMAPPED','st-nobase':'DD UNKNOWN','st-blue':'DD UNKNOWN'};
 return m[row.flag_class]||'OBSERVED';
}
function livePerformanceTable(a){
 const lp=DATA.live_performance||{},acct=(lp.accounts||[]).find(x=>a&&x.account_id===a.id);
 const banner='<div class="notice">Existing LIVE_DASHBOARD producer · source '+(lp.source_fresh?'FRESH':'NOT FRESH')+' · binding '+esc(lp.binding||'UNKNOWN')+'. Net P/L = profit + swap + commission under the producer analysis window. PF/DD are not recomputed by this UI.</div>';
 if(!acct)return banner+'<div class="empty">No source-bound live performance card for this selected account</div>';
 const rows=acct.rows||[]; if(!rows.length)return banner+'<div class="empty">No performance rows in producer output</div>';
 return banner+'<div class="summary-grid"><div class="summary-box"><label>Producer account net</label><strong class="'+(n(acct.account_net_pl)<0?'num-neg':n(acct.account_net_pl)>0?'num-pos':'')+'">'+esc(fmt(acct.account_net_pl))+' '+esc(acct.currency)+'</strong><small>window '+esc(acct.window_start)+'</small></div><div class="summary-box"><label>Closed deal rows</label><strong>'+esc(acct.account_trades??'UNKNOWN')+'</strong><small>'+esc(acct.account_label)+' · producer aggregate</small></div></div><div class="table-wrap"><table><thead><tr><th>EA / magic</th><th>Trades</th><th>Net P/L</th><th>PF</th><th>Max DD</th><th>Kill DD</th><th>Risk flag</th><th>Idle d</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><button class="linkbtn row-title" data-open-liveperf="'+esc(acct.account_id)+'|'+esc(r.magic)+'">'+esc(r.ea)+'</button><span class="row-sub">'+esc(r.symbol)+' · '+esc(r.magic)+' · '+esc(r.operational)+'</span></td><td>'+esc(r.trades)+'</td><td class="'+(n(r.net_pl)<0?'num-neg':n(r.net_pl)>0?'num-pos':'')+'">'+esc(fmt(r.net_pl))+'</td><td>'+esc(r.profit_factor==='INFINITY'?'∞':fmt(r.profit_factor,2))+'</td><td>'+esc(r.max_dd_pct==null?'UNKNOWN':fmt(r.max_dd_pct,2)+'%')+'</td><td>'+esc(r.kill_dd_pct==null?'—':fmt(r.kill_dd_pct,2)+'%')+'</td><td>'+status(livePerfFlag(r))+'</td><td>'+esc(r.days_idle==null?'—':fmt(r.days_idle,0))+'</td></tr>').join('')+'</tbody></table></div>';
}
function openLivePerformance(key){
 const [accountId,magic]=key.split('|'),acct=(DATA.live_performance?.accounts||[]).find(x=>x.account_id===accountId),r=acct?.rows?.find(x=>x.magic===magic); if(!acct||!r)return;
 drawer(r.ea,'<p>'+status(livePerfFlag(r))+' <span class="source-pill">LIVE_DASHBOARD producer</span></p><dl class="kv"><dt>Account</dt><dd>'+esc(acct.account_label+' · '+acct.currency)+'</dd><dt>Magic</dt><dd>'+esc(r.magic)+'</dd><dt>Symbol</dt><dd>'+esc(r.symbol)+'</dd><dt>Closed deal rows</dt><dd>'+esc(r.trades)+'</dd><dt>Net P/L</dt><dd>'+esc(fmt(r.net_pl)+' '+acct.currency)+'</dd><dt>Profit factor</dt><dd>'+esc(r.profit_factor==='INFINITY'?'∞':fmt(r.profit_factor,2))+'</dd><dt>Max DD</dt><dd>'+esc(r.max_dd_pct==null?'UNKNOWN':fmt(r.max_dd_pct,2)+'%')+'</dd><dt>Kill DD reference</dt><dd>'+esc(r.kill_dd_pct==null?'UNKNOWN':fmt(r.kill_dd_pct,2)+'%')+'</dd><dt>Verification</dt><dd>'+esc(r.verification)+'</dd><dt>Detail</dt><dd>'+esc(r.detail)+'</dd></dl><div class="notice">'+esc(DATA.live_performance?.basis||'')+'</div>');
}
function controlRoomTable(a){
 const cr=DATA.control_room||{},rows=(cr.rows||[]).filter(r=>!a||r.account_id===a.id);
 const banner='<div class="notice">Control Room source '+esc(cr.freshness||'UNKNOWN')+' · binding '+esc(cr.binding||'UNKNOWN')+' · reconciliation '+(cr.reconciliation_clear?'CLEAR':'NOT CLEAR')+'. Closed-deal rows and rates are observations from the existing producer, not a universal EA grade.</div>';
 if(!rows.length)return banner+'<div class="empty">No Control Room deployment row for this selected account</div>';
 return banner+'<div class="table-wrap"><table><thead><tr><th>EA / magic</th><th>Closed rows</th><th>Obs / exp trades wk</th><th>Readiness</th><th>Float</th><th>Open</th><th>Verification</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><b>'+esc(r.ea)+'</b><span class="row-sub">'+esc(r.symbol)+' · '+esc(r.magic)+'</span></td><td>'+esc(r.closed_deal_rows??'UNKNOWN')+'</td><td>'+esc(fmt(r.observed_trades_per_week,2))+' / '+esc(fmt(r.expected_trades_per_week,2))+'<span class="row-sub">'+esc(r.rate_flag||'')+'</span></td><td>'+status(r.readiness||'UNKNOWN')+'<span class="row-sub">'+esc(r.forecast||'')+'</span></td><td>'+esc(fmt(r.floating_pl))+'</td><td>'+esc(fmt(r.open_positions,0))+'</td><td>'+status(r.verification_state||'UNKNOWN')+'</td></tr>').join('')+'</tbody></table></div>'
}
function controlRoomProvenance(){
 const cr=DATA.control_room||{},rid=cr.runtime_identity||{},reasons=(cr.verdict_reasons||[]).slice(0,6);
 return '<dl class="kv"><dt>Generated</dt><dd>'+esc(showDate(cr.generated_at))+'</dd><dt>Freshness</dt><dd>'+esc(cr.freshness||'UNKNOWN')+'</dd><dt>Producer Git head</dt><dd>'+esc(cr.git_head||'UNKNOWN')+'</dd><dt>Canonical binding</dt><dd>'+status(cr.binding||'UNKNOWN')+'</dd><dt>Execution context</dt><dd>'+esc(cr.execution_context||'UNKNOWN')+'</dd><dt>Reconciliation</dt><dd>'+esc(cr.reconciliation_clear?'CLEAR':'NOT CLEAR')+'</dd><dt>Runtime identity</dt><dd>'+esc(rid.state||'UNKNOWN')+' / '+esc(rid.forward_test_state||'UNKNOWN')+'</dd></dl>'+(reasons.length?'<div class="notice">'+reasons.map(x=>esc(x.code)+': '+esc(x.detail)).join(' · ')+'</div>':'')
}
function researchTable(){const rows=DATA.research||[];if(!rows.length)return '<div class="empty">No source-bound research records in published Monitor</div>';
 return '<div class="table-wrap"><table><thead><tr><th>EA / evidence record</th><th>Home</th><th>Model</th><th>MAIN PF</th><th>BWD PF</th><th>MAIN DD</th><th>BWD DD</th><th>Status</th></tr></thead><tbody>'+rows.map(r=>{const e=r.evidence||{},m=e.main||{},b=e.bwd||{},home=r.home||{};return '<tr><td><button class="linkbtn row-title" data-open-research="'+esc(r.id)+'">'+esc(r.name)+'</button><span class="row-sub">'+esc(r.family)+' · '+esc(r.verdict||'UNKNOWN')+'</span></td><td>'+esc((home.symbol||'UNKNOWN')+'/'+(home.timeframe||'UNKNOWN'))+'</td><td>'+esc(e.model||'UNKNOWN')+'</td><td>'+esc(m.pf??'UNKNOWN')+'</td><td>'+esc(b.pf??'UNKNOWN')+'</td><td>'+esc(m.dd_pct??'UNKNOWN')+'</td><td>'+esc(b.dd_pct??'UNKNOWN')+'</td><td>'+status(r.status)+'</td></tr>'}).join('')+'</tbody></table></div>'}
function openResearch(id){const r=(DATA.research||[]).find(x=>x.id===id);if(!r)return;const e=r.evidence||{},graphs=r.native_graphs||{};let imgs='';for(const role of ['main','bwd']){const g=graphs[role];if(g?.state==='AVAILABLE'&&g.asset_sha256)imgs+='<p><b>'+role.toUpperCase()+' graph</b></p><img loading="lazy" style="max-width:100%;border:1px solid #23475d;border-radius:6px" src="/asset/'+esc(g.asset_sha256)+'" alt="'+role+' native graph">'}drawer(r.name,'<p>'+status(r.status)+' <span class="source-pill">'+esc(r.family)+'</span></p><dl class="kv"><dt>Strategy</dt><dd>'+esc(r.strategy||'UNKNOWN')+'</dd><dt>Home</dt><dd>'+esc((r.home?.symbol||'UNKNOWN')+'/'+(r.home?.timeframe||'UNKNOWN'))+'</dd><dt>Model</dt><dd>'+esc(e.model||'UNKNOWN')+'</dd><dt>Report stage</dt><dd>'+esc(e.report_stage||'UNKNOWN')+'</dd><dt>Verdict</dt><dd>'+esc(r.verdict||'UNKNOWN')+'</dd><dt>Holdout</dt><dd>'+esc(e.holdout_state||'UNKNOWN')+'</dd></dl>'+imgs+'<div class="notice">Research evidence is separate from live deployment performance and does not imply Candidate/LIVE authority.</div>')}
function performancePageV2(){const a=account(),p=a?.latest||{},eas=latestEA(a);let floating=null;if(eas.length&&eas.every(x=>n(x.floating)!=null))floating=eas.reduce((s,x)=>s+n(x.floating),0);const dd=observedDD(a);
 const values=[['Balance',fmt(p.balance)+' '+(a?.currency||'')],['Equity',fmt(p.equity)+' '+(a?.currency||'')],['MAGIC float sum',fmt(floating)+' '+(a?.currency||'')],['Observed sample DD',dd==null?'UNAVAILABLE':fmt(dd,2)+'%'],['Samples',String(a?.sample_count??0)],['Clock',a?.clock||'UNKNOWN']];
 const summary='<div class="summary-grid">'+values.map(x=>'<div class="summary-box"><label>'+esc(x[0])+'</label><strong>'+esc(x[1])+'</strong></div>').join('')+'</div><div class="notice">No deposit/withdrawal adjustment and no per-EA realized attribution is claimed. Lines connect observed account snapshots only.</div>';
 const top='<div class="grid performance-top">'+panel('Balance vs Equity',chartControls()+chart(a)+metricStrip(a))+panel('Performance Summary',summary)+'</div>';
 const live='<div class="grid performance-lower">'+panel('Observed EA / deployment rows',eaLiveTable(a),'<span class="source-pill">latest account snapshot</span>')+panel('Open lots by symbol',lotsBySymbol(a))+'</div>';
 const realized=panel('Source-bound live performance',livePerformanceTable(a),'<span class="source-pill">existing LIVE_DASHBOARD producer</span>');
 const readiness=panel('Forward / live decision readiness',controlRoomTable(a),'<span class="source-pill">existing Control Room producer</span>');
 main.innerHTML=shellHead('EA Performance / Live Tracking','Observed account equity, source-bound EA performance, deployment readiness and separate research evidence','chart',true)+top+live+realized+readiness+panel('Research evidence / MAIN-BWD',researchTable(),'<span class="source-pill">separate from live</span>');
 bindCommon();
}
function toastMsg(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toast.classList.remove('show'),2400)}
async function refreshData(){if(location.protocol==='file:'){toastMsg('Offline snapshot — open with OPEN_MONITOR.cmd for live local reread.');return}try{const r=await fetch('/api/snapshot?refresh=1',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);DATA=await r.json();toastMsg('Read-only local evidence refreshed');renderRoute()}catch(e){toastMsg('Refresh unavailable: '+e.message)}}
function bindCommon(){
 document.querySelectorAll('[data-refresh]').forEach(b=>b.addEventListener('click',refreshData));
 document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>{range=b.dataset.range;renderRoute()}));
 document.querySelectorAll('[data-account]').forEach(s=>s.addEventListener('change',()=>{selectedAccount=s.value;renderRoute()}));
 document.querySelectorAll('[data-open-work]').forEach(b=>b.addEventListener('click',()=>openWork(b.dataset.openWork)));
 document.querySelectorAll('[data-open-template]').forEach(b=>b.addEventListener('click',()=>openTemplate(b.dataset.openTemplate)));
 document.querySelectorAll('[data-open-research]').forEach(b=>b.addEventListener('click',()=>openResearch(b.dataset.openResearch)));
 document.querySelectorAll('[data-open-liveperf]').forEach(b=>b.addEventListener('click',()=>openLivePerformance(b.dataset.openLiveperf)));
 document.querySelectorAll('[data-open-knowledge]').forEach(b=>b.addEventListener('click',()=>openKnowledge(b.dataset.openKnowledge)));
 document.querySelectorAll('[data-work-filter]').forEach(b=>b.addEventListener('click',()=>{workFilter=b.dataset.workFilter;workPage()}));
 document.querySelectorAll('[data-news-tab]').forEach(b=>b.addEventListener('click',()=>{newsTab=b.dataset.newsTab;newsPage()}));
 document.querySelectorAll('[data-knowledge-kind]').forEach(b=>b.addEventListener('click',()=>{knowledgeKind=b.dataset.knowledgeKind;knowledgePage()}));
 const q=document.querySelector('[data-knowledge-search]');if(q)q.addEventListener('input',()=>{knowledgeQuery=q.value;clearTimeout(q._t);q._t=setTimeout(()=>{knowledgePage();const n=document.querySelector('[data-knowledge-search]');if(n){n.focus();n.setSelectionRange(n.value.length,n.value.length)}},180)});
 document.querySelectorAll('[data-width]').forEach(x=>x.style.width=Math.max(2,Math.min(100,Number(x.dataset.width)||0))+'%');
}
function renderRoute(){const r=route();setActiveNav(r);document.getElementById('topnav').classList.remove('open');document.getElementById('navToggle').setAttribute('aria-expanded','false');drawerRoot.innerHTML='';if(r==='overview')overview();else if(r==='work')workPage();else if(r==='runtime')runtimePage();else if(r==='performance')performancePageV2();else if(r==='news')newsPage();else if(r==='knowledge')knowledgePage();else if(r==='templates')templatesPage();window.scrollTo({top:0,behavior:'instant'})}
document.getElementById('navToggle').addEventListener('click',e=>{const nav=document.getElementById('topnav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
window.addEventListener('hashchange',renderRoute);window.addEventListener('popstate',renderRoute);
renderRoute();
if(location.protocol==='http:'||location.protocol==='https:')setInterval(()=>{if(!document.hidden)refreshData()},30000);
})();