# make_status.ps1 - regenerate STATUS.md (one-file mobile dashboard) + copy to OneDrive.
# Agents run this after every commit (AGENTS.md rule 7); safe to run manually anytime.
# ASCII-only source on purpose: PowerShell 5.1 chokes on BOM-less UTF-8 Thai literals.
$ErrorActionPreference = "SilentlyContinue"
$repo = "D:\EA_LAB"
$out  = Join-Path $repo "STATUS.md"
$oneDrive = "C:\Users\patip\OneDrive\EA_LAB_STATUS.md"

$now = Get-Date -Format "yyyy-MM-dd HH:mm"
$branch = git -C $repo rev-parse --abbrev-ref HEAD

$orders = Get-Content (Join-Path $repo "AGENT_TASKBOARD.md") -Encoding UTF8 |
  Where-Object { $_ -match '^## ORDER-' } |
  ForEach-Object { $_ -replace '^## ', '- ' }

$log = git -C $repo log --oneline -12 | ForEach-Object { "- $_" }

$body = @()
$body += "# EA_LAB STATUS  (auto-generated $now / branch: $branch)"
$body += ""
$body += "> Auto-regenerated by scripts\make_status.ps1 after every commit - do not edit by hand."
$body += "> Full detail: PROJECT_STATE.md / work queue: AGENT_TASKBOARD.md"
$body += ""
$body += "## Work queue (all orders)"
$body += $orders
$body += ""
$body += "## Recent commits"
$body += $log
$body | Set-Content $out -Encoding UTF8

if (Test-Path (Split-Path $oneDrive)) { Copy-Item $out $oneDrive -Force }
