# make_status.ps1 - regenerate STATUS.md (one-file mobile dashboard) + copy to OneDrive.
# Agents run this after every commit (AGENTS.md rule 7); safe to run manually anytime.
# ASCII-only source on purpose: PowerShell 5.1 chokes on BOM-less UTF-8 Thai literals.
$ErrorActionPreference = "SilentlyContinue"
$repo = "D:\EA_LAB"
$out  = Join-Path $repo "STATUS.md"
$oneDrive = "C:\Users\patip\OneDrive\EA_LAB_STATUS.md"

$now = Get-Date -Format "yyyy-MM-dd HH:mm"
$branch = git -C $repo rev-parse --abbrev-ref HEAD

$orders = Get-Content (Join-Path $repo "AGENT_TASKBOARD.md") -Encoding UTF8 |
  Where-Object { $_ -match '^## ORDER-' } |
  ForEach-Object { $_ -replace '^## ', '- ' }

$log = git -C $repo log --oneline -12 | ForEach-Object { "- $_" }

# --- ORDER-612 (S4): the Control Room block, from a VERIFIED snapshot or from nothing --------
#
# Design row 4 ("make_status.ps1 still has an 'unreadable = nothing found' path") is what this
# closes. The rule is NOT "never fail" and NOT "always fail": it is that this page never prints a
# number it did not obtain through snapshot_validator.
#
# PRE-REGISTERED, and deliberately different from monitor_coverage.ps1's answer to the same three
# states (both are written down in scripts\lib\snapshot_reader.ps1):
#   OK          -> render the verdict and the counts.
#   REFUSED     -> render a REFUSED banner with the refusal text. NO numbers. exit 0.
#   UNAVAILABLE -> render an UNAVAILABLE banner. NO numbers. exit 0.
#
# Why exit 0 in both failure states, when the daily chain goes red for the same input: this script
# runs after EVERY commit (AGENTS.md rule 7). A reader that fails closed on a MISSING snapshot
# would convert "no snapshot has been built yet" -- true in a fresh clone, and true for anyone who
# has not run the builder -- into "this repo cannot finish a commit". That is a self-inflicted
# outage, not a safety property, and absence already IS loud in the place that owns it: the daily
# chain returns a hard failure token for exactly the same three states.
#
# $ErrorActionPreference is 'SilentlyContinue' for this whole file, which is itself the
# "unreadable = nothing found" habit. It is narrowed to 'Continue' around this block so a failure
# here cannot be swallowed; Get-VerifiedSnapshot is preference-independent by construction (it
# keeps native stderr out of the pipeline), and that independence is asserted by
# scripts\_test\run_monitor_integrity_tests.ps1.
$savedEap = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
. (Join-Path $repo 'scripts\lib\snapshot_reader.ps1')
$cr = Get-VerifiedSnapshot -SnapshotPath (Join-Path $repo 'portfolio\control_room_snapshot.json') -RepoRoot $repo
$ErrorActionPreference = $savedEap

$crLines = Format-ControlRoomBlock -Verified $cr

$body = @()
$body += "# EA_LAB STATUS  (auto-generated $now / branch: $branch)"
$body += ""
$body += "> Auto-regenerated by scripts\make_status.ps1 after every commit - do not edit by hand."
$body += "> Full detail: PROJECT_STATE.md / work queue: AGENT_TASKBOARD.md"
$body += ""
$body += "## Control Room (verified snapshot only)"
$body += $crLines
$body += ""
$body += "## Work queue (all orders)"
$body += $orders
$body += ""
$body += "## Recent commits"
$body += $log
$body | Set-Content $out -Encoding UTF8

if (Test-Path (Split-Path $oneDrive)) {
  Copy-Item $out $oneDrive -Force
  Copy-Item (Join-Path $repo "EA_MASTER_INDEX.csv") "C:\Users\patip\OneDrive\EA_MASTER_INDEX.csv" -Force
}

# STATUS.html - single-file visual dashboard (same data, same OneDrive drop)
& (Join-Path $PSScriptRoot "make_status_html.ps1")

