#!/usr/bin/env python3
"""Batch pipeline: scan report files -> parse -> score -> central registry.

For every MT5 single-test HTML it parses + scores (BacktestScore v1).
For every optimizer XML it records the top pass.
Writes D:\\EA_LAB\\RUN_REGISTRY.csv and RUN_REGISTRY.md.

Usage: python run_pipeline.py [root ...]   (default: ea_projects + _mt5_report_drop)
"""
import csv
import os
import sys
from pathlib import Path

# import the (fixed) parser from the installed skill + local scorer
SKILLS = r"C:\Users\patip\.claude\skills\backtest-report-analyzer\scripts"
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SKILLS)
sys.path.insert(0, HERE)
import parse_mt5_report as P          # noqa: E402
import score_backtest as SB           # noqa: E402

LAB = r"D:\EA_LAB"
DEFAULT_ROOTS = [os.path.join(LAB, "ea_projects"), os.path.join(LAB, "_mt5_report_drop")]


def guess_strategy(s):
    s = s.lower()
    if "grid" in s:
        return "grid"
    if "scalp" in s:
        return "scalping"
    if "breakout" in s:
        return "breakout"
    if any(k in s for k in ("pivot", "mean", "smc", "revert", "range")):
        return "mean_reversion"
    if "swing" in s:
        return "swing"
    return "default"


def project_of(path):
    parts = Path(path).parts
    if "ea_projects" in parts:
        i = parts.index("ea_projects")
        if i + 1 < len(parts):
            return parts[i + 1]
    return "(drop)"


def main():
    roots = sys.argv[1:] or DEFAULT_ROOTS
    files = []
    for root in roots:
        for dp, _, fns in os.walk(root):
            if "_legacy" in dp:
                continue
            for fn in fns:
                ext = fn.lower().rsplit(".", 1)[-1]
                if ext in ("html", "htm", "xml"):
                    files.append(os.path.join(dp, fn))

    records, errors = [], []
    for f in sorted(files):
        proj = project_of(f)
        try:
            ext = f.lower().rsplit(".", 1)[-1]
            if ext == "xml":
                d = P.parse_optimizer_xml(Path(f), top=1)
                ps = d.get("passes") or []
                if not ps:
                    continue
                t = ps[0]
                records.append({
                    "project": proj, "type": "optimizer", "ea_name": "",
                    "symbol": "", "period": "", "PF": t.get("profit_factor"),
                    "DD%": t.get("max_drawdown_percent"), "RF": t.get("recovery_factor"),
                    "trades": t.get("total_trades"), "net": t.get("net_profit"),
                    "score": "", "verdict": f"top of {d.get('total_passes')} passes",
                    "file": f,
                })
            else:
                d = P.parse_html_report(Path(f))
                if d.get("profit_factor") is None or not d.get("total_trades"):
                    continue                      # not a tester report
                strat = guess_strategy(proj + " " + (d.get("ea_name") or ""))
                v = SB.score(d, strat)
                m = v["metrics"]
                records.append({
                    "project": proj, "type": "single", "ea_name": d.get("ea_name"),
                    "symbol": d.get("symbol"), "period": d.get("period"),
                    "PF": m["PF"], "DD%": m["DD%"], "RF": m["RF"],
                    "trades": m["trades"], "net": m["net"],
                    "score": v["BacktestScore"], "verdict": v["verdict"], "file": f,
                })
        except Exception as e:
            errors.append((f, repr(e)[:120]))

    cols = ["project", "type", "ea_name", "symbol", "period", "PF", "DD%", "RF",
            "trades", "net", "score", "verdict", "file"]
    with open(os.path.join(LAB, "RUN_REGISTRY.csv"), "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(records)

    order = {"PASS": 0, "WATCH": 1, "REJECT": 2}
    singles = sorted([r for r in records if r["type"] == "single"],
                     key=lambda r: (order.get(r["verdict"], 3), -(r["score"] or 0)))
    opt = [r for r in records if r["type"] == "optimizer"]
    md = ["# RUN REGISTRY", "",
          f"> auto-generated by run_pipeline.py · {len(records)} reports · {len(errors)} errors",
          "", "## Single backtests (scored)", "",
          "| Verdict | Score | Project | Symbol | PF | DD% | RF | Trades | Net | File |",
          "|---|---:|---|---|---:|---:|---:|---:|---:|---|"]
    for r in singles:
        md.append("| {verdict} | {score} | {project} | {symbol} | {PF} | {DD%} | {RF} | "
                  "{trades} | {net} | {f} |".format(f=os.path.basename(r["file"]), **r))
    if opt:
        md += ["", "## Optimizer runs (top pass)", "",
               "| Project | PF | DD% | RF | Trades | Net | Passes | File |",
               "|---|---:|---:|---:|---:|---:|---|---|"]
        for r in opt:
            md.append("| {project} | {PF} | {DD%} | {RF} | {trades} | {net} | {verdict} | {f} |"
                      .format(f=os.path.basename(r["file"]), **r))
    if errors:
        md += ["", "## Parse errors", ""]
        md += [f"- {os.path.basename(f)} — {e}" for f, e in errors]
    Path(os.path.join(LAB, "RUN_REGISTRY.md")).write_text("\n".join(md), encoding="utf-8")

    npass = sum(1 for r in singles if r["verdict"] == "PASS")
    nwatch = sum(1 for r in singles if r["verdict"] == "WATCH")
    print(f"reports={len(records)} single={len(singles)} optimizer={len(opt)} errors={len(errors)}")
    print(f"  PASS={npass} WATCH={nwatch} REJECT={len(singles)-npass-nwatch}")
    print(f"wrote {LAB}\\RUN_REGISTRY.md + .csv")


if __name__ == "__main__":
    main()
