<#
.SYNOPSIS
    ORDER-251 -- mirror the skills library into the repo and hash-cage it.

.DESCRIPTION
    The skills under C:\Users\patip\.claude\skills own the decision bars this
    whole project runs on: backtest-optimize-rigor owns THE LADDER, and the
    DEMOTED banner / corr ladder / FINAL RULE live there too. None of it was in
    git. No history, no diff, nothing to compare against -- so "the bar has not
    drifted since 2026-07-18" was an assertion, not a fact. Meanwhile ORDER-102
    and ORDER-103 built an append-chain tamper cage for the taskboard.

    This mirrors (never moves -- Claude Code must still find the originals where
    they live) the library into docs/skills_mirror/ and writes a sha256 manifest.
    check_state.ps1 compares the live library against that manifest, so drift
    shows up as a warning on the next commit instead of never.

      -Update   refresh the mirror + manifest from the live library
      -Check    compare live library to the committed manifest (read-only)

    Symlinked skills are followed and mirrored by CONTENT: several skills are
    symlinks into C:\Users\patip\.agents\skills, and a mirror of a link is worth
    nothing. The manifest records which ones arrived that way.

    Exit: 0 clean, 1 drift (only under -Check), 2 tooling failure.
#>
param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$SkillsRoot = (Join-Path $env:USERPROFILE '.claude\skills'),
    [switch]$Update,
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

if (-not $Update -and -not $Check) { $Check = $true }

$mirrorDir = Join-Path $RepoRoot 'docs\skills_mirror'
$manifestPath = Join-Path $mirrorDir 'MANIFEST.sha256'

if (-not (Test-Path -LiteralPath $SkillsRoot)) {
    Write-Host ("[skills-mirror] TOOLING: skills root not found: {0}" -f $SkillsRoot) -ForegroundColor Red
    exit 2
}

function Get-LiveSkillFiles {
    <# .NET's EnumerateFiles follows reparse points on Windows, which
       Get-ChildItem -Recurse does not -- and 11 of the 26 skills are symlinks
       into .agents\skills, so the PowerShell-native walk would have quietly
       mirrored an empty shell. #>
    param([string]$Root)
    $rootFull = [System.IO.Path]::GetFullPath($Root).TrimEnd('\')
    $out = New-Object System.Collections.Generic.List[object]
    foreach ($f in [System.IO.Directory]::EnumerateFiles($rootFull, '*', [System.IO.SearchOption]::AllDirectories)) {
        $rel = $f.Substring($rootFull.Length + 1)
        # Skip VCS/tooling internals. .agents\skills is itself a git repo, so
        # following the symlinks drags its .git along -- and copying a .git into
        # the mirror makes git store the whole tree as a GITLINK (mode 160000),
        # i.e. a bare commit pointer with none of the content. The first version
        # of this did exactly that and committed a mirror holding zero files
        # while reporting success.
        $segments = $rel -split '[\\/]'
        if ($segments -contains '.git' -or $segments -contains 'node_modules' -or $segments -contains '__pycache__') { continue }
        $out.Add([pscustomobject]@{ Rel = $rel; Full = $f })
    }
    # Deterministic order, or the manifest churns for no reason.
    return @($out | Sort-Object { $_.Rel } -CaseSensitive)
}

function Get-Sha256 {
    param([string]$Path)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $stream = [System.IO.File]::OpenRead($Path)
        try { return ([System.BitConverter]::ToString($sha.ComputeHash($stream)) -replace '-','').ToLowerInvariant() }
        finally { $stream.Dispose() }
    } finally { $sha.Dispose() }
}

$live = Get-LiveSkillFiles -Root $SkillsRoot
$liveMap = @{}
foreach ($f in $live) { $liveMap[$f.Rel] = Get-Sha256 -Path $f.Full }

# Which top-level skill dirs are symlinks -- recorded as provenance, because a
# skill that lives in .agents is shared with other tools and can change from
# outside this project entirely.
$linked = @{}
foreach ($d in [System.IO.Directory]::EnumerateDirectories($SkillsRoot)) {
    $info = New-Object System.IO.DirectoryInfo($d)
    if (($info.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        $linked[$info.Name] = $true
    }
}

if ($Update) {
    if (Test-Path -LiteralPath $mirrorDir) { Remove-Item -LiteralPath $mirrorDir -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $mirrorDir | Out-Null

    foreach ($f in $live) {
        $dest = Join-Path (Join-Path $mirrorDir 'skills') $f.Rel
        $parent = Split-Path -Parent $dest
        if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
        Copy-Item -LiteralPath $f.Full -Destination $dest -Force
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# ORDER-251 skills mirror manifest -- GENERATED by scripts/sync_skills_mirror.ps1 -Update')
    $lines.Add('# sha256  via-symlink  relative-path')
    $lines.Add(('# source: {0}' -f $SkillsRoot))
    $lines.Add(('# files: {0}' -f $live.Count))
    foreach ($f in $live) {
        $top = ($f.Rel -split '[\\/]')[0]
        $via = if ($linked.ContainsKey($top)) { 'link' } else { 'real' }
        $lines.Add(('{0}  {1}  {2}' -f $liveMap[$f.Rel], $via, ($f.Rel -replace '\\','/')))
    }
    Set-Content -LiteralPath $manifestPath -Value $lines -Encoding UTF8
    Write-Host ("[skills-mirror] updated: {0} files mirrored, {1} of {2} top-level skills are symlinks" -f $live.Count, $linked.Count, ([System.IO.Directory]::GetDirectories($SkillsRoot)).Count) -ForegroundColor Green
    exit 0
}

# ---- Check ----
if (-not (Test-Path -LiteralPath $manifestPath)) {
    Write-Host '[skills-mirror] no manifest yet -- run: powershell -File scripts\sync_skills_mirror.ps1 -Update' -ForegroundColor Yellow
    exit 1
}

$recorded = @{}
foreach ($line in (Get-Content -LiteralPath $manifestPath -Encoding UTF8)) {
    if ($line.StartsWith('#') -or -not $line.Trim()) { continue }
    $parts = $line -split '\s+', 3
    if ($parts.Count -lt 3) { continue }
    $recorded[($parts[2] -replace '/','\')] = $parts[0]
}

$changed = @(); $added = @(); $removed = @()
foreach ($rel in $liveMap.Keys) {
    if (-not $recorded.ContainsKey($rel)) { $added += $rel }
    elseif ($recorded[$rel] -ne $liveMap[$rel]) { $changed += $rel }
}
foreach ($rel in $recorded.Keys) {
    if (-not $liveMap.ContainsKey($rel)) { $removed += $rel }
}

$drift = $changed.Count + $added.Count + $removed.Count
if ($drift -eq 0) {
    Write-Host ("[skills-mirror] clean -- {0} files match the committed manifest" -f $live.Count) -ForegroundColor Green
    exit 0
}

Write-Host ("[skills-mirror] DRIFT: {0} changed, {1} added, {2} removed vs the committed manifest" -f $changed.Count, $added.Count, $removed.Count) -ForegroundColor Yellow
foreach ($r in ($changed | Sort-Object)) { Write-Host ("  changed: {0}" -f $r) }
foreach ($r in ($added   | Sort-Object)) { Write-Host ("  added  : {0}" -f $r) }
foreach ($r in ($removed | Sort-Object)) { Write-Host ("  removed: {0}" -f $r) }
Write-Host ''
Write-Host '  A bar that changed without a commit is the thing this check exists for.'
Write-Host '  If the change is intended: powershell -File scripts\sync_skills_mirror.ps1 -Update'
Write-Host '  and commit the mirror in the same commit as whatever justified it.'
exit 1
