import {AUTHORITY, STAGES, validatePack, project, ownerActions, qualify} from './model.mjs';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? 'UNKNOWN').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge = s => `<span class="badge ${esc(String(s).toLowerCase().replace(/[^a-z]/g,''))}">${esc(s)}</span>`;
const screens=[['overview','◫','Overview'],['research','▤','Research board'],['templates','▦','Template readiness'],['optimization','◎','Optimization'],['evidence','▧','Report / evidence'],['blockers','⊞','Blockers'],['owner','◇','Owner action']];
let pack, scenario='normal', search='', filter='ALL', nativeState='PENDING', nativeUrl, lastFocus;
const options=()=>({now:Date.now(),scenario,online:navigator.onLine});
const rows=key=>project(pack,pack[key],options());
const valid=()=>qualify(pack,{...pack,refSha:pack.baseSha,source:'fixtures.json'},options())==='FRESH';
const short=s=>String(s ?? 'UNKNOWN').slice(0,8);
const provenance=(row)=>`<div class="provenance"><span>FIXTURE · NO AUTHORITY</span>${badge(row.freshness)}<button class="inspect" data-inspect="${esc(row.id)}">Source & ref ↗</button></div>`;
const summarySource=()=>`<div class="provenance">Derived from qualified fixture rows · excludes unresolved observations<button class="inspect" data-snapshot>Source & derivation ↗</button></div>`;
const heading=(title,sub)=>`<div class="page-title"><div><h2>${title}</h2><p>${sub}</p></div></div>`;
const unknown=()=>`<div class="note">UNKNOWN / PENDING — this snapshot is ${esc(scenario === 'normal' ? 'not current or qualified' : scenario)}. Current readiness, counts and owner requests are suppressed.</div>`;
function ownerMarkup(compact=false){
 const actions=ownerActions(pack,options());
 return actions.length ? actions.map(r=>`<article class="${compact?'row':'card'}" data-owner-action><div><div class="family-id">EXPLICIT E · FICTIONAL REQUEST</div><h3>${esc(r.title)}</h3><p>${esc(r.data.action)}</p>${compact?'':`<p class="muted">${esc(r.data.scope)}</p><p class="muted">Expires ${esc(r.data.expiresAt)} · bound to ${short(r.refSha)}</p>`}${provenance({...r,freshness:'FRESH'})}</div></article>`).join('') : `<div class="empty">No owner action currently derived.<br><small>Unknown, stale, expired and unbound requests fail closed. This does not establish that no real decisions are outstanding.</small></div>`;
}
function researchCard(r){const d=r.display;return `<article class="card" data-research-card><div class="card-head"><div><div class="family-id">${esc(r.id)} · ${esc(d.family || 'IDENTITY PENDING')}</div><h3>${esc(r.title)}</h3></div>${badge(r.state)}</div>${r.known?`<div class="setup">${esc(d.setup)}</div><div class="mini-rail" aria-label="Current stage ${esc(d.stage)}">${STAGES.map(s=>`<span class="${s===d.stage?'current':''}"></span>`).join('')}</div><small>Stage ${badge(d.stage)}</small><p class="next">${esc(d.evidence)}</p><div class="pair"><div><label>MAIN</label><strong>${esc(d.main)}</strong></div><div><label>BWD</label><strong>${esc(d.bwd)}</strong></div><div><label>OPTIMIZATION</label><strong>${esc(d.optimization)}</strong></div><div><label>MODEL4</label><strong>${esc(d.model4)}</strong></div></div><div class="next"><span>NEXT RESEARCH ACTION · FIXTURE</span>${esc(d.next)}</div><p class="blocker-note">${esc(d.blocker)}</p>`:`<div class="graph-panel">${badge('UNKNOWN')}<p>Stage, evidence and next action are PENDING until a fresh, bound observation is supplied.</p></div>`}${provenance(r)}</article>`;}
function overview(){
 const rr=rows('research'), lr=rows('lanes');const ready=rr.find(r=>r.state==='READY');
 return heading('Research at a glance','A decision-sized view of the conveyor · fictional sample queue')+
 (!valid()?unknown():'')+
 `<div class="hero"><div><div class="hero-kicker">NEXT INTO RESEARCH · FIXTURE</div><h2>${ready?esc(ready.title):'Readiness UNKNOWN'}</h2><p>${ready?'Prerequisite fixture is complete. Next: inspect the Model1 plan and its evidence binding. READY here is a sample queue label; it grants no execution permission.':'A fresh, bound fixture is required before showing the next research item.'}</p></div><button data-go="research">Inspect research queue →</button></div>`+
 `<div class="metrics">${['READY','BLOCKED','PARKED','RUNNING','NEED BOSS'].map(s=>`<div class="metric"><label>${s}</label><strong class="${valid()?s.toLowerCase()+'-text':'unknown-text'}">${valid()?(s==='NEED BOSS'?ownerActions(pack,options()).length:rr.filter(r=>r.state===s).length):'UNKNOWN'}</strong><small>${s==='NEED BOSS'?'qualified sample actions':'qualified sample EAs'}</small></div>`).join('')}</div>`+
 `<section class="panel"><div class="panel-head"><h2>Research conveyor</h2><a href="#research">Board →</a></div><div class="rail">${STAGES.map(s=>`<div class="stage ${rr.some(r=>r.known&&r.display.stage===s)?'current':''}"><strong>${valid()?rr.filter(r=>r.known&&r.display.stage===s).length:'?'}</strong>${s}</div>`).join('')}</div><p class="rail-note">${rr.filter(r=>!r.known).length} unresolved observations excluded · stage counts do not prove earlier gates passed.</p>${summarySource()}</section>`+
 `<div class="grid-two"><section class="panel"><div class="panel-head"><h2>What is running?</h2>${badge(valid()?'FIXTURE':'UNKNOWN')}</div>${lr.map(r=>`<div class="row"><div><h3>${esc(r.title)}</h3><p>${esc(r.display.activity || 'Activity UNKNOWN / PENDING')}</p><small>Process health UNKNOWN · ownership ≠ execution</small></div><div class="row-end">${badge(r.state)}<br><button class="inspect" data-inspect="${r.id}">${esc(r.freshness)} ↗</button></div></div>`).join('')}<p class="rail-note">${valid()?lr.filter(r=>r.known&&r.state==='RUNNING').length:'UNKNOWN'} active fixture lane observations. No MT5 or VPS connection.</p>${summarySource()}</section><section class="panel"><div class="panel-head"><h2>NEED BOSS</h2><a href="#owner">Inspect →</a></div>${ownerMarkup(true)}</section></div>`+
 `<div class="grid-two"><section class="panel"><div class="panel-head"><h2>What slows research?</h2><a href="#blockers">Blockers →</a></div>${heatmap()}<p class="rail-note">One sample blocker per class. Fix the named dependency before adding more workers.</p>${summarySource()}</section><section class="panel"><div class="panel-head"><h2>Monitoring state</h2>${badge('UNKNOWN')}</div><p class="muted">No qualified monitor DTO was supplied. A successful UI load is not a healthy monitoring chain.</p><button class="inspect" data-snapshot>Source: fixture adapter / no live input ↗</button><div class="row"><div><h3>Changed since parent</h3><p>B15 historical CountBars: 2 → 3</p><small>Exact report source · Meta5c · research context only</small></div><a href="#evidence">Inspect →</a></div></section></div>`;
}
function heatmap(){const bs=rows('blockers');return `<div class="heatmap">${['A','B','C','D','E'].map((c,i)=>`<a class="heat ${valid()?'':'zero'}" href="#blockers"><span>${c}</span><strong>${valid()?bs.filter(r=>r.known&&r.data.category===c).length:'?'}</strong><span>${['Product','Harness','Environment','Incomplete','Owner'][i]}</span></a>`).join('')}</div>`;}
function research(){return heading('EA research board','Search families, evidence, next actions and blockers.')+`<div class="toolbar"><input class="search" id="research-search" type="search" aria-label="Search research" placeholder="Search EA, family or blocker…" value="${esc(search)}"><div class="filters" role="group" aria-label="Research status">${['ALL','READY','BLOCKED','PARKED','UNKNOWN'].map(f=>`<button data-filter="${f}" class="${f===filter?'selected':''}" aria-pressed="${f===filter}">${f}</button>`).join('')}</div></div><p class="muted" id="result-count" aria-live="polite"></p><div class="research-grid" id="research-results"></div>`;}
function filterResearch(){const rr=rows('research').filter(r=>(filter==='ALL'||r.state===filter)&&JSON.stringify({title:r.title,id:r.id,...r.display}).toLowerCase().includes(search.toLowerCase()));$('#research-results').innerHTML=rr.length?rr.map(researchCard).join(''):'<div class="empty">No matching research. Try another family or status.</div>';$('#result-count').textContent=`${rr.length} of ${pack.research.length} sample records · source and freshness on every card`;}
function templates(){return heading('Template readiness','Sample family matrix · readiness is not permission to run.')+`<div class="note">Illustrative rows below are not canonical family readiness. Read the pinned readiness document for its historical scope; newer contracts must be reconciled separately.</div><section class="panel"><div class="table-scroll"><table class="template-table"><thead><tr><th>Family</th><th>Semantics</th><th>Build / set</th><th>Source review</th><th>Evidence pack</th><th>Provenance</th></tr></thead><tbody>${rows('templates').map(r=>`<tr><td>${esc(r.title)}<br><small>${esc(r.display.missing || 'UNKNOWN / PENDING')}</small></td>${['semantics','build','review','packaging'].map(k=>`<td>${badge(r.display[k]||'UNKNOWN')}</td>`).join('')}<td><button class="inspect" data-inspect="${r.id}">Fixture · ${esc(r.freshness)} ↗</button></td></tr>`).join('')}</tbody></table></div><p class="rail-note mobile-only">Swipe the matrix to inspect all readiness gates →</p></section><section class="panel"><h3>Semantics and packaging remain separate</h3><p class="muted">A complete set cannot settle an unresolved source behavior. A passing build cannot supply missing native graph bytes. Each has its own visible gate.</p>${sourceLink('docs/architecture/EA_TEMPLATE_XX00_BACKTEST_READINESS_V1.md')}</section>`;}
function optimization(){return heading('Optimization','Map stable regions. Freeze the center before BWD. Preserve HOLDOUT.')+`<div class="research-grid">${rows('optimizations').map(r=>`<article class="card"><div class="card-head"><h3>${esc(r.title)}</h3>${badge(r.state)}</div><div class="gate-list">${[['Prerequisites','prerequisites'],['Search status','search'],['Stable region','region'],['Center frozen?','center'],['BWD spent?','bwd'],['HOLDOUT','holdout'],['Model4 gate','model4']].map(([label,k])=>`<div class="gate"><span>${label}</span>${badge(r.display[k]||'UNKNOWN')}</div>`).join('')}</div><div class="next"><span>NEXT</span>${esc(r.display.next || 'PENDING fresh bound evidence')}</div>${provenance(r)}</article>`).join('')}</div><section class="panel"><h3>Gate context</h3><p class="muted">An in-sample search map is not a candidate verdict. This prototype has no start, resume, freeze, approval or promotion controls.</p>${sourceLink('docs/research/EA_REPORT_SCHEMA.md')}</section>`;}
function sourceLink(path){const s=pack.sources.find(x=>x.path===path);return s?`<p class="source-list"><a href="${esc(s.href)}" target="_blank" rel="noreferrer">${esc(path)} ↗</a><br><small>PINNED HISTORICAL · ${short(s.refSha)} · NO AUTHORITY</small><br><button class="inspect" data-source="${esc(path)}">Full SHA / hash / provenance ↗</button></p>`:'';}
function graphMarkup(){return `<div class="graph-panel" id="native-panel">${badge(nativeState)}<p>${nativeState==='EXACT'?'Verified original bytes · historical MAIN asset only.':nativeState==='REFUSED'?'Native bytes failed identity, hash or decoding checks. No replacement graph.':'Verifying native asset bytes…'}</p>${nativeState==='EXACT'?`<img class="native-img" src="${nativeUrl}" alt="Original B15 CountBars 3 GBPUSD H4 MAIN Model1 native MT5 graph, Meta5c, historical source"><button data-native>Inspect original larger ↗</button>`:''}</div>`;}
function evidence(){return heading('Report & evidence','Key parameters first. Native graphs retain their exact source identity.')+`<section class="panel"><div class="card-head"><div><div class="family-id">PINNED HISTORICAL ARTIFACT · NOT A SAMPLE EA RESULT</div><h3>${esc(pack.native.title)}</h3><p class="setup">${esc(pack.native.lane)} · ${esc(pack.native.model)} · MAIN ${esc(pack.native.window)} · ${short(pack.baseSha)}</p></div>${badge('HISTORICAL')}</div><div class="parameter-key"><span class="eyebrow">KEY CHANGED PARAMETER</span><code>_15_CountBars</code><strong><span class="strike">2</span> <span class="delta">→ 3</span></strong><p class="muted">One-change child. Parent and child share MACD 12 / 26 / 9. Values are historical source declarations, never current defaults.</p></div><div class="table-scroll"><table><thead><tr><th>Key parameter</th><th>Parent</th><th>Child</th><th>Change</th></tr></thead><tbody><tr class="changed"><td>_15_CountBars</td><td>2</td><td>3</td><td class="delta">+1</td></tr><tr><td>MACD periods</td><td>12 / 26 / 9</td><td>12 / 26 / 9</td><td>Frozen</td></tr></tbody></table></div>${sourceLink('docs/research/B15_COUNTBARS_SENS_01_RESULTS.md')}<details><summary>Historical tested setup & parameter context</summary><p class="muted">The pinned report describes fixed first lot 0.01, STACK_SINGLE, no progression, no recovery and no hedge. These describe the historical experiment only. Full parameter identity and source evidence remain in the linked report.</p><label for="parameter-search" class="muted">Search displayed parameter context</label><input id="parameter-search" class="search" type="search" placeholder="e.g. CountBars, MACD, StackMode"><div id="parameter-results"></div></details></section><div class="grid-two"><section class="panel"><div class="panel-head"><h2>MAIN · original MT5 graph</h2>${badge(nativeState)}</div>${graphMarkup()}<button class="inspect" data-native-source>Asset source / SHA-256 ↗</button></section><section class="panel"><div class="panel-head"><h2>BWD · no graph supplied</h2>${badge('MISSING')}</div><div class="graph-panel">${badge('MISSING')}<p>This prototype has no explicitly bound BWD native asset. It makes no claim that the repository lacks one.</p></div><div class="provenance">Source: static adapter / BWD omitted · PENDING · NO AUTHORITY<button class="inspect" data-snapshot>Inspect ↗</button></div><div class="graph-panel">${badge('REFUSED')}<p>Negative fixture: asset hash differs from the declared hash. Image display is refused. No graph is reconstructed.</p></div><div class="provenance">Source: test hash-mismatch case · FIXTURE · NO AUTHORITY<button class="inspect" data-refused>Inspect ↗</button></div></section></div><section class="panel"><h3>Report ladder & source contracts</h3>${sourceLink('docs/research/EA_REPORT_LADDER.md')}${sourceLink('tools/mobile_report_hub/README.md')}</section>`;}
function blockers(){return heading('What prevents faster research?','Five explicit blocker classes · fixture data only.')+`<section class="panel">${heatmap()}${summarySource()}</section>${rows('blockers').map(r=>`<section class="card"><div class="card-head"><h3>${esc(r.display.category || '?')} · ${esc(r.title).toUpperCase()}</h3>${badge(r.state)}</div><p>${esc(r.display.reason || 'Reason UNKNOWN / PENDING')}</p><small>Affects: ${esc(r.display.affected)}</small><div class="next"><span>UNBLOCKING STEP · PRESENTATION ONLY</span>${esc(r.display.next || 'Obtain fresh bound evidence')}</div>${provenance(r)}</section>`).join('')}`;}
function owner(){return heading('Owner action','Only explicit, qualified, fresh, unexpired E-class actions appear.')+`<div class="note">These are fictional requests for testing the product flow. No action here can approve research, change a default, sign an attestation or launch a worker.</div>${ownerMarkup()}<section class="panel"><h3>Fail-closed action qualification</h3><p class="muted">A current envelope, a unique row, matching SHA, valid observation time, explicit request, qualified E blocker and unexpired action are all required. Generic attention and historical prose create no action.</p><p class="muted">Stale / offline / unbound conditions remove requests immediately. The drawer also closes when qualification changes.</p>${summarySource()}</section>`;}
function currentScreen(){const key=location.hash.slice(1);return screens.some(s=>s[0]===key)?key:'overview';}
function render(){
 const screen=currentScreen();document.title=`EA_LAB · ${screens.find(s=>s[0]===screen)[2]}`;
 $('nav').innerHTML=screens.map(([key,icon,label])=>`<a href="#${key}" class="${screen===key?'active':''}" ${screen===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('');
 $('#snapshot-bar').innerHTML=`<div class="snapshot"><span>STATIC FIXTURE</span>${badge(valid()?'FRESH':qualify(pack,{...pack,refSha:pack.baseSha,source:'fixtures.json'},options()))}<span>Observed ${esc(pack.observedAt.replace('T',' ').replace('Z',' UTC'))}</span><span>Pinned canonical <a href="https://github.com/BaBosss/EA_LAB/commit/${pack.baseSha}" target="_blank" rel="noreferrer">${short(pack.baseSha)} ↗</a></span><button class="inspect" data-snapshot>Source contract ↗</button></div>`;
 $('#main').innerHTML=({overview,research,templates,optimization,evidence,blockers,owner}[screen])();
 if(screen==='research')filterResearch();if(screen==='evidence')filterParams('');
}
function openDrawer(title,html){lastFocus=document.activeElement;$('#drawer-title').textContent=title;$('#drawer-body').innerHTML=html;$('#drawer').showModal();}
function closeDrawer(){if($('#drawer').open)$('#drawer').close();lastFocus?.focus?.();}
function snapshotDrawer(){openDrawer('Static adapter contract',`<div class="note">PRESENTATION ONLY / NO AUTHORITY</div><dl><dt>Source</dt><dd><a href="fixtures.json" target="_blank">fixtures.json</a> · all FX rows are invented UX examples</dd><dt>Pinned canonical SHA</dt><dd class="code">${pack.baseSha}</dd><dt>Observed</dt><dd>${pack.observedAt}</dd><dt>Freshness</dt><dd>24-hour ceiling; future time over 5 minutes, malformed, unbound and offline inputs fail closed. Static snapshots age naturally; no timestamp refresh is performed.</dd><dt>Counts / next research</dt><dd>Counts include only unique, fresh, bound OBSERVED rows. Next research is the first qualified READY fixture, not a dispatch instruction. Missing monitor input is UNKNOWN.</dd><dt>Binding meaning</dt><dd>The base SHA pins design context. It does not turn invented fixture facts into canonical project facts.</dd><dt>Authority</dt><dd>${AUTHORITY}</dd></dl><h3>Pinned sources consulted</h3><ul class="source-list">${pack.sources.map(s=>`<li><a href="${s.href}" target="_blank" rel="noreferrer">${esc(s.path)}</a><br><button class="inspect" data-source="${esc(s.path)}">Hash / source observation ↗</button></li>`).join('')}</ul>`);}
function inspect(id){const r=['research','lanes','templates','optimizations','blockers','actions'].flatMap(rows).find(r=>r.id===id);if(!r)return;openDrawer(r.title,`<div class="note">FICTIONAL OBSERVATION · NO AUTHORITY</div><dl><dt>Source / JSON pointer</dt><dd><a href="fixtures.json" target="_blank">${esc(r.source)}</a></dd><dt>Ref SHA (design context only)</dt><dd class="code">${esc(r.refSha)}</dd><dt>Observed / freshness</dt><dd>${esc(r.observedAt)} · ${esc(r.freshness)}</dd><dt>Source status / displayed status</dt><dd>${esc(r.status)} / ${esc(r.state)}</dd><dt>Authority</dt><dd>${esc(r.authority)}</dd></dl>${r.known?`<h3>Qualified fixture fields</h3><pre>${esc(JSON.stringify(r.display,null,2))}</pre>`:'<p>UNKNOWN / PENDING. Unqualified content is suppressed, including next actions.</p>'}`);}
function showSource(s){openDrawer('Source provenance',`<dl>${Object.entries(s).map(([k,v])=>`<dt>${esc(k)}</dt><dd class="code">${esc(v)}</dd>`).join('')}</dl>${s.href?.startsWith('https://github.com/BaBosss/EA_LAB/')?`<a href="${esc(s.href)}" target="_blank" rel="noreferrer">Open exact Git source ↗</a>`:''}`);}
const params=[['_15_CountBars','2 → 3'],['MACD periods','12 / 26 / 9'],['StackMode','90 / STACK_SINGLE'],['First lot','0.01'],['LotProg','50 / PROG_NONE'],['RecoveryMode','80 / REC_NONE'],['HedgeMode','0']];
function filterParams(q){if(!$('#parameter-results'))return;const found=params.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase()));$('#parameter-results').innerHTML=found.length?found.map(([k,v])=>`<div class="gate"><code>${esc(k)}</code><strong>${esc(v)}</strong></div>`).join(''):'<p>No matching displayed parameters.</p>';}
async function verifyNative(){
 try{const n=pack.native;if(n.refSha!==pack.baseSha||n.authority!==AUTHORITY||n.href!=='assets/b15-native-main.png'||!/^[a-f0-9]{64}$/.test(n.sha256))throw Error('binding');const response=await fetch(n.href,{cache:'no-store',redirect:'error'});if(!response.ok)throw Error('missing');const bytes=await response.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==n.sha256)throw Error('hash');const url=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));const img=new Image();img.src=url;try{await img.decode();}catch(e){URL.revokeObjectURL(url);throw e;}nativeUrl=url;nativeState='EXACT';}catch{nativeState='REFUSED';}
 if(currentScreen()==='evidence')render();
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){location.hash=b.dataset.go;}else if(b.hasAttribute('data-snapshot'))snapshotDrawer();else if(b.dataset.inspect)inspect(b.dataset.inspect);else if(b.dataset.source)showSource(pack.sources.find(s=>s.path===b.dataset.source));else if(b.hasAttribute('data-native-source'))showSource(pack.native);else if(b.hasAttribute('data-native')&&nativeState==='EXACT')openDrawer('Original native MT5 asset',`<p class="muted">${esc(pack.native.title)} · MAIN · Meta5c · HISTORICAL / NO AUTHORITY</p><img class="native-img" src="${nativeUrl}" alt="Original historical MT5 graph enlarged"><p class="code">SHA-256 ${pack.native.sha256}</p><a href="${pack.native.href}" target="_blank">Open original image ↗</a>`);else if(b.hasAttribute('data-refused'))openDrawer('Graph refusal fixture','<dl><dt>Source</dt><dd>Static negative scenario: browser.test.cjs / poisoned native asset</dd><dt>Status</dt><dd>REFUSED</dd><dt>Freshness</dt><dd>FIXTURE / NOT A LIVE OBSERVATION</dd><dt>Authority</dt><dd>PRESENTATION_ONLY_NO_AUTHORITY</dd></dl><p>Valid PNG bytes with a different SHA-256 must fail the native asset verifier. No image is shown or generated.</p>');else if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x.dataset.filter===filter);x.setAttribute('aria-pressed',x.dataset.filter===filter);});filterResearch();}});
document.addEventListener('input',e=>{if(e.target.id==='research-search'){search=e.target.value;filterResearch();}if(e.target.id==='parameter-search')filterParams(e.target.value);});
$('#scenario').addEventListener('change',e=>{scenario=e.target.value;closeDrawer();render();});$('#close-drawer').addEventListener('click',closeDrawer);
window.addEventListener('hashchange',()=>{closeDrawer();render();window.scrollTo(0,0);});
window.addEventListener('offline',()=>{closeDrawer();render();});window.addEventListener('online',()=>{closeDrawer();render();});
try{const response=await fetch('fixtures.json',{cache:'no-store',redirect:'error'});if(!response.ok)throw Error('Fixture unavailable');pack=validatePack(await response.json());render();verifyNative();let previous=JSON.stringify([rows('research'),ownerActions(pack,options())]);setInterval(()=>{const next=JSON.stringify([rows('research'),ownerActions(pack,options())]);if(next!==previous){previous=next;closeDrawer();render();}},1000);}catch(error){$('#main').innerHTML=`<div class="note"><h2>UNKNOWN / PENDING</h2><p>Static data is unavailable or invalid. No readiness or owner action can be derived.</p><small>${esc(error.message)}</small></div>`;}
